### ISSUE TITLE
[디자인 목록]디자인 이름 문자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#10]
우선순위:B, 
변경후: **문자 최대 100자로 제한**
변경전: _한글50자로 제한_

**Comment by sojung1418** [comment]
maxLength 지정을 해주어야했습니다.
1월31일(목) 수정완료

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글50자"에서 "문자100자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 varchar(100)로 최대100자까지 가능합니다.

**Comment by kimgyuri** [comment]
2월 21일까지 완료하도록 하겠습니다.

**Comment by kimgyuri** [comment]
디자인 이름 문자수 100자로 제한 완료하였습니다.
(/home/gyurl/opendesign/myfront/src/components/Designs/DesignBoardCard/CardTitleUpdate.js 
61번째줄 maxLength 추가, 64번째줄 텍스트 수정)
