### ISSUE TITLE
[파생디자인] 요구사항정리

### ISSUE THREAD

**Issue by sojung1418** [kmu-crc/osd_front#100]
Opensrcdesign.com : 사이트에 파생 디자인 관리에 대한 요구사항 정리할 것.

**Comment by sojung1418** [comment]
02/15 완료

**Comment by eleutheria80** [comment]
@opensrcdesign-admin , @sojung1418 현재 상태 정리해서 코멘트 남겨주세요. 완료일 경우 close 혹은 wait 등의 라벨 남겨주세요.

**Comment by eleutheria80** [comment]
@opensrcdesign-admin 요구사항 정리가 끝난 내용이면 협의하여서 닫아주세요
@sojung1418 새로운 프로젝트를 만들어서 정리를 해놓았는데 우리 메인 개발 프로젝트에 정리할 수 있는지 검토 해 주세요. 개발이 우선이므로 개발이 마무리 된 후에 검토 해 주세요.

**Comment by sojung1418** [comment]
@opensrcdesign-admin 요구사항정리는 끝났습니다.이슈 닫아주세요.
@eleutheria80 네 알겠습니다.

**Comment by ggamsang** [comment]
이 이슈는 교수님께 한 번 더 확인봤고 닫는 것을 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
금일(3월6일) 회의내용에 따라 해당이슈를 닫습니다.
