### ISSUE TITLE
[메인] UI 개선

### ISSUE THREAD

**Issue by Jinakimm** [kmu-crc/osd_front#107]
메인 화면에 사용자 가이드 없애고 배너 이미지를 뭘로 할지 결정
로그인 전 / 후
배너 키워드 문장으로 풀어쓰는 거에 대해서 (회사 사이트 소개에 있음) 생각해보기

**Comment by Jinakimm** [comment]
디자인 라벨

**Comment by Jinakimm** [comment]
메인 페이지 레이아웃 스케치

![main_layout](https://user-images.githubusercontent.com/47623887/53086561-b27d8a00-3548-11e9-88dd-602537bac494.jpg)
![main_layout2](https://user-images.githubusercontent.com/47623887/53086563-b27d8a00-3548-11e9-8c3e-f084fc716eff.jpg)
![main_layout3](https://user-images.githubusercontent.com/47623887/53086564-b27d8a00-3548-11e9-8fd1-f63aaa42f9da.jpg)

1. 웹페이지 기본 크기 1920*1080
2. 모바일 중 제일 작은 크기 320*568
==로그인 전
     검색 버튼이 축소화
==로그인 후
     사용자 이름이 사라지고 아이콘만 보임
3. 태블릿 크기 1024*768

**Comment by Jinakimm** [comment]
웹페이지 기본 크기에서 width 줄일 때 순서
1. 검색 버튼이 최소화 (아이콘만 남고 검색 하는 칸은 없어짐)
2. 사용자 이름이 사라짐 (사용자 아이콘만 남음)
>>모바일 버전으로 바뀜
*사용자 이름이 검색 버튼보다 먼저 사라지면 안된다고 생각합니다

**Comment by Jinakimm** [comment]
**메인페이지 카드 디스플레이**

![image](https://user-images.githubusercontent.com/47623887/53148621-b06e0680-35ee-11e9-82bb-058d2aab5b41.png)
마우스 커서 x

![image](https://user-images.githubusercontent.com/47623887/53148624-b4018d80-35ee-11e9-9f80-ef98a497cffc.png)
마우스 커서 o 
카드에 gradient black opacity 100 to 0 + 작품 이름 + 사용자 이름 + 좋아요 수와 조회수

**Comment by Jinakimm** [comment]
![14](https://user-images.githubusercontent.com/47623887/53301307-76259300-3894-11e9-8e59-6bafc38ee2d7.jpg)
.
.
.
.
![15](https://user-images.githubusercontent.com/47623887/53301308-76259300-3894-11e9-8085-4ca7cebdc607.jpg)
.
.
.
.
![image](https://user-images.githubusercontent.com/47623887/53301314-95bcbb80-3894-11e9-8097-5362bb610cbd.png)

**Comment by eleutheria80** [comment]
@opensrcdesign-admin , @Jinakimm 오류가 아닌 장기간 수정 이슈라면 생각하는 진행 방향과 일정 등을 정리해서 코멘트 남겨주세요.

**Comment by Jinakimm** [comment]
아직 디자인이 정확하게 결정된 것이 아니라 일단은 제가 디벨롭을 해서 그때 그때 올리겠습니다
3월 넘어야만 프로토타입도 정립이 될 것 같아서 정해진 due date는 없을 것 같습니다
