### ISSUE TITLE
[메인] 배너 이미지 및 문구

### ISSUE THREAD

**Issue by Jinakimm** [kmu-crc/osd_front#115]
메인페이지의 배너 이미지 및 문구

**Comment by Jinakimm** [comment]
**references**
![image](https://user-images.githubusercontent.com/47623887/53147929-62580380-35ec-11e9-94ae-ff87956d9c16.png)
![image](https://user-images.githubusercontent.com/47623887/53147956-756ad380-35ec-11e9-8ea3-f09e008666ea.png)
![image](https://user-images.githubusercontent.com/47623887/53147978-8adffd80-35ec-11e9-8c51-e593b381bb89.png)
![image](https://user-images.githubusercontent.com/47623887/53148014-a9de8f80-35ec-11e9-87be-e4d268ec8dfd.png)

**Comment by Jinakimm** [comment]
**사용자 가이드에 대한 아이디어**

![image](https://user-images.githubusercontent.com/47623887/53148202-53be1c00-35ed-11e9-9502-e53f91d947a0.png)
사용자 가이드를 메인페이지 배너에 올리지 않고 퍼스트유저가 접속하는 순간 위 사진처럼 구성된다면
사용자 가이드를 누르지 않아도 쉽게 사용자가 익힐 수 있습니다.

**Comment by Jinakimm** [comment]
**배너 문구 디벨롭**

**현재 배너**
오픈 디자인- 이유: 오픈소스 기반 플랫폼
쉬운 디자인- 이유: ?
함께하는 디자인- 이유: 그룹 활동을 통한 디자인 공유 시스템

**사이트 소개 문구**
* 개개인의 작은 디자인 아이디어가 모여 최고의 디자인으로 발전할 수 있습니다. (집단 지성)
* 사장될 수도 있는 개인의 디자인 아이디어가 다른 사람들에게 영감을 주어 디자인 생태계의 발전을 가져옵니다. (창의성 고양)
* 일반인들의 디자인에 대한 관심을 끌고 안목을 키워줄 수 있습니다.
* 디자인의 독창성, 우수성, 개선사항 등에 대한 다양한 분야의 전문가들의 평가와 조언을 즉각적으로 얻을 수 있습니다.
* 많은 발명이나 발견이 인류공영에 이바지 하였듯이 훌륭한 디자인이 수많은 사람들에게 혜택을 줄 수 있습니다.

**고안한 배너 문구**
오픈소스 디자인과 함께하세요! 

오픈소스 기반 플랫폼을 통해 당신의 아이디어를 최고의 디자인으로 만들어 보세요. (오픈 디자인의 설명)
다양한 사람들과 함께 멋진 디자인을 만들어 보세요. (함께하는 디자인의 설명)

당신의 아이디어가 최고가 되는 경험을 저희와 함께하세요.

디자인 등록하기 (활동 유도 버튼)

**Comment by opensrcdesign-admin** [comment]
@Jinakimm 디자인제안
@kimgyuri 디자인적용

**Comment by Jinakimm** [comment]
![14](https://user-images.githubusercontent.com/47623887/53301342-d9afc080-3894-11e9-97a0-12e1ea8e29b6.jpg)

**Comment by eleutheria80** [comment]
@opensrcdesign-admin , @Jinakimm, @kimgyuri 디자인 파트 제안을 검토 후 코멘트 남겨주세요.

**Comment by Jinakimm** [comment]
저번 회의 결과 디자인이 아직 확정이 되지 않아서 3월 넘어야 디자인에 관해서 제대로 정립할 수 있을 것 같습니다
due date를 명확히 정해놓지 않고 디자인팀이 저 혼자이니 디벨롭을 계속 해서 그때 그때 올리겠습니다
