### ISSUE TITLE
[디자인 상세보기] 카드 요약정보표시방식변경

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#123]
디자인 내에
![screenshot from 2019-02-23 19-09-04](https://user-images.githubusercontent.com/28895134/53284999-b1de3100-379e-11e9-8c3a-2564fa7d328d.png)
두줄로 표시되어 있는 시간과 작성자, 댓글를
한줄로 표시한다. 시간은 좌측, 작성자, 댓글은 우측으로 정렬한다.

**Comment by ggamsang** [comment]
due date: 02.24

**Comment by ggamsang** [comment]
![screenshot from 2019-02-24 17-22-55](https://user-images.githubusercontent.com/28895134/53296930-e6162800-3858-11e9-94c6-0d64f66f77ea.png)
좌측: 비포, 우측: 애프터

공간줘야하나?

**Comment by opensrcdesign-admin** [comment]
일단, develop 브런치에 머지함

**Comment by ggamsang** [comment]
좌측에 {업데이트일자} 우측에 {작성자} {댓글수} 가 원래 요구사항이었으나,
현재 적용된 좌측 {댓글수}{작성자} 우측에 {업데이트일자}가 보기 좋다고 생각하여 위와 같이 적용함.

**Comment by ggamsang** [comment]
![screenshot from 2019-02-25 22-27-41](https://user-images.githubusercontent.com/28895134/53340543-987ae780-394c-11e9-8ad0-580c259533a2.png)
위와 같이 변경!
wait_close해주라!
