### ISSUE TITLE
[디자인 상세보기] 디자인 상세내용부분 레이아웃 개선

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#124]
디자인 상세보기화면에서 
보드가 화면보다 길면 스크롤이 보이게 된다. 이때 '컨텐츠추가' 버튼도 같이 내려가 보이지 않게 된다.
이를 항상 보이도록 코드를 수정한다.

**Comment by ggamsang** [comment]
due date: 02.26

**Comment by opensrcdesign-admin** [comment]
회의시간에 잡은 일정대로 마감 기한(03.07) 전까지 하고, 중간에 계속 업데이트 바랍니다.
일정조정:
due date: 03.07

**Comment by ggamsang** [comment]
계속 딜레이되고 있습니다, 죄송합니다.
스타일시트를 적용 중인데 스타일시트의 계층구조로 적용해야하는 부분에서 어려움을 겪고있습니다.
13일까지 완료하겠습니다.

**Comment by opensrcdesign-admin** [comment]
2차개발로 미루고 88번 이슈에 집중할 것.
