### ISSUE TITLE
[디자인 등록]작품설명 - 글자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#13]
우선순위:B, 
변경후: **최대 문자 1000자로 제한하기**
변경전: _최대 한글 500자(1000자)로 제한하기_

**Comment by eleutheria80** [comment]
@sojung1418 원인 파악 후에 원인과 수정 예정일을 명시 해 주세요.

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글500자(1000자)"에서 "문자1000자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 longtext로 최대4294967295자까지 가능합니다.

**Comment by kimgyuri** [comment]
2월 22일까지 완료하도록 하겠습니다.

**Comment by kimgyuri** [comment]
디자인등록 작품설명 글자수 1000자 제한 완료하였습니다.
(/home/gyurl/opendesign/myfront/src/components/Designs/CreateDesignForm/CreateDesignForm.js
133번째줄 maxLength 추가, 134번째줄 수정)
