### ISSUE TITLE
[디자인 등록/수정] 섬네일 스케일기능 추가

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#132]
디자이너가 디자인 등록을 할 때, 수정할 때 섬네일의 크기를 정사각형으로 만드는 기능을 추가한다.

가로의 섬네일인 경우 
세로를 기준으로 가로의 중앙부분을 크롭하여 정사각형의 이미지를 만든다.

세로의 섬네일인 경우
가로를 기준으로 세로의 중앙부분을 크롭하여 정사각형의 이미지를 만든다.

**Comment by eleutheria80** [comment]
@opensrcdesign-admin 28일까지 작업이 불가능한 새로운 이슈일 경우에는 3월 작업 시 진행을 명시 해 주세요.

**Comment by kshahn** [comment]
정사각형 이미지가 아니라 현재 썸네일 이미지 크기에 맞춰 스케일링 한다는 얘기입니다. 현재 썸네일 이미지 표시 부분에 꽉 차도록.

**Comment by ggamsang** [comment]
@eleutheria80 3월달에 작업하도록하겠습니다.

**Comment by ggamsang** [comment]
메모:
https://jonathannicol.com/blog/2014/06/16/centre-crop-thumbnails-with-css/
참고해도좋을듯.

**Comment by opensrcdesign-admin** [comment]
(1) 디자인 목록 / 스타일시트 적용 전
![screenshot from 2019-03-02 22-58-54](https://user-images.githubusercontent.com/46555793/53682977-d9a13c00-3d3e-11e9-9387-41069a5bac72.png)
---------------------
(2) 디자인 목록 / 적용 후
![screenshot from 2019-03-02 22-59-04](https://user-images.githubusercontent.com/46555793/53683001-0bb29e00-3d3f-11e9-9422-49541918a3ec.png)
---------------------

(3) 디자인 상세보기 / 적용 전
![screenshot from 2019-03-02 22-59-24](https://user-images.githubusercontent.com/46555793/53682978-ddcd5980-3d3e-11e9-8249-ddeeda485de4.png)
---------------------
(4) 디자인 상세보기 / 적용 후
![screenshot from 2019-03-02 22-59-18](https://user-images.githubusercontent.com/46555793/53683010-26851280-3d3f-11e9-8dc6-39ce4a748f60.png)
---------------------

섬네일 크기조정 하는 알고리즘을 구현하기 전에 스타일시트에서 제공해주는 기능을 알아보았고
적합한 기능이라고 생각되어 위와 스타일시트를 사용하는 방법으로 적용될 것입니다,

섬네일의 가로/세로의 비율이 지나치게 차이가 나면 영상이 잘리는 경우가 발생합니다.
이를 해결하기 위해서는 섬네일 등록할 때 가이드를 해주는 기능이 다음버전에 추가되어야 할 것 같습니다.

아래의 영상이 위에서 말한 내용입니다.
![screenshot from 2019-03-02 23-04-05](https://user-images.githubusercontent.com/46555793/53683047-ba56de80-3d3f-11e9-9e02-02edb64fff90.png)
![screenshot from 2019-03-02 23-04-28](https://user-images.githubusercontent.com/46555793/53683048-bb880b80-3d3f-11e9-9cd6-e1a92d83b653.png)

**Comment by eleutheria80** [comment]
@ggamsang 이번 버전에 적용인 안되는 내용이라면 한번 정리 해 주시고 2월 개발로 넘겨주세요.

**Comment by opensrcdesign-admin** [comment]
@eleutheria80 현재 스타일시트로 이용하여 적용된 상태고 2차개발때는 위에서 말한 기능 구현할 예정입니다.
