### ISSUE TITLE
[마이페이지] 디자인카드들이 화면 밖에서 보이는 문제

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#133]
발생하는 경우
마이페이지에서 웹브라우저 zoom out  하면 뷰 밖으로 디자인카드가 출력되는 버그가 발생하고 있음.

원인파악 후 속히 조치바람.

**Comment by ggamsang** [comment]
오늘(2월27일)중에 파악하고 일정잡겠습니ㅏㄷ.

**Comment by ggamsang** [comment]
파악한 결과 반응형웹디자인을 위해 이와 같이 " mobile={..} tablet={...} computer={...} largeScreen={...}"
화면환경에 따라 표시방식을 정할 수 있습니다. 해당하는 컴포넌트에서 잘못쓰이고 있는 것으로 보입니다.
3월중에 해결해야할 것 같습니다.

**Comment by eleutheria80** [comment]
@ggamsang 다른 이슈 수정하며 발생한 사이드 이펙트 아닌가요? 원인되는 부분을 원복 등의 해결 방안 정리 해 주시고 현재 상태로 2차 개발로 넘길 경우 라벨을 달아서 넘겨주세요.

**Comment by opensrcdesign-admin** [comment]
@eleutheria80 확인한 결과 이 문제는 우리팀이 본격적으로 코드 수정하기 이전부터 가지고 있던 문제로 사이드이펙트라고 볼 수 없습니다.
이에 따라 원복은 무의미하게 보입니다. 좀 더 예전으로 돌려서 혹은 이 문제에 해당되는 파일의 히스토리를 보는 등하여 정상적으로 작동한적이 있었는지 알아봐야 할 것이고,
만약 정상적이었던 적이 없다면 위에서 말한대로 문제를 해결해야 합니다.

레이아웃에 대해 좀 더 파악한 후에 상세한 일정 잡도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
2차개발 떄 진행하는 것으로 하겠습니다.
