### ISSUE TITLE
[상단메뉴] 알람 발생 리스트업

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#146]
정의
오픈소스디자인사이트에서 사용자의 행동에 따라 알람이 언제 발생하는지를 정리하고 이를 구현한다.

방법
- 알람이 일어날 수 있는 모든 경우를 정리한다.
- 위의 목록으로 현재 어느것이 구현되었는지 안되었는지를 파악한다.
- 구현되지않은 것들은 필요한지 논의 후 구현한다.

부족한 부분있으면 계속 추가바랍니다.

**Comment by wwjdtm** [comment]
1. 메세지 왔을 때 (o)
2. 디자인 멤버로 초대받았을 때 (o)
3. 디자인 멤버에 가입신청이 왔을 때 (o)
4. 디자인 멤버 가입신청이 승인 되었을 때 (o)
5. 디자인 멤버 가입신청이 승인 되지 않았을 때 (o)
6. 그룹 가입신청이 왔을 때 (o)
7. 그룹 가입신청이 승인되었을 때 (o)
8. 그룹 가입신청이 승인되지 않았을 때 (o)
9. 내 디자인에 좋아요가 눌렸을 때 (x)
10. 내 디자인에 댓글이 달렸을 때 (x)

**Comment by opensrcdesign-admin** [comment]
위에서 작성된 목록을 기반으로 추가하면 될 것으로 보임. 일정과 방법에 대해서 남겨주길바람.

**Comment by ggamsang** [comment]
알람이 발생할 시점을 정리한 목록 코맨트입니다.(계속업데이트될예정)
-----
|알람코드 | 알람발생시점 | 구현 | 비고 |
|---|---|---|---|
| | 새로운 메시지 받았을 때 | :ballot_box_with_check: | |
| | 디자인멤버로 초대받았을 때 | :ballot_box_with_check: | |
| | 디자인초대가 거절되었을 때 | :ballot_box_with_check: | 메시지수정필요 "초대에 거절하엿습니다." |
| | 디자인초대에 승인하였을 때 | :ballot_box_with_check: | |
| | 디자인에서 탈퇴되었을 때 |:ballot_box_with_check: | 메시지수정필요 "디자인에서 탈퇴되었습니다." |
| | 디자인가입 신청이 왔을 때 | :ballot_box_with_check: | |
| | 디자인가입 신청이 승인되었을 때 | :ballot_box_with_check: | |
| | 디자인가입 신청이 거절되었을 때 | :ballot_box_with_check: | |
| | 그룹 가입신청이 왔을 때 | :ballot_box_with_check: |언라이브|
| | 그룹 가입신청이 승인되었을 때 | :ballot_box_with_check: |언라이브|
| | 그룹 가입신청이 승인되지 않았을 때 | :ballot_box_with_check: |언라이브|
| | 내 디자인에 좋아요가 눌렸을 때 | | |
| | 내 그룹에 좋아요가 눌렸을 때 | | |
| | 내 디자인에 댓글이 달렸을 때 | | |
| | 내 컨턴츠에 댓글이 달렸을 때 | | |
| | 내 댓글에 답변이 달렸을 때 | | |

*언라이브 - 알람아이콘이 바로 갱신되지 않고 새로고침 해야하는 경우

**Comment by ggamsang** [comment]
제가 종합한 사항은 위와 같습니다. 현시점에서 알람은 11개의 이슈에 대해서 알람을 보내고, 5개의 이슈에 대해서는 보내지 않습니다. 또한 동작하는 11개의 이슈 중 5개는 수정이 필요할 것으로 보입니다.

소요: 3일
완료시점: 4월 8일
처리내용: 새로운 알람 5개 추가, 알람4개 수정

**Comment by ggamsang** [comment]
이슈상태는 "진행중"입니다.

**Comment by ggamsang** [comment]
알람이 추가되어야하는 시점 
- 내 그룹에 좋아요가 눌렸을 때
- 내 디자인에 댓글이 달렸을 때
- 내 컨턴츠에 댓글이 달렸을 때
- 내 댓글에 답변이 달렸을 때

위의 사항에 대한 하위이슈 열고 진행하도록 하겠습니다.

**Comment by ggamsang** [comment]
현재 목록에 있는 사항에 대해서 모두 구현완료하고 머지까지 확인했습니다.
