### ISSUE TITLE
[디자인 등록]카테고리 5개까지 추가가능토록 코드수정

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#15]
우선순위:B, output) {1,2},{3,23},{3,4}...

**Comment by eleutheria80** [comment]
@kimgyuri 원인 분석 후에 원인과 수정 예정일을 명시 해 주세요.

**Comment by kimgyuri** [comment]
카테고리 1개만 설정 가능하도록 되어있습니다. 2월 3일까지 해결하도록 하겠습니다.
