### ISSUE TITLE
[UX] 아이디어 목록

### ISSUE THREAD

**Issue by Jinakimm** [kmu-crc/osd_front#157]
제가 작업하다가 생각나는 아이디어들을 이 곳에 한번에 정리하도록 하겠습니다

**Comment by Jinakimm** [comment]
1. 이용가이드 다시 작성하기
현재 이용가이드는 클릭하면 다시 단계형으로 분리가 되어 있어서, 러닝커브가 너무 길 뿐더러 그 곳에 있는 정보들이 중요한 것들이 아니라 오히려 악효과가 오는 것 같습니다.
단계형이 아닌 하나의 페이지로 이미지와 글을 통해 지면을 구성하고, 거시적인 이용가이드만 작성하고 나머지 세부적인 이용법은 페이지 별로 그때그때 설명하는 것이 좋을 것 같습니다

**Comment by Jinakimm** [comment]
2. 로고도 임시라고 들었는데, 필요하면 추후에라도 바꿀 생각도 있습니다
Open이라는 것이 퍼져나가다, 프레임 밖으로 나가다라는 뜻인데 현 로고는 너무 정사각형 틀에 갇힌 느낌이 들어서 시각적인 임팩트가 약한 것 같습니다. 나중에라도 로고를 바꿔야 한다면 진행하겠습니다.

**Comment by Jinakimm** [comment]
3. 파생 디자인 재정립
파생 디자인이라는 말도 어렵고, 아이콘도 개발 쪽에서 자주 볼 수 있는 픽토그램이라 다양한 분야의 사용자가 직관적으로 알아보기 어려울 것 같습니다. 아이콘은 사이트 구 버전 때 사용하였던 아이콘이 더 나을 것 같고, 명칭은 연결되어있다는 의미를 가졌으면 좋겠습니다

**Comment by Jinakimm** [comment]
4. 친절한 사이트
요즘은 시크하고 아주 멀고 높은 곳에 있을 것 같은 느낌을 주는 사이트보다, 내 친구같고 바로 옆에서 내 이야기를 들어줄 수 있는 평등한 위치의 사이트를 선호합니다. 따라서 모든 사이트의 종결어미가 청자높임법 중 해요체가 되면 좋을 것 같습니다. 느낌표!도 좋은 인상을 줍니다

**Comment by Jinakimm** [comment]
5. 단계형(프로젝트형)에 대한 명확한 설명
제가 처음에 이 사이트를 접속했을 때 제일 혼란스러웠던 것은, 같은 카테고리의 프로젝트를 눌러도 어떤 것은 단계가 나오고, 어떤 것은 그냥 하나의 페이지만 나온다는 것이었습니다. 따라서 그것을 사용자가 선택할 수 있도록 선택지를 주거나, 디자인 카트 아래에 아이콘으로 이것이 단계형인지 아닌지를 보여주는 것도 좋은 방법일 것 같습니다

**Comment by opensrcdesign-admin** [comment]
정리 완료되시면 해당이슈는 닫도록 하겠습니다 :)

**Comment by Jinakimm** [comment]
정리 완료하였습니다! 감사합니다
