### ISSUE TITLE
[맴버검색] 디자인 등록 시 입력된 글자없을때는 맴버검색요청하지 않게 막기

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#158]
디자인을 등록 시 맴버검색 입력창에서 입력된 글자가 없어도 검색이 되는데 이를 막는 이슈입니다.

이슈가 할당되면 파악 후 간략하게 어떤방식으로 처리할 것인지와 일정을 알려주시면 됩니다.

**Comment by doeuncow** [comment]
입력된 글자가 없다는 뜻은 "공백"을 입력하였을 때 검색되는 경우를 뜻하는 건가요?
해당 경우에는 이메일 및 닉네임에 "공백"이 포함된 결과들이 나타나는데 제대로 나타나서 문제되는 부분이 아니라고 생각됩니다.

공백조차도 입력하지 않았을 경우에는 "검색결과가 없습니다."라고 나타납니다!

**Comment by opensrcdesign-admin** [comment]
맴버검색 창에 아무것도 입력되지 않고 검색버튼을 누르게 되면 빈값을 서버에 보내고 서버는 이를 처리하다가 500에러를 발생시킵니다.
서버쪽은 @ggamsang 가 처리할것이고, @doeuncow 께서는 빈값일때는 요청하기전에 체크후 return 하시면 될 것으로 보입니다. :) 답변이 되었길 바라면 이해가 가지않는 부분이 있으시다면 코맨트남겨주시면 감사하겠습니다. :smile:

**Comment by opensrcdesign-admin** [comment]
![Screenshot from 2019-04-04 10-25-42](https://user-images.githubusercontent.com/46555793/55523417-0ccf4600-56c4-11e9-9093-7c17ab2993be.png)

**Comment by doeuncow** [comment]
확인했습니다! 처리 방법 고민 후, 코멘트 남겨놓겠습니다.

**Comment by doeuncow** [comment]
Components > Designs > CreateDesignForm > CreateDesignForm.js 파일을 확인하면, 멤버검색 요청 하는 부분의 위치가 Components > Commons > FormItems > AsyncInput.js 에 있는 것을 확인할 수 있습니다.

해당 부분에서 validate 속성을 추가하거나 입력하는 값을 1개 이상 입력하도록 제한을 두면 해결될 것으로 보입니다. 

04.05 : 해당 부분 validate 속성 추가 가능한지 확인 및 제한하는 방법 확인하기, 테스트 1차
04.08 : 테스트 2차

Due Date : 04. 08

**Comment by doeuncow** [comment]
asyncinput과 input에  minlength >= 1을 입력하고,

검색에서도 제한을 주기 위해, searchlist의 textValue를 asyncinput하는 if 문 조건에
 && (this.state.textValue.length > 1) 를 추가하여 제한할 수 있다.

**Comment by opensrcdesign-admin** [comment]
테스트결과 별다른 문제 발견되지않아 머지하였고, 이에 해당이슈는 닫도록 하겠습니다. 수고하셨습니다. 👍
