### ISSUE TITLE
[통합] 오픈소스사이트 내 모든 문자입력창 리스트업

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#159]
오픈소스사이트 내 모든 문자입력창에 대해서 목록을 만듭니다.
1) 상단메뉴 검색창 (최대100자)
2) ...
*입력 시 제한글자수를 넘기게 될 때 어떻게 처리할지도 정합니다.

~또한 문자열 표시 제한~
~1) 상단메뉴 닉네임(길이 표시제한: 5자)~
~2) ...~

위와 같이 목록을 만들어도 되겠지만, 형식은 이슈 담당자 임의로 만드셔도 됩니다.

이슈가 할당되면 파악 후 간략하게 어떤방식으로 처리할 것인지와 일정을 알려주시면 됩니다.

**Comment by opensrcdesign-admin** [comment]
@kimgyuri 오늘중에 해당이슈를 어떻게 진행해나갈것인지 자신의 생각을 남겨주시면 감사하겠습니다. 편하게 작성하셔도 좋습니다. (메모장만큼 편하게요)

**Comment by kimgyuri** [comment]
블로그형디자인, 단계형디자인, 마이페이지 등등 페이지 별로 나누어서 리스트를 만들 계획입니다. 테스트 때 발견되었던 부분들을 우선적으로 정리하고, 후에 오픈디자인 페이지에서 지속적으로 테스트하고 발견된 부분을 추가할 생각입니다!

**Comment by opensrcdesign-admin** [comment]
그리고 예상일정 잡아보도록 하세요! 🙂

**Comment by kimgyuri** [comment]
다음주 금요일 (4월 12일) 까지 하도록 하겠습니다!

**Comment by opensrcdesign-admin** [comment]
https://docs.google.com/spreadsheets/d/1sWK6Uz8As4R1O9P4dq6bq0HCW9ZDyz989_yI3-42et4/edit?usp=sharing
