### ISSUE TITLE
[비밀번호찾기] 이메일 조회후 없을시 500에러발생

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#160]
조회 후 결과가 없으면 500에러가 발생하는데 예외처리를 해야할 것으로 보임.

**Comment by opensrcdesign-admin** [comment]
이슈 파악하고 난 후에 내용과 일정 남겨주시기 바랍니다.

**Comment by ggamsang** [comment]
이메일주소를 조회 후 결과값이 없으면 500에러를 발생시키게 되어있습니다만
이 경우 서버내부에러라는 500은 적절하지 않습니다.
상태코드를 달리해서 전송하는 것이 방법이겠으나, reject하지 않으면 다음 함수들이 수행되는 문제가 있습니다.
express의 next를 현재와 다르게 사용하는 방법이 있는지 조사해보고 어떻게 구현할 것인지 구체적으로 남기도록 하겠습니다.
예정 완료시점은 **4월10일**입니다.

**Comment by ggamsang** [comment]
아이디를 못찾았을 경우 500에러보다는 상태코드 200으로 데이터 내 에러메시지를 전송하는 방식으로 하였으며,
이와 유사한 이슈들은 위와 같이 진행할 예정입니다.

여기서 보충되어야하는 것이 있다면 Error Handling을 어떻게해야 "callback hell"에 빠지지 않는지에 대한 연구가 필요할 것으로 보입니다.

**Comment by opensrcdesign-admin** [comment]
확인 후 머지하였습니다. 이에 해당이슈는 닫도록 하겠습니다.
