### ISSUE TITLE
[로그인] 디비에 없는 아이디로 로그인 시 500에러발생

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#161]
디비에 없는 아이디로 로그인 시 500에러 발생. #160과 유사한 이슈임.

**Comment by ggamsang** [comment]
#160 과 유사한 이슈인 것을 확인하였습니다.
내일 테스트해보고 바로 리퀘하겠습니다.
완료시점: **4월 9일**

**Comment by opensrcdesign-admin** [comment]
머지하였음, 해당이슈 닫습니다.
