### ISSUE TITLE
[맴버검색] 입력글자없이 검색버튼클릭시 500에러

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#162]
#160과 처리가 동일할 것으로 보임.

**Comment by ggamsang** [comment]
넵, #160, #161 와 유사한 이슈입니다.
완료시점: **4월10일**

**Comment by opensrcdesign-admin** [comment]
@opensrcdesign-admin  계정으로 직접 커밋함. 이에 해당이슈 종료.
