### ISSUE TITLE
[댓글] 디자인 댓글에 빈 댓글 입력되지 않토록!

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#164]
디자인 상세보기에서  디자인댓글을 입력할 때, 빈칸도 입력이 가능하게 되어 있음, 이를 빈칸인 경우에 댓글 등록이 불가능하도록 한다.

**Comment by ggamsang** [comment]
designcomment.js 내 onSubmitCmtForm 함수에서 글자수를 체크합니다.
글자수체크if문조건이 복잡하게 되어있는데 단순하게 할 필요가 있을 것같고, 금방해결할수있는문제입니다.
완료시점:**4월12일**

**Comment by opensrcdesign-admin** [comment]
완료로 인한 종료
