### ISSUE TITLE
[알람] 버그! 알람아이콘에 없어지지않는 숫자가 생기는 경우가 발생

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#167]
알람이 발생하는 경우가 여럿 있다.
 그중 하나가 발생하였다고 했을 때, 해당인원에게 알람이 간다.
해당인원이 그 알람을 열람하지 않은 상태에서 알람발생사항이 취소되는 경우 
해당인원에게는 계속 알람이 보이게되며 없어지지 않는 문제가 발생한다. 이를 파악하고 바로 잡는다.

**Comment by opensrcdesign-admin** [comment]
원인파악 자세히 다시해보고 이슈 진행하시기바랍니다.

**Comment by ggamsang** [comment]
사라지지않는 알람의 숫자는 디자인이나 그룹이 지워졌을때 그리고 확인하지않은 상태라면 사라지지않습니다.

이 문제는 알람을 가져올때 validation해서 목록을 다시 만드는 것으로 해결했습니다.

현재 이슈화되지않은 이슈를 진행중입니다. 이 이슈는 그 이유에 포함됩니다.

15일 회의전까지 완료를 목표로 진행하고있습니다.

완료시점: **5월15일**

**Comment by opensrcdesign-admin** [comment]
완료되어 닫습니다.
