### ISSUE TITLE
[알람] 알람이 누구로부터 왔는지 표시한다.

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#168]
현재 어떤 사항에 대해서 알람이 왔는지 관련문구를 표시하지면 알람에 따라 인원의 닉네임이 필요한 경우가 있고 이를 표시하게 기능을 보완한다.

**Comment by ggamsang** [comment]
#167 에서 코멘트한 것과 같이 이 이슈도 이미 해결하였습니다.
이슈화되지않은 알람이슈 커밋하면 해결되는 이슈입니다.

완료시점: **5월15일**

**Comment by opensrcdesign-admin** [comment]
완료되어 닫습니다.
