### ISSUE TITLE
[마이페이지] 등록한 디자인수, 좋아요 수, 조회수가 상이한 문제

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#169]
디자인카운터 테이블과 현재 사용하고있는 테이블을 확인할 필요가 있을 것으로 보임.
이전의 추천디자인테이블과 혼돈되는 것으로 보임.

**Comment by ggamsang** [comment]
해당데이터들은 user_counter 테이블에서 값을 가져옵니다. 디자인수 좋아요 조회수 모두 올바르게 업데이트되지 않은데서 생긴문제로 각 항목별 업데이트가 잘 이루어지는 확인이 필요할 것 같습니다.
다른방법으론 값을 가져오기전 항목에 대해서 COUNT해서 가져오는 것도 좋은 방법일 것입니다.
완료시점:**4월15일**

**Comment by ggamsang** [comment]
고쳐야할부분: 디자이이너 디테일에서 타 디자이너의 관심디자인을 클릭하면 파생아이콘이 다 뜸. 이건 백엔드의 문제로 보임. 해당요청에 대한 쿼리문을 확인할 필요가 있음.

**Comment by ggamsang** [comment]
update 문을 통해 design_counter의 값을 갱신하여 값이 다른 경우가 없도록 구현하였습니다.
곧, 리퀘하겠습니다.
표시형식도 조금 바뀐부분이 있어 프론트엔드도 리퀘하겠습니다.

**Comment by opensrcdesign-admin** [comment]
리뷰/머지 완료되어 해당이슈 닫습니다.
