### ISSUE TITLE
[디자인 등록]카테고리 - 버튼 누르면 삭제

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#17]
우선순위:B, 1개가 남을 때까지 제거할수 있게 기능구현

**Comment by kimgyuri** [comment]
x 버튼 클릭시 카테고리 삭제. (이번주 안으로)

**Comment by eleutheria80** [comment]
@kimgyuri 단순히 '이번주 안으로' 라고 적지 마시고 01/31 혹은 02/01일과 같이 명확한 날짜를 명시 해 주세요.

**Comment by kimgyuri** [comment]
2월 3일까지 끝내도록 하겠습니다.

**Comment by eleutheria80** [comment]
@kimgyuri 앞으로 특별히 급한 사항이 아니면 휴일은 계산하지 마시고 워킹데이 기준으로 작성 해 주세요.
