### ISSUE TITLE
[디자이너 상세보기] 등록한 디자인수, 좋아요, 조회수 값이 상이한 문제

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#170]
#169 와 동일한 문제로 보이며 처리는 같게하면 될 것으로 보임.

**Comment by ggamsang** [comment]
SET SQL_SAFE_UPDATES = 0;
UPDATE opendesign.user_counter SET total_view = 0;

UPDATE opendesign.user_counter T, (
SELECT A.user_id, SUM(B.view_count) AS 'view_count'#A.uid, A.user_id, B.view_count
FROM opendesign.design A 
LEFT JOIN design_counter B ON B.design_id = A.uid
WHERE user_id IN (SELECT uid FROM opendesign.user)
GROUP BY A.user_id) TT
SET T.total_view = TT.view_count
WHERE T.user_id = TT.user_id;
SELECT * FROM opendesign.user_counter;
SET SQL_SAFE_UPDATES = 1;
로 해결함.
