### ISSUE TITLE
[로그인] 로그인 시 무조건 메인으로 이동 ... 로그인 전 페이지로 이동토록

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#172]
현재 오픈소스사이트에서 로그인페이지를 통해 로그인하면 메인페이지로 이동하게된다.
이를 로그인 전 페이지로 이동하도록 **수정하되, 전 페이지로 이동해서 페이지가 오작동하지않도록 한다.**

**Comment by doeuncow** [comment]
할당받은것 확인했습니다. 
04.09 중으로 해당 코드 확인하고, 마감기한 적도록 하겠습니다! :)

**Comment by opensrcdesign-admin** [comment]
그리고 진행하시면서
제가 history.go(1)하면 되는 거 확인했는데, 이게 위에서 말한 오작동을 일으킬수있는지 확인해주시면 감사하겠습니다.

**Comment by opensrcdesign-admin** [comment]
this.props.history.go(-1)

**Comment by opensrcdesign-admin** [comment]
현재로써는 로그아웃 시 메인페이지로 가는 것 좋을 듯 합니다. 로그아웃하는 페이지가 유저정보 및 권한이 있어야만 정상적으로 페이지가 뜨는 경우엔 페이지에서 이를 체크하지않으면 에러가 날 수 있어서 그부분을 완벽하게 구현하거나 한것을 확인 한 후에 해도 좋을것같습니다.

**Comment by doeuncow** [comment]
아하, 네네! 확인했습니다:) 그러면 "로그인 시"에만 적용하여 테스트 진행 후 pull request하겠습니다!

**Comment by doeuncow** [comment]
**<테스트 항목>**
로그인 시, (이전 페이지) -> (로그인 후 페이지 위치)

- [ ] 메인 페이지 -> 메인 페이지
- [ ] 디자인 목록 페이지 -> 디자인 목록 페이지
- [ ] 그룹 목록 페이지 -> 그룹 목록 페이지
- [ ] 디자이너 페이지 -> 디자이너 페이지
- [ ] 검색 페이지 -> 검색 페이지 
- [ ] 디자인 단계형(프로젝트) 페이지 -> 디자인 단계형(프로젝트) 페이지
- [ ] 디자인 블로그형 페이지 -> 디자인 블로그형 페이지
- [ ] 회원가입 페이지 -> 회원가입 페이지
- [ ] 사이트 소개 페이지 -> 사이트 소개 페이지
- [ ] 이용약관 페이지 -> 이용약관 페이지
- [ ] 개인정보보호정책 페이지 -> 개인정보보호정책 페이지

**Comment by doeuncow** [comment]
위 항목 테스트 진행하였으며, 로그인 후 이전 페이지로 잘 이동하는 것을 확인하였습니다. :)
pull request하겠습니다~!

**Comment by opensrcdesign-admin** [comment]
테스트까지 완벽히 잘해주셨습니다. :)
확인후 머지하였습니다. 해당이슈는 닫도록하겠습니다.
