### ISSUE TITLE
[로그인] 로그인된 상태에서 새로고침을 여러 번하면 로그아웃되는 경우

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#173]
새로고침을 연속으로 누르면 로그아웃이 되는 경우가 발생한다.
이는 로그인 정보를 하위컴포넌트에서 가지고 있어서 발생하는 것으로 파악되었고,
이를 해결하기 위해서는 로그인 정보는 최상의 컴포넌트 (App.js) 에서 유지토록 코드를 수정한다.

**Comment by ggamsang** [comment]
최상의 컴포넌트로 올렸음에도 문제가 계속 발생되었음
그리하여, 다시 파악해보니 토큰을 지워버리는 코드가 있는데, 불필요한 시점에서 수행됨에 따라 커맨트아웃시킴
