### ISSUE TITLE
[비밀번호찾기] 찾기버튼 클릭 후 대기하는 동안 로딩레이어를 표시

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#174]
사용자가 비밀번호를 찾기위해 자신의 이메일주소를 넣고 찾기 버튼을 눌렀을 때, 약간의 시간이 지난 후 결과 메시지가 뜨는데, 요청후 처리결과를 받을 때 까지 로더를 화면에 표시하도록 한다.

**Comment by doeuncow** [comment]
할당받은 것 확인했습니다! 

적용하는 파일 및 코드상에서 확인 후, 오늘 내로 Due Date 업로드 하도록 하겠습니다. 
(중간고사 기간 고려하여 일정을 여유롭게 잡도록 하겠습니다.)

**Comment by opensrcdesign-admin** [comment]
천천히 하지만 분명하게!
넵, 무리해서 진행하지마시고 꼼꼼히 확인하시면서  해주시면 감사하겠습니다. 
진행하시는데 모달이 필요하신 경우엔 현재 2가지 패지키이용하고있으니,
 그 중에 하나 선택하셔도 좋을 것 같습니다. (semantic-ui-react에서의 modal, react-awesome-modal)
레이어디자인에 대해서는 신경쓰시지 않아도 좋습니다. 한 디자인으로 통일될 것입니다.
:)

**Comment by doeuncow** [comment]
현재 상황을 확인하기 위해 테스트를 진행하였습니다.

> 비밀번호 찾기 버튼 클릭 후, 이메일 입력하면 약 3~4초 가량 지난 후에, 이메일 전송 완료 Alert창이 나타난다.

진행 중, 추가적인 문제를 발견하였습니다.
> 아래 이미지와 같이 비밀번호 변경한 값이 나타나지 않습니다. 
![image](https://user-images.githubusercontent.com/30363239/56014618-f7e05b80-5d30-11e9-86d6-95adcccdefb2.png)

**Comment by doeuncow** [comment]
확인할 파일

1. components/Registration/SignInForm/SignInForm.js
`<Link to="/resetPw"><FindPwBtn type="button">비밀번호 찾기</FindPwBtn></Link>`
2. pages/ResetPwPage/ResetPwPage.js
3. containers/Registration/ResetPwContainer/ResetPwContainer.js

modal 이용 말고, 
semantic-ui-react 의 loader를 사용하는 방법을 고려 중입니다.
> components/Commons/Loading/Loading.js 


**적용 아이디어**
1) 이미 만들어진 loader를 적용하는 방법
2) 이미 만들어진 loader가 적절하지 않아 보인다면, 새로 semantic-ui-react loader적용. loader 나타난 후, Alert창이 나타나는 순서로?
3) Components/Registration/SignUpModal.js 참조하여 새로운 Modal 생성하여 연결.

Due Date : 04.19 까지 1번과 2번 방법 적용하는 방안 고려
Due Date : 04.30 위 방안에서 해결점이 보이지 않는다면, 3번 방안 진행. (22일~26일 시험기간이기에 많은 시간 쏟을 수 없을 것으로 예상되어 기간을 길게 잡았습니다.)

**Comment by opensrcdesign-admin** [comment]
값이 없는 문제는 바로 처리하도록 하겠습니다. 알려주셔서 감사합니다.

**Comment by opensrcdesign-admin** [comment]
시험일정에 차질없도록 진행해주시면 감사하겠습니다. (연기하세요)

**Comment by doeuncow** [comment]
> Due Date : 04.19 : 1번과 2번 방법 적용하는 방안 고려
Due Date : 04.30 : 위 방안에서 해결점이 보이지 않는다면, 3번 방안 진행. (22일~26일 시험기간이기에 많은 시간 쏟을 수 없을 것으로 예상되어 기간을 길게 잡았습니다.)

로 예정했던 일정을 중간고사 시험공부와 자격증 시험으로 인해 연기하도록 하겠습니다. 
(이슈 진행사항에 대한 코멘트 늦은 점 죄송합니다.)

> Due Date : 05.01 (1번, 2번 방안 적용 및 검토)
Due Date : 05.07 (위 방안에서 해결점이 보이지 않는다면, 3번 방안 진행)

**Comment by doeuncow** [comment]
1번 방법(이미 만들어진 loader를 적용하는 방법)을 진행중입니다.
아직 뚜렷하게 확인되지 않아 자정까지 마저 진행하고, 그 후에 다른 방안으로 교체여부에 대해 코멘트 남기도록 하겠습니다.

**Comment by doeuncow** [comment]
로컬 테스트에서 확인 중, 비밀번호 이메일 요청을 했을 시 다음 이미지와 같은 문제가 발생했습니다.
![ERROR](https://user-images.githubusercontent.com/30363239/57089455-6f594780-6d3f-11e9-80da-9471f6d395b6.png)

**Comment by doeuncow** [comment]
현재 서비스중인 페이지에서는 위 문제가 발생하지 않았습니다.
로컬환경에서 무언가 문제가 있는 듯 한데 정확히 파악은 아직 못했습니다.

일단, 위 문제 고려하여 3번 방법(Components/Registration/SignUpModal.js 참조하여 새로운 Modal 생성하여 연결.) 적용해보도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
백엔드 .env 파일 내 지메일 아이디 비밀번호가 맞는지 확인해보시고 알려주세요.

모달관련 state를 하나 만들고, 요청 시 이 state를 변경하도록합니다. 이때, 모달이 실행되는 조건으로 이 state를 주면 될 것입니다. SignUpModal도 이와 같이 구현되어 있습니다. :)

**Comment by doeuncow** [comment]
중간고사 대체 프로젝트 과제로 인해 이슈해결이 지연되었습니다.

1일 연장하여 해결하도록 하겠습니다. 죄송합니다.
Due Date : 05.09

**Comment by doeuncow** [comment]
ResetPwModal 파일을 생성하여, 기존 회원가입 모달 창과 비슷하게 구현하였습니다.

몇 초후 Modal이 종료되게끔이 아니라, Alert창이 나타날때까지만 Modal이 나타나게 하는 작업을 진행중입니다.

**Comment by doeuncow** [comment]
ResetPw.js로부터 alert창이 실행되는 조건내에 state를 주어 ResetPwModal.js로 넘겨 state가 바뀌었을 때, Modal이 종료되게끔 하려고 하는데, 
`if (nextProps.state === "SUCCESS"{ ~~~ }` 이 코드 내부에 `this.setState({timeover: true})` 의 setState함수를 적용하려 했으나 작동되지 않는다.

상태를 전달하여 모달을 종료시킬 수 있는 다른 방법을 찾아보겠습니다.

**Comment by opensrcdesign-admin** [comment]
제가 테스트한 방식에 대해서 한 번 시도해주시면 감사하겠습니다.
(시도해보신방법과 다르지 않다면 알려주세요.)

class ResetPwForm extends Component{
    state = {loading: false}
      shouldComponentUpdate(nextProps){
    if(JSON.stringify(this.props.status) !== JSON.stringify(nextProps.status)){
      if(nextProps.status === "SUCCESS"){
        this.setState({loading:false})
        alert(nextProps.message)
      } else if (nextProps.status === "FAILURE") {
        alert(nextProps.message)
      }
    }
    return true
  }
...(중략) ...
render() {
    return (
      <Bg>
        {this.state.loading?"처리중":null}
        <ResetFormCard>
          <h2>비밀번호 찾기</h2>
...(생략) ...

와 같이 해보시는 것도 좋을 것 같습니다.
여기서 처리중 이라는 부분에 모달컴포넌트를 입력하시면 될 것으로보입니다.

**Comment by doeuncow** [comment]
저도 같은 방식으로 구현했는데 

`if(JSON.stringify(this.props.status) !== JSON.stringify(nextProps.status)){
if(nextProps.status === "SUCCESS"){
this.setState({loading:false})
alert(nextProps.message)
} else if (nextProps.status === "FAILURE") {
alert(nextProps.message)
}`

이 부분의 this.setState({loading:false})로 하여도, 상태가 변하지 않습니다. 혹시나 하여 FAILURE일 때에도 테스트하였으나 역시나 상태가 변하지 않습니다ㅠㅠㅠㅠㅠㅠ console로 확인하여 보아도 false상태로 바뀌는데에 실패합니다....

**Comment by opensrcdesign-admin** [comment]
혹시 코드 전체를 제가 볼 수 있을까요?

**Comment by doeuncow** [comment]
**ResetPwModal.js**

import React, { Component } from 'react';
import Modal from 'react-awesome-modal';
import { relative } from 'path';

export default class ResetPwModal extends Component {
  constructor(props) {
    super(props);
    this.state = {
      visible : true
    }
  }

  // componentDidMount() {
  //   setTimeout(
  //     ()=>{
  //       this.props.history.go(-1);
  //       this.setState({visible: false});
  //     }, 4000);
  // }

  // closeModal() {
  //   this.setState({visible : false});
  // }

  render() {
    const ModalStyle = {
      textAlign: 'center',
      margin: 100
    }

    return(
      <section>
        <Modal
        onLoad
        visible={this.state.visible}
        width="400"
        height="300"
        effect="fadeInDown"
        >
        <div style={ModalStyle}>
          <h1>비밀번호를<br></br> 전송중입니다.</h1>
          <p>로그인 페이지로 이동합니다.</p>
        </div>
        </Modal>
      </section>
    );
  }
}

**Comment by doeuncow** [comment]
음 그러면 일단 커밋해두도록 하겠습니다!

**Comment by opensrcdesign-admin** [comment]
https://github.com/doeuncow/new_osd_front/commit/36d355e307bb85f373995a90c2e49ad9e4800ffa
에서와 같이 진행하시면 되며, 로그인페이지로 이동하는 코드를 추가하시면 될 것으로 보입니다. :)

**Comment by doeuncow** [comment]
위와 같이 진행하였는데, Alert 창이 나타나면서 Modal이 종료되게끔 구현되지는 않았습니다. 하지만 Alert창 클릭 시, 모달 창이 종료되기 때문에 원하는 만큼 구현은 안되었지만 충분히 기능은 수행한다 생각하여 이대로 커밋하도록 하겠습니다.

로그인 페이지로 이동하게끔 코드를 추가하였습니다.
풀 리퀘스트 요청해두도록 하겠습니다.
