### ISSUE TITLE
[맴버검색] 메시지 보내기 위해 회원검색 할 때, 글자수 1자입력부터 검색가능케

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#175]
현재 메시지를 보낼 회원을 검색 할 때 2자이상을 넣어야 회원이 검색된다. 이를 한 자만 입력해도 검색이 되도록 수정한다.

**Comment by doeuncow** [comment]
할당받은것 확인했습니다. 

Validate 값을 이전에 2로 두었는데 1로 두면 해결될 것으로 보입니다.
Due Date : 04.10

**Comment by opensrcdesign-admin** [comment]
머지하였습니다. 해당이슈는 종료하겠습니다. 수고하셨습니다! :1st_place_medal: :1st_place_medal: :1st_place_medal:
