### ISSUE TITLE
[상단메뉴] 닉네임 표시 길이제한 

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#178]
닉네임의 길이가 길면 상단메뉴 우측에 닉네임표시가 여러줄에 걸쳐서 표시되는데
이를 너비에 맞게 초과하면 "..." 으로 표시하도록 한다.

**Comment by opensrcdesign-admin** [comment]
아!그리고, 표시 길이제한 이슈하시면서 리스트작성해주시면 감사하겠습니다. :)

**Comment by kimgyuri** [comment]
4월 11일까지 코드 확인 후 기한 남기도록 하겠습니다!

**Comment by opensrcdesign-admin** [comment]
기한 남겨주시거나 수행하는데 어려움이 있으시면 알려주세요~ 기술적인것인지 일정문제인지. :)

**Comment by kimgyuri** [comment]
4월 19일까지 완료하도록 하겠습니다~

**Comment by kimgyuri** [comment]
현재 header 파일에 있는 userinterface 부분에서 구현중입니다! 다만 시험기간이랑 과제랑 겹쳐서 기한안에 해결하지 못했습니다. 혹시 해당 이슈 26일까지 가능할까요? 시험 끝나는대로 최대한 빨리 구현하도록 하겠습니다!

우선 닉네임이 최대 6자까지 표현되고, 6자 이후로는 4자+"..." 정도로 표현하려고 하는 중입니다.
this.props.userInfo.nickName.length < 6 ? porps.userInfo.nickName : porps.userInfo.nickName.slice(0,3) + "..."

이런 느낌이로 구현하고있습니다만... 안되면 다른 형태로 바꿔서 다시 구현해보겠습니당ㅠㅠ

**Comment by opensrcdesign-admin** [comment]
네, 시험준비 잘 하시고 시험마치시면 바로 하시면 될 것 같습니다. :)

**Comment by kimgyuri** [comment]
닉네임 표시 길이 제한 완료했습니다.
3자까지 나오게 하고 그 이후로는 "..."으로 표시 되도록 구현했습니다.

파일 위치 : /home/gyurl/opendesign/myfront/src/components/Commons/Header/Header.js

**Comment by opensrcdesign-admin** [comment]
머지하였습니다. 이에 본 이슈는 크로즈합니다.
