### ISSUE TITLE
[디자인 등록]멤버초대 - 자동수락 기능

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#18]
우선순위:B, 현재 확인 요청 있음, 자동수락하게 변경

**Comment by kimgyuri** [comment]
자동 수락 기능보단 확인 요청 기능이 필요함

**Comment by opensrcdesign-admin** [comment]
2019년 1월 28일 회의내용에 따라 해당 기능은 유지합니다. 이에 따라 본 이슈는 닫습니다.
