### ISSUE TITLE
[닉네임]  닉네임 특수문자 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#180]
회원가입 및 회원정보수정 시 닉네임에 띄어쓰기 제한 허용하는 
특수문자를 제외한 모든 문자를 허용하지않는 것과 같은 제한사항을 정하고 이를 적용한다.

예)
닉네임 제한사항
- 1자부터 20자까지
- 한글/영문/숫자
- 띄어쓰기 제한
- "_", "!", "~" 이에 해당하는 특수문자만 허용
...
위와같이 정하고 적용한다.

**Comment by ggamsang** [comment]
**적용범위**
- 회원가입 닉네임
- 회원정보수정 닉네임
적용내용
- 20자 제한
- 한글/영문/숫자/특수문자("_","!","~" )
- 띄어쓰기제한

-> onBlur될 때 validation함.

**Comment by opensrcdesign-admin** [comment]
merged, will be close right now
