### ISSUE TITLE
[메시지] 공백메시지 전송되지 않도록

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#183]
공백메시지가 전송되지 않게 길이를 체크하거나 trim연산을 통해 빈칸으로만 이뤄진 문자열을 전송요청할 경우 return하여 요청을 하지 못하도록 한다.

**Comment by opensrcdesign-admin** [comment]
새롭게 이슈할당되었으니 확인해주시면 감사하겠습니다. :)

**Comment by kimgyuri** [comment]
5월 8일까지 완료하도록 하겠습니다~

**Comment by opensrcdesign-admin** [comment]
코드확인하시고, 어떻게 진행하실지 결정되면 알려주세요.

**Comment by kimgyuri** [comment]
넵 오늘 안으로 확인하고 답변 드리겠습니다~!

**Comment by kimgyuri** [comment]
![Screenshot from 2019-05-04 05-51-23](https://user-images.githubusercontent.com/29365057/57164962-b70bcc00-6e30-11e9-8050-63e410ffd6d6.png)

이번에도 이런 형태로 짜려고 하는데 괜찮은가요..?

**Comment by opensrcdesign-admin** [comment]
이런형태가 정확히 어떤 것인지 좀 더 구체적으로 적어주시면 감사하겠습니다.
str 의 경우 빈칸 한개가 아닌 두 개 그 이상인 경우("  ") 에 대해서는 동작하지 않을것으로 보입니다. trim연산이 뭔지 알아보시고 벅용해보시는것도 좋은 방법입니다.

**Comment by opensrcdesign-admin** [comment]
다른방법으로는 함수를 추가하지 않고 하는 방법입니다.
onSubmitForm 함수 내 리퀘스트함수를 수행하기 전에 if문으로 빈 칸으로만 이루어졌는지 체크하여 결과에 따라 return 해도 됩니다.

**Comment by kimgyuri** [comment]
![Screenshot from 2019-05-07 15-28-51](https://user-images.githubusercontent.com/29365057/57276570-0118da00-70dd-11e9-8076-ced7e42a98f0.png)
계속 수정해보고 있는데 홈페이지에 왜인지 적용이 안되네요ㅠㅠ
제 코드가 잘못된건가 싶어서 다른 코드 지워보고 저장시켜 봤는데 똑같이 홈페이지에 적용이 안됐습니다..

코드 잘못된 부분이 있나요? 말씀해주시면 바로 수정하겟겠습니다!!

**Comment by opensrcdesign-admin** [comment]
답변드리겠습니다.
화면상 23줄을 보시면,
사용자로부터 입력받은 데이터를 data라고 했을 때 data가 null일때와 값이 없을 때는 다릅니다.
data === null이라는 말은 객체자체가 없다는 것을 의미하지만, 우리는 ValidateForm내 FormField로부터 객체를 받아온 상태입니다. data가 어떤 구조로 되어 있는지 확인하시고, 입력받은 문자열은 data내 어디에 저장하는지(data.???) 파악하시면 될 것 같습니다. 만약 ???일경우 23줄의 코드는 
if(data.??? === "") 혹은 if(data.???.trim() === "") 혹은 if(data.???.length === 0) 와 같이 조건문을 변경하시면 됩니다.

**Comment by kimgyuri** [comment]
테스트 확인이 불가능해서 계속 질문하는 점 죄송합니다..

if (data.message.legnth === 0) {
      alert("메시지 내용을 입력해주세요.");
      return;
    }

로 코드 짰을 때 되는지 확인 가능할까요?

**Comment by opensrcdesign-admin** [comment]
안됩니다. 다시확인해보세요~

**Comment by kimgyuri** [comment]
해당 이슈 완료하였습니다! 확인 부탁드립니다~

파일 경로 : /home/gyurl/opendesign/myfront/src/components/Messages/MessageList/MessageList.js
275 ~ 277번째줄
if (FormData.length === 0) {
      alert("메시지 내용을 입력해주세요.");
      return;
    }

**Comment by opensrcdesign-admin** [comment]
#217 에서와같이 메시지가 있는 경우에도 메시지를 전송하지 않고 있습니다. 다시한번확인해주시면 감사하겠습니다. :)

**Comment by opensrcdesign-admin** [comment]
이번주중으로 반드시 완료합시다! : )

**Comment by opensrcdesign-admin** [comment]
merged and closed
