### ISSUE TITLE
[개인정보수정] 비밀번호 변경 시 비밀번호규칙 체크하지않음.

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#184]
개인정보수정 비밀번호 변경 시 비밀번호규칙 체크하지않고있으나
회원가입때처럼 비밀번호규칙 2가지를 체크하도록 한다.

**Comment by doeuncow** [comment]
이슈 할당 확인하였습니다. 오늘 중으로 해결방법 확인하여 정확한 Due Date 다시 남기도록 하겠습니다.

**Comment by doeuncow** [comment]
#52 참조하여 비밀번호 규칙이 적용되는지 확인하고, #53 를 참조하여 비밀번호일치 여부를 확인하면 될 듯 합니다.

Due Date : 05.24

**Comment by doeuncow** [comment]
Test 항목
**"비밀번호는 6자~15자 이내로 영문, 숫자, 특수문자를 모두 조합하여 작성해 주십시오"를 만족해야한다.**

- [ ] 숫자만 6자~15자 이내로 입력
- [ ] 영문만 6자~15자 이내로 입력
- [ ] 특수문자만 6자~15자 이내로 입력
- [ ] 숫자, 영문으로 6자~15자 이내로 입력
- [ ] 숫자, 특수문자로 6자~15자 이내로 입력
- [ ] 영문, 특수문자로 6자~15자 이내로 입력
- [ ] 숫자, 영문, 특수문자를 모두 조합하여 6자~15자 이내로 입력
- [ ] 비밀번호 확인(일치여부) 모든 테스트에서 적용되는가?

**Comment by doeuncow** [comment]
위 테스트를 진행하던 중, 문제점을 발견했습니다.

비밀번호 입력을 할 시에,
1. 숫자 - 영문 - 특수문자 순서
2. 특수문자 - 영문 - 숫자 순서
등 영문이 우선이 되지 않는 비밀번호를 입력할 시에 Alert창이 나타납니다.

정규표현식으로 나타낸 아래 변수에서 문제점이 있는 것으로 파악하여 
`var reg_pw = /^.(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[~!@#$%^&*<>?]).*$/;`

아래 링크를 참조하여 수정하도록 하겠습니다.
[정규표현식](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/%EC%A0%95%EA%B7%9C%EC%8B%9D)

**Comment by doeuncow** [comment]
^와 $로 인해 제약이 있던 것으로 파악하여,
`var reg_pw = /(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[~!@#$%^&*<>?])/;`와 같이 변경하였으며, 
위 테스트항목 동일하게 테스트 진행했을 때, 무리없이 테스트되었음을 확인하였습니다.

커밋 및 풀리퀘스트 하도록 하겠습니다.

**Comment by doeuncow** [comment]
+ #52 에 해당하는 SignUpModal.js도 동시에 수정하도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
확인하였고, 머지하였습니다. 사이트에는 오늘중에 적용될 예정입니다. 수고하셨습니다!
완료되어 해당이슈를 크로즈합니다.
