### ISSUE TITLE
[하위이슈][알람] 디자인초대가 거절되었을때, 디자인에서 탈퇴되었을때의 메시지변경

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#185]
알람이 발생할 시점을 정리한 목록 코맨트입니다.(계속업데이트될예정)
-----
|알람코드 | 알람발생시점 | 구현 | 비고 |
|---|---|---|---|
| | 디자인초대가 거절되었을 때 | :ballot_box_with_check: | 메시지수정필요 "초대를 거절하였습니다." |
| | 디자인에서 탈퇴되었을 때 |:ballot_box_with_check: | 메시지수정필요 "디자인에서 탈퇴되었습니다." |

**Comment by opensrcdesign-admin** [comment]
머지하였습니다.
