### ISSUE TITLE
[하위이슈][알람] 언라이브 항목들 처리

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#188]
|알람코드 | 알람발생시점 | 구현 | 비고 |
|---|---|---|---|
| | 그룹 가입신청이 왔을 때 | :ballot_box_with_check: |~언라이브~|
| | 그룹 가입신청이 승인되었을 때 | :ballot_box_with_check: |~언라이브~|
| | 그룹 가입신청이 승인되지 않았을 때 | :ballot_box_with_check: |~언라이브~|
| | 내 디자인에 좋아요가 눌렸을 때 | :ballot_box_with_check: |~언라이브~|

목록 중 언라이브한 항목만 빼온 모습이다.  해당이슈에서는 알람발생시 바로 알람버튼이 활성화 되도록 코드를 수정한다.

**Comment by ggamsang** [comment]
await ... then 을 이용하지 않고 sendAlarm을 호출하여 즉 비동기적으로 처리하여 언라이브한 상황이 발생하는 것을 보입니다. 테스트해본 결과 await .. then으로 호출할때 라이브로 알람이 활성화되는 것을 확인했습니다.
이에 목록에 있는 다른 항목들도 같게 구현한 후 리퀘하겠습니다.
소요일은 1일로 오늘중에 리퀘하겠습니다. 백엔드코드 수정이 필요합니다. 라벨추가 요청합니다. 감사합니다.

**Comment by opensrcdesign-admin** [comment]
해당이슈는 완료되었으므로 닫습니다.
