### ISSUE TITLE
[하위이슈][알람] 새로운 알람 추가

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#189]
해당이슈는 아직 구현되지 않은 알람시점을 추가합니다.
-   내 그룹에 좋아요가 눌렸을 때
-   내 디자인에 댓글이 달렸을 때
-   내 컨턴츠에 댓글이 달렸을 때
-   내 댓글에 답변이 달렸을 때

**Comment by ggamsang** [comment]
백엔드에서 각 명령들이 실행될 때 알람을 추가및전송하는 함수를 호출하면됩니다.
프론트엔드는 받은 알람의 문구를 추가하고, 링크를 걸어주는 코드를 추가하면 됩니다.
오늘 중에 해결될 것 같습니다.

**Comment by ggamsang** [comment]
진행하는중에 발견사항
블로그형 댓글은 프로젝트형으로 변경하면 지워짐.이거 맞는건지 확인이 필요함.
현재 대댓글에 대한 알람만 추가하면됨그리고.

**Comment by opensrcdesign-admin** [comment]
머지하였습니다. 이슈 닫습니다.
