### ISSUE TITLE
[디자인 등록/맴버관리]멤버초대 - 자동검색 기능

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#19]
우선순위:B, 문자입력마다 자동으로 검색하는 기능

**Comment by doeuncow** [comment]
두 글자 이상부터 검색 가능하게끔. 엔터치기 전에 검색될 수 있게.

**Comment by doeuncow** [comment]
관련 기능을 검색하는 중인데 브라우저에 입력한 기록을 기억하는 자동완성 기능만 검색되어 조금 더 시간이 필요할 듯 하다. 
예상 Due Date는 02.19이다.

**Comment by doeuncow** [comment]
[Related Info](https://www.dev-diary.com/archives/4141)

**Comment by ggamsang** [comment]
MessageList.js 참고하시면 좋을거같아요~
/src/modules/Validates/Validates.js에서 "> 2"부분을 ">=2"로 고치셔야할것같고요.확인해주세욤~

**Comment by doeuncow** [comment]
헉 감사합니당.!!! 확인하고 수정해보겠습니다

**Comment by doeuncow** [comment]
MessageList.js 확인 중으로 Due Date 를 좀 더 늦추도록 하겠습니다.

Due Date : 02.22

**Comment by doeuncow** [comment]
validate : 2자 이상인 부분은 해결.
messagelist.js 참조하여 코드 수정 중

**Comment by doeuncow** [comment]
Validate.js 2자 이상인 부분은 해결. 
"> 2"부분을 ">=2"로 고침.

MessageList.js와는 다르게 AsyncInput.js 를 이용하여 멤버검색을 진행한다.

MessageList.js 에서는 SearchMemberRequest 를 요청하여 멤버리스트를 불러오는데,
AsyncInput.js 에서는 비동기방식으로 불러오는 듯함.

MessageList.js처럼 멤버검색을 하기 위해 파일 교체 중인데 요청을 보내고 다시 받는 과정에서 에러가 발생하여 수정하는 중이다.

**Comment by doeuncow** [comment]
방법 2.

엔터치기 전에 검색될 수 있게.
-->
`    if (e && e.key === "Enter") {
      this.SearchList();
    }`
이 부분 코드 때문인데 

`e.key === "Enter"` 를 없애면 문자 입력 하나마다 검색은 되지만, 입력창에서도 하나씩만 입력이 가능하게끔 되어 이 부분을 수정하려고 함.

**Comment by doeuncow** [comment]
두 가지 방법을 시도 중인데 원활히 되지 않아 (이미 마감기한을 넘겼지만) 조금 더 기한을 늘려야할 듯하다.

Due Date: 02.28

**Comment by doeuncow** [comment]
방법 1.
MessageList.js처럼 멤버검색을 하기 위해 파일 교체 중인데 요청을 보내고 다시 받는 과정에서 에러가 발생하여 수정하는 중이다.
:: MessageList.js에서 사용한 함수 및 state를 이용하여 똑같이 적용 중인데 (
` <FormInput type="text" name="search" placeholder="찾고자 하는 회원의 닉네임을 입력해 주세요." validates={["MinLength2"]} getValue={this.getValue}/>` )
getValue를 가져오는 과정에서의 오류는 해결했으나, 문자입력마다 검색하는 것 및 멤버리스트를 불러오는 과정에서의 오류가 또 발생되었다. 

방법 2.

엔터치기 전에 검색될 수 있게.
-->
` if (e && e.key === "Enter") { this.SearchList(); }`
이 부분 코드 때문인데

`e.key === "Enter"` 를 없애면 문자 입력 하나마다 검색은 되지만, 입력창에서도 하나씩만 입력이 가능하게끔 되어 이 부분을 수정하려고 함. 

:: 일단 `e.key === "Enter"` 를 없애고 async방식을 sync하게 바꾸는 방법을 시도중이다.

현재 커밋한 내용은 `e.key === "Enter"`를 삭제하여 문자 입력마다 검색을 가능하게 하였다.

---------------------------------------
방법 1을 적용하거나 방법 2를 좀 더 개선하는데 Due Date : 03.04로 일정을 조정.

**Comment by doeuncow** [comment]
위 내용은 일단 풀 리퀘스트는 하지 않고, 추가적인 문제가 해결되었을 때 진행하도록 하겠습니다.

**Comment by doeuncow** [comment]
방법2로 개선이 될 것 같지 않아 방법 1을 계속하여 적용 중인데 위에서 말한 오류
> :: MessageList.js에서 사용한 함수 및 state를 이용하여 똑같이 적용 중인데 (
<FormInput type="text" name="search" placeholder="찾고자 하는 회원의 닉네임을 입력해 주세요." validates={["MinLength2"]} getValue={this.getValue}/> )
getValue를 가져오는 과정에서의 오류는 해결했으나, 문자입력마다 검색하는 것 및 멤버리스트를 불러오는 과정에서의 오류가 또 발생되었다.

가 해결되지 않고 있습니다.
내일 조금 더 살펴본 후, 여전히 해결이 안될 시, 도움을 요청하도록 하겠습니다.

**Comment by doeuncow** [comment]
혼자서 해결하기 어려워 김정혁 연구원님께 도움을 요청하여 진행하도록 하겠습니다. 

Due Date도 변경하도록 하겠습니다. 

Due Date : 03.12

**Comment by doeuncow** [comment]
MessageList.js의 `<FormInput>` 참조하여 코드를 변경하였습니다.

멤버 초대 시, 입력마다 해당 입력을 가진 사용자를 확인할 수 있습니다.

> 문제 : 디자인 등록 시, `this.state.member.value`에서의 value 속성을 인식하지 못한다. 현재 이 부분 오류 살펴보고 수정 중입니다.

**Comment by doeuncow** [comment]
위에서 이야기 한, 
> 디자인 등록 시, this.state.member.value에서의 value 속성을 인식하지 못한다. 

문제 해결하였습니다.

**Comment by doeuncow** [comment]
풀 리퀘스트 한 내용 확인 후, 회의에서 OK받으면, 이슈 닫아도 될 듯 합니다~!

**Comment by doeuncow** [comment]
검색에는 무리가 없으나, 디자인 등록(제출) 시 발생되는 에러가 있어 확인 예정입니다.
