### ISSUE TITLE
[디자인 등록] 디자이너가 아닐때도 디자인등록가능

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#194]
디자이너가 아님에도 디자인 등록이 되는 것을 확인
이를 수정하기 위해서는 백엔드로부터 user_detail테이블의 데이터를 요청/조회/전송하는 함수를 구현한다.

디자인등록버튼은 디자이너일때는 빨간색, 아닐때는 회색으로 한다.

**Comment by opensrcdesign-admin** [comment]
크로즈했습니다.
