### ISSUE TITLE
[동영상재생] mp4코덱변환하여 s3에 업로드

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#195]
현재 컨텐츠에 업로드파일로 동영상 파일을 올리면, 자동재생하게끔 구현되어 있다.

여기서 동영상파일의 코덱과 플레이어의 코덱 호환성에 따라 재생이 되지 않는 일부 코덱이 있다는 것이 발견되었다.

이에 업로드된 어떤한 영상이든 Mp4 part10으로 변환해서 업로드(s3) 및 재생 그리고 다운로드 되게끔 코드를 수정한다.

이미지와 같이 변환하는 중에 convert 해주는 외부라이브러리가 필요할 수도 있다. (ffmpeg 이라고 예상된다.)

**Comment by ggamsang** [comment]
이슈 확인하였습니다.

convert 는 ffmpeg 으로 할 것이고, 이를 이용한 라이브러리는 좀 더 조사한 후에 적용하겠습니다.

동영상파일업로드는  백엔드에서 updateCardAllData라는 함수를 통하여 진행되고 있습니다.
이 함수 내에서 

계획은 아래와 같습니다.
- 노드 내에서 영상변환 확인
- updateCardAllData에서 영상파일이 있는지 확인
- 어떤 영상파일인지에 따라 변환옵션을 다르게 줌
- 옵션에 맞게 변환명령을 내리고 대기
- 변환이 완료되면 전송된 데이터 중 영상파일이름, 타입에 대한 데이터를 갱신하고 next()한다.

위와 같이 진행할 예정이며, 완료시점은 *5월6일*입니다.

**Comment by ggamsang** [comment]
하루만연장하겠습니다. 오늘중에 반드시 리퀘하겠습니다.

**Comment by ggamsang** [comment]
child_process 를 이용하여 노드외부에서 변환명령을 실행하는 방법으로 진행하고있습니다.

**Comment by opensrcdesign-admin** [comment]
완료로 크로즈합니다.

**Comment by opensrcdesign-admin** [comment]
늦었습니다. 일정준수하길바랍니다.

**Comment by opensrcdesign-admin** [comment]
다시 오픈합니다. 로컬환경에서는 잘 동작하나, 실 서비스환경에서는 에러가 발생합니다.
![Screenshot from 2019-05-08 11-11-40](https://user-images.githubusercontent.com/46555793/57344427-2d3a6680-7182-11e9-8f4a-25dc1ff74e4f.png)
확인후 다시 커밋해주시길 바람. 기한 넉넉히 잡고 우선 다른 이슈부터 처리하도록!

**Comment by ggamsang** [comment]
ffmpeg 로 변환 중 aac 라이브러리를 사용하는데 문제가 발생하였다.
명령어 중 -strict -2 를 추가하여 문제를 해결하였다.
예)
ffmpeg -y -i uploads/1558085172925.avi **-strict -2** -c:a aac -c:v libx264 -f mp4 uploads/1558085172925.mp4

이슈완료하였습니다 :)
