### ISSUE TITLE
[디자인 상세보기]단계 - 이름 글자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#20]
우선순위:B, 
변경후: **최대 20자로 제한**
변경전: _최대 8자로 제한_

**Comment by doeuncow** [comment]
2/2

**Comment by doeuncow** [comment]
# html
maxlength = "8"

or 

# jQuery
var elem = $("#myTextfield");
if(elem) elem.val(elem.val().substr(0,10));

**Comment by doeuncow** [comment]
issue change -> maxLength = 20

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "최대 8자"에서 "최대 20자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 varchar(100)로 최대100자까지 가능합니다.

**Comment by kimgyuri** [comment]
2월 22일까지 완료하도록 하겠습니다.

**Comment by kshahn** [comment]
단계 이름 (8자 이내)로 되어 있음. 현재 8자 이상 입력하면 짤림
그러나 수정하여 8자 이상 입력하면 됨. 시급한 조치 요망
테스트 철저히 하도록!!!

**Comment by kimgyuri** [comment]
디자인 상세보기 단계 이름 20자로 글자수 제한 완료하였습니다.
수정했을때도 20자 제한 완료하였습니다.

- /home/gyurl/opendesign/myfront/src/components/Designs/CreateBoard/CreateBoard.js
  101번째줄 수정, 102번째줄 maxLength 추가

- /home/gyurl/opendesign/myfront/src/components/Designs/DesignBoard/BoardUpdate.js
  86번째줄 수정, 87번째줄 maxLength 추가

**Comment by kimgyuri** [comment]
해당 이슈는 완료되었으므로 확인 후 클로즈 부탁드립니다.
