### ISSUE TITLE
[통합] 오픈소스사이트 내 모든 **문자표시** 길이제한 리스트업

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#200]
해당이슈는 오픈소스사이트에서 표시되는 모든 문자들의 길이가 해당문자 디자인 너비보다 초과되는 경우 "..."로 표시하도록 기능을 구현한다. 이전에 어떤 것들이 이에 속하는지 리스트를 만들어 관리한다.
(예를 들어 디자인 카드의 이름을 보면 디자인의 이름이 길면 "..."로 표시된다. )

![Screenshot from 2019-04-11 10-34-46](https://user-images.githubusercontent.com/46555793/55924612-752ea200-5c45-11e9-9391-a5b0538a4414.png)

**Comment by ggamsang** [comment]
금일 중 리스트 작성완료하여, 일정잡도록하겠습니다!

**Comment by ggamsang** [comment]
css로 가능하며, 현재 이 방식으로 구현되어 있음.

**Comment by ggamsang** [comment]
구성요소 | 상세내용 | 구현여부 | 비고
---| --- | --- | ---
상단메뉴|사용자이름|O| -
하단메뉴|카피라이트|-| -
디자인카드|디자인제목|O|-
디자인카드|작성자이름|O|-
디자인카드|카테고리|-|-
디자인상세| 디자인제목|-|-
디자인상세| 디자인설명|-|-
디자인상세| 디자인작성자이름|-|-
디자인상세| 디자인카테고리|-|-
디자인상세| 맴버목록|O|-
디자인상세| 단계제목|O|-
디자인상세| 카드제목|-|-
디자인상세| 카드작성자이름|-|-
디자인상세| 파생목록 디자인이름|-|-
디자인상세| 파생목록 작성자이름 |-|-
그룹카드| 그룹제목|O|-
그룹카드| 작성자이름|-|-
그룹상세| 그룹제목|-|-
그룹상세| 그룹설명|-|-
그룹상세| 작성자이름|-|-
디자이너카드| 디자이너이름|O|-
디자이너상세| 디자이너이름|-|-
디자이너상세| 디자이너설명|-|-
알림| 알림제목|O|-
알림| 알림설명|-|-
메시지|대화상자 상단문구|-|-
메시지|대화상자 사용자이름|-|-자

리스트작성하였습니다.
구현방식은 컴포넌트를 한 개 만들 것이며, 입력된 텍스트와 너비에 따라 css에서 제공하는 text-overflow를 통해 "..."으로 처리할 것이며, 마우스오버시 모든내용이 보일수있도록할 것입니다.

완료시점: 5월3일

**Comment by ggamsang** [comment]
컴포넌트만들어서 적용 중.

**Comment by opensrcdesign-admin** [comment]
리퀘확인/머지 하였습니다. 해당이슈는 크로즈합니다.
