### ISSUE TITLE
[디자이너] 디자이너 페이지에서 자신의 카드를 클릭 시 남처럼보입니다.

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#203]
디자이너 페이지에서 자신의 카드를 클릭하면 다른 디자이너와 같은 레이아웃이 뜨는데,
클릭한 카드가 자기 자신이라면 [마이페이지]로 이동하게 변경해야할 것으로 보입니다.

**Comment by opensrcdesign-admin** [comment]
완료로 인한 이슈종료!

**Comment by ggamsang** [comment]
다시오픈해주시기바랍니다. 수정해야할 부분이 있어서요.  우선 로그인 데이터 저정위치 이슈부터 해결 하고 난 후에 오츤하셔도
좋을것같습니다.

2019년 4월 15일 (월) 15:52, opensrcdesign-admin <notifications@github.com>님이 작성:
