### ISSUE TITLE
[메시지] 레이아웃변경

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#213]
아래와 같은 조건으로 메시지페이지의 레이아웃을 변경하는 이슈입니다.

1) 좌측 대화상대 목록 사이즈 줄임
2) 좌측 대화상대 목록 높이 늘림
3) 우측 대화내용 높이 줄임 : 대화내용 및 입력창 한 화면에 보이게 

이외 추가될 사항이 있다면 추가하시기 바랍니다.

**Comment by opensrcdesign-admin** [comment]
레이아웃바꾸면서 메시지알림도 함께 수정하길.

**Comment by ggamsang** [comment]
이슈 진행 중입니다.
메시지알림표시에 대해서 배포(수정/머지/배포)하였습니다.
레이아웃수정후리퀘하겠습니다.
소요일은 2일 예상하고 있습니다.
**5월18일**

**Comment by opensrcdesign-admin** [comment]
머지하여 크로즈합니다.
