### ISSUE TITLE
[텍스트에디터] 기능개선

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#216]
현재 오픈소스사이트 내 디자인카드의 내용을 추가 또는 수정할 때 TextController.js 를 이용하여 텍스트를 편집합니다. 하지만, 현재 구현된 기능들이 다소 불편함을 주기 때문에 개선의 여지가 있습니다. 이에 이를 개선하기를 제안합니다.

제안하는 방법으로 첫번째 방법은 공개된 텍스트에디터(네이버 스마트에디터)를 적용하는 방법이 있을 것이고,
다른 방법으로는 현재 버전에서 어떤 기능들이 존재하고, 불편한 것은 어떤 것이며, 어떤 것들이 더 필요한지 개선사항을 목록으로 만들어 개선을 하는 방법입니다.

할당된 인원은 위에서 말한 방법에 대해서 생각해보시고 더 좋은 방법이 있다면 제안해주시면 감사하겠습니다.

**Comment by wwjdtm** [comment]
현재 새로운 텍스트에디터를 찾아본결과, 대표적인 툴로는
1. 네이버 웹에디터 (http://dev.naver.com/projects/smarteditor/ )
2. tinyMCE (http://www.tinymce.com/)
3. ckeditor (https://ckeditor.com/)
위의 세가지가 있는 것 같습니다.

현재 오픈소스홈페이지에 적용된 텍스트에디터의 기능에서는 
볼드체, 글자 기울이기, 밑줄체, 글자 정렬, 글자크기, 글자색변경 의 기능을 지원하고 있습니다.

불편한점
1.글자크기 종류가 다양하지 않은점
2.맞춤법 검사기능으로 인한 밑줄 점선표시
3.현재 어떤 기능이 적용중인지 표시되지 않는 부분

더 적용되었으면 하는 부분
1. 취소선
2. 글자 배경색 선택

**Comment by opensrcdesign-admin** [comment]
추가하자면,
블록지정 후 기능을 수행하면 블록이 해제되는데 이것이 불편할 수 있다는 의견도 있었습니다 :)

**Comment by wwjdtm** [comment]
현재 홈페이지 코드를 살펴본결과, 특정한 텍스트 에디터가 사용되지 않고 구현되어 있습니다.
src/components/Designs/CardSourceDetail/TextController.js

**Comment by wwjdtm** [comment]
다른 파일에서 글씨를 카피해왔을 경우 해당 글씨에 적용된 폰트도 함께 카피되는 현상 발생

**Comment by opensrcdesign-admin** [comment]
ckeditor 를 사용하도록 합시다! 

우선 적용해보시고, 향후에 경량화하는 진행하도록 합시다.  

라이센스 확인해주세요 (코드수정해도 되는지 재배포가능 한지 등)

일정잡아주시길 바래요~

**Comment by wwjdtm** [comment]
현재 ckeditor에 무료 라이선스관련 문의글을 남겨두었습니다. 답변을 받으면 진행할 수 있을 것 같습니다.

**Comment by wwjdtm** [comment]
CKEditor5는 GPL-2.0 or later, CKEditor4 이하 버전은 GPL-2.0 or later, LGPL-2.1, MPL-1.1(*세 라이선스 중 한 가지를 선택하여 따르면 됩니다.)로 배포되고 있습니다. 
CKEditor의 소스코드를 수정하고 재배포하는 것은 모두 무료로 가능하며, 라이선스의 의무사항만 준수하시면 됩니다.
학교 내부에서 CKEditor를 수정하여 사용하는 경우에는 문제될 것 없지만, 재배포 하실 경우 수정한 버전의 소스코드를 수취인에게 제공해야 합니다. 
이상입니다. 
※ 법적 분쟁 발생시 본 답변은 법률적 해석 혹은 논리로 활용될 수 없습니다. 

라이선스 문의에서 위와 같은 답변을 받았습니다. 
CKEditor4, 5를 확인해본 결과 
CKEditor4
<img width="1147" alt="스크린샷 2019-05-28 오후 5 08 27" src="https://user-images.githubusercontent.com/28584133/58461700-3e680900-816b-11e9-9ff5-fe8f669cb18a.png"> 

CKEditor 5
<img width="891" alt="스크린샷 2019-05-28 오후 5 08 20" src="https://user-images.githubusercontent.com/28584133/58461712-488a0780-816b-11e9-9190-3071fb585488.png">

CKEditor 5를 사용하는 것이 좋을 것 같습니다

**Comment by opensrcdesign-admin** [comment]
그럼 5버전으로 사용하는것으로 하죠!

**Comment by ggamsang** [comment]
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html 를 참고하여
TextController.js파일에 적용 중.
클래식버전에서는 폰트기능들이 없어 플러그인을 설치해야함.
커스터마이징을 하기위해 저장소를 클론하여 필요한 플러그인을 설치하고 빌드해야함.

**Comment by opensrcdesign-admin** [comment]
미리빌드하지않고 컴파일타임에 생성되는 방식으로 구현됨.
기능추가삭제하기에 후자가 더욱 용이하다고 판단되어.

해당이슈 완료로 크로즈합니다.
