### ISSUE TITLE
[디자인댓글] 댓글에 "@아이디"를 입력하면 해당인원에게 알람가도록 기능구현

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#218]
디자인 댓글 입력창에 "@"를 입력하면 팀원목록을 표시하여 사용자는 댓글을 달았다고 알람을 보내는 기능을 구현한다.

**Comment by ggamsang** [comment]
사용자로부터 입력이 있을 때마다 값을 체크하게끔 되어 있기때문에 @가 입력되면 간단한 팝업창이 뜨도록하고,
팀원의 목록을 불러오도록할 것입니다.
백엔드에서는 댓글이 입력요청이 이뤄지면 건네받은 문자열에서 @아이디 형식의 문자열을 추출하고, validation후 알람을 만듭니다. 이때, 접속한 인원이 있으면 바로 알람이 가게끔합니다.

완료시점은 **5월 21일**입니다.

**Comment by ggamsang** [comment]
1) 팀원 목록 가져오기
2) 팀원 팝업창생성
3) @ 문자 체크
4) 백엔드에서 @문자로 인원확인
5) 해당인원에게 보낼 알람생성
6) 소켓이있다면(접속중이라면) 알람보냄
와 같이 진행될 예정입니다.

**Comment by ggamsang** [comment]
위와 같이 진행하고있으며, 다른이슈처리(#229, #230, #228 and so on...)로 인하여 해당이슈기한을 연장하려고합니다.
예상완료시점은 **5월24일**입니다.

**Comment by opensrcdesign-admin** [comment]
다른이슈부터처리하고 진행하기로함.
