### ISSUE TITLE
[디자인 상세보기] 순서변경기능창 디자인 개선

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#22]
우선순위:B, 단계 내에 있는 컨텐츠들을 최신순으로 정렬해 표시한다.

**Comment by doeuncow** [comment]
2/2

**Comment by ggamsang** [comment]
해당 이슈는 최신순으로 정렬하기보다는 #65 와 같이 **순서변경가능**한 기능을 제공해야하는 이슈입니다.
#65 가 완료되며 +3일 하여 **2월 19일**에 완료하는 것으로 하겠습니다.

**Comment by ggamsang** [comment]
일정변경: 2월21일
#65가 아직구현되지않았음으로 #65 duedate +1일하여 21일에 완료예정.

**Comment by ggamsang** [comment]
일정변경: 
#65 에 따라 일정변경합니다.
due date: 02.26

**Comment by eleutheria80** [comment]
@ggamsang 일정에 문제없는지 코멘트 남겨주세요.

**Comment by opensrcdesign-admin** [comment]
#65 완료된 상태로 시작하면 +1일 소요된다고 했으니 완료시점은 3월4일입니다.
중요한 이슈입니다.

**Comment by eleutheria80** [comment]
@ggamsang 완료일이 지났습니다. 현재 상태 공유 해 주세요.

**Comment by ggamsang** [comment]
- 진행사항
- [ ] 버튼추가
- [ ] 변경요청이벤트연결
- [ ] 변경요청
- [ ] 백엔드 변경요청 라우터 확인 / 추가
- [ ] 디버깅

**Comment by ggamsang** [comment]
- 추가수행업무
-데이터베이스 7244행 업데이트, order값이 모두 0이어서 순서부여 / 백업함

- 추가할사항
-다른 브라우저 실시간 업데이트! **[중요]** 
오늘(3월6일) 중에 완료목표

**Comment by Jinakimm** [comment]
<img src = "https://user-images.githubusercontent.com/47623887/53870834-4a49a080-403e-11e9-92ab-f78bb5e02311.PNG" width= "50%">

**Comment by Jinakimm** [comment]
/
**아직 디자인이 확정된 것이 아니라 컨텐츠 순서 변경 기능만 참고해주세요!**
/
/
/
/
일단 지금 현재 사이트 디자인이 아무것도 되어있지 않아서 인터페이스보다 제가 오늘 회의 끝나고 말씀드렸던 위치에 신경써주시면 감사하겠습니다

![12](https://user-images.githubusercontent.com/47623887/53888338-93fab100-4067-11e9-9166-5b11f92bc777.jpg)
![13](https://user-images.githubusercontent.com/47623887/53888339-93fab100-4067-11e9-9802-d4e218173916.jpg)
![14](https://user-images.githubusercontent.com/47623887/53888340-94934780-4067-11e9-8b47-75930637a797.jpg)
![15](https://user-images.githubusercontent.com/47623887/53888341-94934780-4067-11e9-9d6f-753c10120686.jpg)
![16](https://user-images.githubusercontent.com/47623887/53888342-952bde00-4067-11e9-9566-6fdb40830d12.jpg)

**Comment by ggamsang** [comment]
기본적인 기능은 구현하여, 리퀘리스트한 상황이지만,
제안된 디자인에 맞게 구현하기 위해 일정변경을 변경하고자합니다.
완료시점은 **3월 12일**입니다.
변경사항
화살표버튼에서 모달창띄워서 변경하는 방식으로
모달창띄울때 위치 제안에 맞게 창의 위치가 relative 하게 할것.

**Comment by ggamsang** [comment]
수행예상항목
- [ ] : 버튼메뉴 추가하여 모달뛰우기
- [ ] : 모달로 부터 순서변경
     - [ ] : 목록가져오기 기능구현
     - [ ] : 쇼터블기능구현
- [ ] : 변경된 내용 받아서 순서변경 요청함수
- [ ] : 백엔드이슈
- [ ] : 디버깅

**Comment by ggamsang** [comment]
![Screenshot from 2019-03-13 09-04-22](https://user-images.githubusercontent.com/28895134/54244240-10f9bf00-456f-11e9-8efc-88d0651be471.png)
![Screenshot from 2019-03-13 09-04-31](https://user-images.githubusercontent.com/28895134/54244244-15be7300-456f-11e9-99d1-b4cfa94dbe2e.png)

**Comment by Jinakimm** [comment]
저 #그리드는 무엇인가요?
이것 또한 세부 디자인은 나중에 수정하도록 할게요!
