### ISSUE TITLE
[디자인 상세보기]단계 - 한 화면에 단계표시 개수

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#23]
우선순위:B, 현재는 4로, 6개 표시되도록 수정해야한다.

**Comment by doeuncow** [comment]
2/2

**Comment by eleutheria80** [comment]
@doeuncow 2/2일이면 주말인데 가능하면 휴일 빼고 working day 기준으로 일정 산정 해 주세요.
그리고 파악한 문제 원인도 같이 적어주세요.

**Comment by doeuncow** [comment]
closed 할 기능
