### ISSUE TITLE
[v1.5] 디자인개선 - 디자인 엘레멘트 컴포넌트 구현

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#253]
오픈소스디자인 사이트에 사용되는 디자인 엘레멘트 컴포넌트를 구현하기위해 해당이슈를 열었습니다.

현재는 아래와 같이 되어 있으며,
![Screenshot from 2019-06-24 19-09-10](https://user-images.githubusercontent.com/46555793/60010861-971bba80-96b3-11e9-8270-163cf1c48ffa.png)

이를 아래와 같이 변경하고자 합니다.
![Screenshot from 2019-06-24 19-11-02](https://user-images.githubusercontent.com/46555793/60011002-d944fc00-96b3-11e9-8c97-2dfaf52459f1.png)
![Screenshot from 2019-06-24 19-10-22](https://user-images.githubusercontent.com/46555793/60011003-d944fc00-96b3-11e9-86f7-4dd6242ca2a4.png)

작업은 메신저로 공유된 파일을 참고하시면 될 것 같습니다.

**Comment by opensrcdesign-admin** [comment]
**완료시점: 6월 28일(+ ~30일)**

**Comment by wwjdtm** [comment]
yarn패키지 실행도중 지속적인 에러발생으로 개발이 지연되어 완료시점을 7월3일로 변경하겠습니다.

**Comment by wwjdtm** [comment]
디자인카드에 제목이 표시될 때 제목길이가 길 경우, ... 으로 표시할지 개행을통해 제목 전체를 표시할지 정해야할 것 같습니다.

**Comment by opensrcdesign-admin** [comment]
해당 이슈 크로즈 된 상태입니다.

넵! 제안사항 반영하여 업무 진행하도록 하겠습니다!! : )



2019년 7월 1일 (월) 오후 12:02, wwjdtm <notifications@github.com>님이 작성:
