### ISSUE TITLE
[디자인 상세보기]댓글 - 글자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#27]
우선순위:B, 
변경후: **최대 문자 500자로 제한한다.**

**Comment by kimgyuri** [comment]
현재 텍스트 제한이 되어있지 않습니다. 2월 3일까지 해결하도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
최대 500자로 제한한다.로 내용수정.

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글500자(1000자)"에서 "문자500자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 longtext로 최대4294967295자까지 가능합니다.

**Comment by kimgyuri** [comment]
글자수 제한 완료된 상태이며 깃에 업로드하는 도중에 에러가 생겨 2월 11일에 해결 후 바로 업로드 하도록 하겠습니다.

**Comment by kimgyuri** [comment]
이슈 완료했습니다.

**Comment by kimgyuri** [comment]
테스트서버에서 확인해본 결과 적용이 되지 않은 것 같아 다시 수정해서 올렸습니다.
