### ISSUE TITLE
[디자인 상세보기]설명 - 글자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#29]
우선순위:B,
변경후: **최대 문자 1000자로 제한하기**
변경전: _최대 한글 500자(1000자)로 제한하기_

**Comment by eleutheria80** [comment]
예상 수정일과 분석한 오류 발생 원인을 적어주세요.

**Comment by kimgyuri** [comment]
현재 텍스트 제한이 되어있지 않습니다. 2월 3일까지 해결하도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
이슈내용이 "최대 한글 500자(1000자)로 제한하기" 로 수정되었습니다.

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글500자(1000자)"에서 "문자1000자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 longtext로 최대4294967295자까지 가능합니다.

**Comment by kimgyuri** [comment]
글자수 제한 완료된 상태이며 깃에 업로드하는 도중에 에러가 생겨 2월 11일에 해결 후 바로 업로드 하도록 하겠습니다.

**Comment by kimgyuri** [comment]
2월 22일까지 완료하도록 하겠습니다.

**Comment by kimgyuri** [comment]
디자인 상세보기 설명 글자수 1000자 제한 코드 작성 완료하였습니다.
다만, 현재 제 로컬로 디비 연결이 되지 않아 테스트 서버에서 제대로 확인하지 못했기 때문에 25일 디비 연결 제대로 한 후에 다시 한번 확인하도록 하겠습니다.
- /home/gyurl/opendesign/myfront/src/components/Designs/DesignBoardCard/CardContentUpdate.js
  66번째줄 maxLength 추가, 68번째줄 수정

**Comment by eleutheria80** [comment]
@kimgyuri 현재 상황 정리해서 코멘트 남겨주세요.

**Comment by kimgyuri** [comment]
어제 디비 연결 완료 했으며 코드 다시 확인하고 올리도록 하겠습니다.

**Comment by kimgyuri** [comment]
디자인 상세보기 설명 1000자로 글자수 제한하였습니다.
1000자 이상을 입력하였을 시, "1000자 이하로 입력 할 수 있습니다." 라는 알림이 뜨도록 만들었습니다.
- /home/gyurl/opendesign/myfront/src/components/Designs/DesignCardModify/DesignCardModify.js
  109번째 줄 validates={["Required", "MaxLength(1000)"]} 추가

**Comment by kimgyuri** [comment]
@opensrcdesign-admin 해당 이슈 확인 부탁드립니다!

**Comment by opensrcdesign-admin** [comment]
확인하였고, 머지하였습니다.

디자인 설명이 또 어디에 있는지 확인부탁드립니다. 없으면 없다고 알려주시고 있으면 그것도 풀리퀘해주세요.
만약에 그게 이슈로 이미 있다면 그 이슈에서 풀리퀘해주세요~  :smile: :+1:

**Comment by kimgyuri** [comment]
현재 디자인 카드 보드에서 컨텐츠 추가할 때 제목 글자수에 제한이 없어서 20자 제한으로 코드 수정하였습니다.
풀리퀘스트한 상태이니 확인 후 머지부탁드립니다!
- /home/gyurl/opendesign/myfront/src/components/Designs/CreateCard/CreateCard.js
  84번째줄 수정

**Comment by kimgyuri** [comment]
그리고 디자인 보드에서 컨텐츠 추가할 때 제목 입력하는 부분에 "새로운 컨텐츠의 제목을 입력해주세요." 라고 뜨는데 문장이 길어서 잘려서 출력됩니다! 문장의 길이를 줄여야 할 것 같은데 어떻게 바꾸면 좋을까요?

**Comment by opensrcdesign-admin** [comment]
"제목을 입력해주세요."
"새 컨텐츠의 제목을 입력하세요."
"새 카드의 제목을 입력해주세요."
.... 정도가 되겠네요.

**Comment by kimgyuri** [comment]
문장 길이 수정해서 풀리퀘스트 해놓았습니다. 확인부탁드립니당~ @opensrcdesign-admin

**Comment by opensrcdesign-admin** [comment]
금일 2월 28일 회의내용에 따라 해당이슈는 닫겠습니다.
