### ISSUE TITLE
[사이트 footer]사이트 이용약관 내용 최신화

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#36]
우선순위:B, 표시됨, 검수가 필요하다고 함.

**Comment by opensrcdesign-admin** [comment]
현재 구현된 상태로 학교에 문의해야겠습니다. 차주에 문의하여 결과 남기도록하겠습니다.

**Comment by ggamsang** [comment]
현재 구현된 상태로 학교에 문의해야겠습니다. 차주에 문의하여 결과 남기도록하겠습니다. (**2월15일**)

**Comment by ggamsang** [comment]
(#37내용과 같음)
진행사항 
관련사항에 대해 문의함.
CRC센터답변: 전임자에게 문의해볼 것(정보기획팀업무가 아닐지...??)
전임자답변: 해당이슈에 대해서 모름
정보기획팀 퇴근시간이라 내일다시 시도해보겠음...ㅠ

**Comment by ggamsang** [comment]
due date: 02월22일
정보통신처에 문의중 이번주안으로 해결될 것으로 보임

**Comment by opensrcdesign-admin** [comment]
담당자와 통화내용요약
-----
0) 이용약관 및 개인정보보호정책 페이지
- 약관/정책에는 필수항목이 있음: 그에 맞게 작성되지 않은것으로보임
- 유지보수가 되고 있는가: 최신화되어 있지않음
- 기타: 브라우저환경에 따라 화면이 잘 보이지 않고 있음

1) 회원가입 및 관리
 - 가입 전/후로 입력한 개인정보 보호정책에 대해서 공지해야함.
 - 개인정보 보호정책에 동의
 - 회원탈퇴 시 개인정보에 대해서 공지해야함.
 - 비밀번호 암호화 되어 있는가? 되어있음
 - 관리페이지 보안에 취약하면 ssh등 client툴이용하여 데이터베이스관리할 것.

2) 로그인
관리자와 일반사용자간 페이지를 분리해야함. 
(예를 들어, opensrcdesign.com/admin/login.js)

3) 국민대 내부관리계획 및 개인정보보호 참고하여 준수할 것.

위와 같습니다.
여기서, 앞으로 구현해야할 사항들, 지금 살펴봐야할 것들이 많습니다.
우선, "이용약관"과 "개인정보보정책" 페이지 최신화하겠습니다.
그 후,  회원가입, 관리자로그인, 내부관리계획 참고 순으로 진행하도록 하겠습니다.
이 이슈는 우선 하기로 한 것에 대해서만 다루고 기타 이슈는 따로 열도록 하겠습니다.

**Comment by eleutheria80** [comment]
@ggamsang 우선 하기로 한 것에 대한 내용과 기타 이슈에 대한 내용을 정리해서 코멘트 남겨주세요.

**Comment by eleutheria80** [comment]
@ggamsang 이슈가 어떤 상황인지 정리 해 주세요.
