### ISSUE TITLE
[회원정보 수정]자기소개 문자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#4]
우선순위:B, 
변경후: **최대 문자 1000자로 제한하기**
변경전: _최대 한글 500자(1000자)로 제한하기_

**Comment by wwjdtm** [comment]
1/31

**Comment by eleutheria80** [comment]
@wwjdtm 각 이슈에 단순히 날짜만 적지 마시고 파악한 원인도 같이 적어주세요.

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글500자(1000자)"에서 "문자1000자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 longtext로 최대4294967295자까지 가능합니다.

**Comment by kimgyuri** [comment]
2월 21일까지 완료하도록 하겠습니다.
