### ISSUE TITLE
[테스트환경]테스트환경완료시키기

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#40]
우선순위:AA, 현재버전 테스트해야하나 테스트서버가 없어서 원활히 테스트를 할 수가 없음 어서 테스트서버환경설정 완료할 것! 우선순위 아주 높음!

**Comment by ggamsang** [comment]
2월 8일까지 완료하고 테스트서버 사용법 공유하도록하겠습니다.
AWS 실서비스와 비슷하게 무료계정 하나 더 만들어서 할 계획입니다.

**Comment by ggamsang** [comment]
진행사항

무료계정생성 후
1) 백엔드(aws,ec2,13.209.182.26) 동작 중
2) 프론트엔드(aws,s3,http://ggmsng.com.s3-website.ap-northeast-2.amazonaws.com) 동작중
3) 데이터베이스(aws,opendesign-dev) 동작 중
4) 도메인 신청한 상태, 대기 중 ... 도메인신청완료되면 각 서비스에 짧은주소 및 도메인으로 접근가능.

결과: 테스트서버구현은 하였음, 하지만, 접근하기위해 위와 같이 주소가 복잡함. 이를 해결하기위해 route53이용해야하는데, 도메인신청완료되어야 진행할수 있음.

앞으로 남은 일 : 
> 도메인 받을 때까지 대기
> 도메인 설정 한 후 설정파일 편집
> 테스트서버 이용하기!

**Comment by ggamsang** [comment]
테스트서버 구축은 되어 있습니다.

사용법이 담긴 문서를 메신저에 공유하도록 하겠습니다. 
보안문제로 여기에 남길수없습니다.
backend (http://http.ggmsng.com)
frontend (http://ggmsng.com)

문제가 있다면 섬네일 업로드부분의 코드 및 설정 부분을 살펴봐야합니다. 그외엔 정상작동합니다.

**Comment by opensrcdesign-admin** [comment]
dev.opensrcdesign.com 다시 살려서 사용할것.

**Comment by opensrcdesign-admin** [comment]
사용이 필요하지 않아 테스트서버 비활성화시키겠습니다.
필요하신분은 따로 말씀해주시기 바랍니다.
