### ISSUE TITLE
[처리중레이어]각 화면 별 확인처리 메시지 표시

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#41]
우선순위:B, 안뜸

**Comment by ggamsang** [comment]
#42 이슈가 해결되어야 처리가능합니다. 
우선순위가 B이나 낮다고 보입니다. **2월 21일**까지 완료하도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
각 화면이라고 하면 어떠한 화면들을 말하는지 확인필요.
꼭 메시지를 띄워야하는 페이지의 목록을 만든다, 우선!

**Comment by eleutheria80** [comment]
@opensrcdesign-admin 진행 사항을 코멘트로 남겨주세요.

**Comment by eleutheria80** [comment]
@ggamsang 2차 개발 시에 진행 할 내용 정리 해 주세요.
