### ISSUE TITLE
[처리중레이어]처리완료되면 처리중레이어 닫음

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#42]
우선순위:B, 내용없음

**Comment by ggamsang** [comment]
#41 이 완료되면 가능한 기능입니다. #41 완료되면 하루정도 시간들이면 완료될 것으로 보입니다.
**2월 22일**까지 완료하고자 합니다.

**Comment by eleutheria80** [comment]
@ggamsang 22일 완료 예정인데 어떻게 진행되고 있는지 코멘트 남겨주세요.

**Comment by eleutheria80** [comment]
@ggamsang 정리해서 코멘트 남겨주세요.
