### ISSUE TITLE
[서버오류레이어]서버오류 발생시, 메시지 출력

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#43]
우선순위:B, 현재 비밀번호 찾기 이메일 전송 오류만 확인됨. 이전에 디자인 등록이 안될 때에는 따로 알림 창 없이 Loading 화면만 계속됨.

**Comment by ggamsang** [comment]
"현재 비밀번호 찾기 이메일 전송 오류만 확인됨." ㅡ> 
"이전에 디자인 등록이 안될 때에는 따로 알림 창 없이 Loading 화면만 계속됨." ㅡ> 이 문제는 백엔드에서 예외처리가 올바르게 되지 않아 프론트엔드에서 무한정 기다리게 됨으로써 생기는 원인으로 
백엔드에서 예외처리가 발생하면 그에 대응되게끔 프론트엔드도 수정해야합니다.
작은 이슈로 보이지 않습니다. **2월 28일**까지 하는 것으로 하고, 지속적으로 내용 업데이트하겠습니다.

**Comment by eleutheria80** [comment]
@ggamsang 어떻게 진행되고 있는지 코멘트 남겨주세요.

**Comment by eleutheria80** [comment]
@ggamsang 현재 상황 업데이트 해 주세요.
