### ISSUE TITLE
[메뉴 바] 메시지 아이콘 - 메시지 들어오면 아이콘변경

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#44]
우선순위:B, 현재: 새 메시지오면 "알림"아이콘에 표시됨, 수정: 새로고침없이 메시지아이콘에 표시되도록 수정

**Comment by wwjdtm** [comment]
2월26일까지 완료하겠습니다. 파악된원인은 추후 업로드하겠습니다

**Comment by wwjdtm** [comment]
메시지가 왔을경우 메시지아이콘이 활성화 되도록 수정

**Comment by opensrcdesign-admin** [comment]
이슈이름 변경하였습니다.

**Comment by wwjdtm** [comment]
이슈 #47 과 함께 해결하도록 하겠습니다. 메시지에 알림기능이 구현되어 있지 않습니다. 2월28일까지 완료하도록 하겠습니다

**Comment by wwjdtm** [comment]
해당 이슈는 closed 부탁드립니다 !
