### ISSUE TITLE
[메시지 페이지] 대화내용창

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#46]
우선순위:B, 대화내용 밑에 년월일표시, 아래의 시간나타내는법에 따라 표시방식 수정
시간나타내는법:  1분이내–초단위,  1시간이내–분단위,  24시간이내–시단위,  한달이내–일단위,  1년이내–달단위,  그이후–년단위

**Comment by wwjdtm** [comment]
2월26일까지 완료하겠습니다. 파악된원인은 추후 업로드하겠습니다

**Comment by opensrcdesign-admin** [comment]
이슈이름 변경하였습니다.

**Comment by wwjdtm** [comment]
메시지 대화창에서의 날짜 표현방식이 dateform으로 표현되지 않은것 같습니다. 이부분 수정 예정입니다.

**Comment by eleutheria80** [comment]
@wwjdtm 현재 상태 정리해서 코멘트 남겨주세요.

**Comment by wwjdtm** [comment]
수정기한을 2월 28까지로 수정하겠습니다.

**Comment by wwjdtm** [comment]
앞선 이슈처리가 예상보다 늦어져 해당이슈는 3월1일까지 수정하도록 하겠습니다

**Comment by wwjdtm** [comment]
수정해서 푸쉬하였습니다 ! 혹시 푸쉬되었나요 ???

**Comment by opensrcdesign-admin** [comment]
내용확인하였고, 해당이슈 닫겠습니다.
