### ISSUE TITLE
[메시지 페이지] 좌측 메시지 보낸 사람 목록(대화목록) 표시방법

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#47]
우선순위:B, 메시지 최대10개 표시, 그 이상은 스크롤

**Comment by wwjdtm** [comment]
2월15일까지 완료하겠습니다. 파악된원인은 추후 업로드하겠습니다

**Comment by wwjdtm** [comment]
detailwrapper style의 height를 수정하였습니다. 현재 상태에서 height를 max로 수정하였을때 보여지는 메세지의 갯수는 최대8개 표시, 그 이상은 스크롤됩니다.

**Comment by wwjdtm** [comment]
수정완료하였습니다 확인부탁드립니다 !

**Comment by opensrcdesign-admin** [comment]
수정내용확인하였습니다. 이슈가 열렸을 당시에 설명이 부족했던거 같습니다. 회의시간이 이야기합시다.

**Comment by wwjdtm** [comment]
이슈 내용 변경되었습니다 : 메시지 알림이 왔을때 메시지아이콘을 활성화 하고, 메시지 창 내부에서도 알림

**Comment by opensrcdesign-admin** [comment]
이슈이름 변경하였습니다.

**Comment by wwjdtm** [comment]
해당 이슈는 closed 부탁드립니다 !
