### ISSUE TITLE
[메뉴바 - 알람아이콘] 디자인 좋아요 눌렀을때 알림

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#48]
우선순위:B, 최신알림기준: 유저가 확인한 이후 새로운 알림개수표시

**Comment by wwjdtm** [comment]
2월15일까지 완료하겠습니다. 파악된원인은 추후 업로드하겠습니다

**Comment by wwjdtm** [comment]
확인 결과 알림개수표시 기능이 잘 작동하여 수정할 부분이 없는 것 같습니다. 회의때 말씀드리겠습니다

**Comment by wwjdtm** [comment]
알림 등록되어야 하는 경우 : 디자인등록, 등록한 디자인 편집, 메세지, 좋아요, 멤버초대 등등

**Comment by opensrcdesign-admin** [comment]
이슈이름 변경하였습니다.

**Comment by wwjdtm** [comment]
3월1일까지 마무리 하도록 하겠습니다

**Comment by wwjdtm** [comment]
해당이슈는 추가내용이 많아 시간이 걸릴것으로 예상되어 기한을 3월8일로 변경하겠습니다

**Comment by eleutheria80** [comment]
@wwjdtm 현재까지 진행 사항 업데이트 해 주세요.

**Comment by wwjdtm** [comment]
본인의 프로젝트에 좋아요가 눌렀을때 알림이 활성화는 기능 구현중입니다

**Comment by wwjdtm** [comment]
현재 개발환경문제로 인해(코드수정시 홈페이지 업데이트가 작동안함) 이슈처리가 늦어질 것 같아 기간을 3월11일로 변경하겠습니다.

**Comment by wwjdtm** [comment]
수정완료하여 푸쉬하였습니다

**Comment by wwjdtm** [comment]
수정완료하였습니다 !

**Comment by opensrcdesign-admin** [comment]
완료되어닫습니다.
