### ISSUE TITLE
[회원정보 수정]이름 문자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#5]
우선순위:B, 
변경후: **문자 최대 45자로 제한하기**
변경전: _최대 한글 25자(50자)로 제한하기_

**Comment by wwjdtm** [comment]
1/31

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글25자(50자)"에서 "문자45자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 varchar(45)로 최대 45자까지 가능합니다.

**Comment by kimgyuri** [comment]
25자에서 45자로 수정 완료했습니다. 현재 깃헙 업로드 하는 도중 에러가 발생하여 2월 11일까지 해결하고 업로드 하도록 하겠습니다.
