### ISSUE TITLE
[회원가입]이용약관동의 여부 모달창으로 표시

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#51]
우선순위:B, 현재 unchecked에도 가입이 됨. checked일때만 가입가능토록 수정할것.

**Comment by wwjdtm** [comment]
2월15일까지 완료하겠습니다. 파악된원인은 추후 업로드하겠습니다

**Comment by wwjdtm** [comment]
회원가입시 이용약관 동의여부가 구현되어있지 않는것 같습니다. 회의때 말씀드리겠습니다

**Comment by wwjdtm** [comment]
이용약관 동의여부를 묻는 질문을 signupform에 추가하도록 하겠습니다. 2월 26일까지 완료하겠습니다

**Comment by wwjdtm** [comment]
이용약관 동의여부 확인여부 수정을 하였으나 회원가입 버튼 누른 이후에 자기소개를 입력하는 화면이 뜨지 않는 문제가 생겨 완료기간을 늦춰야할 것 같습니다. 
2월27일까지로 변경하도록 하겠습니다.

**Comment by wwjdtm** [comment]
![image](https://user-images.githubusercontent.com/28584133/53444960-ce09f880-3a52-11e9-9ccf-c1a3590f4c01.png)

**Comment by Jinakimm** [comment]
제가 소스를 만들어드려야하나요? 아니면 전체 화면 레이아웃을 드려야 하나요?
오늘은 제가 해야할 일들이 있어서 오늘까지는 업로드를 못 할 것 같습니다
어떤 것이 필요하신지 자세하게 말씀해주세용!
내일이나 내일 모레에 업로드하겠습니다

**Comment by ggamsang** [comment]
기본값이 체크되어 있는데 언체크로 해서 또 올려주세요~ :smiley:

**Comment by wwjdtm** [comment]
@ggamsang 기본값 언체크로 해서 푸쉬하였습니다 ~!
@Jinakimm 레이아웃?을 해주시면 좋겠어요 ! 회원가입창-이용약관동의 확인부분에서 이용약관내용을 위에 캡쳐본과 같이 링크나 버튼으로 연결 할지 아니면 텍스트박스로 추가 할지를 고려한 디자인을 제안해주시면 될 것 같아요 !

**Comment by ggamsang** [comment]
잘하셨어요ㅡㅋ :smiley: :+1:  근데 풀리퀘 모하고 체리:cherries: 픽할거같아요ㅡ 딸려온 커밋들이 있어서욤. 

나중에 체크박스사용할 때 , 반드시 value를 지정해주어야겠네요. 안그러면 null이 들어갈테니까뇽~  :smile:

**Comment by wwjdtm** [comment]
넵 ㅜ 다른 설정에 지장 안가게하려다보니 value값에 따라 바뀌게했어욥 
아 혹시 변경파일만 다시 푸쉬할까요??

**Comment by opensrcdesign-admin** [comment]
![screenshot from 2019-02-27 22-19-09](https://user-images.githubusercontent.com/46555793/53493036-bb88d100-3add-11e9-873d-e841ca50073e.png)
해당 부분만 머지해서 이미 적용된 상태입니다.

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/53495692-c47ca100-3ae3-11e9-9dca-b2b20d6ee4a4.png)

링크나 버튼으로 이용약관 보기를 누르게 하는 것이 더 나을 것 같습니다 요즘은 거의 대부분 읽지 않아서..

제가 지금 이용약관 전체 글을 볼 수가 없어서 내일 회의 때 보여주시면 그것 토대로 레이아웃 주말에 완료해서 올리도록 하겠습니다

그리고 모든 디자인 레이아웃은 아직 전체 디자인 레이아웃 여백이 정리되지 않아서 3월 이후에 바뀔 수도 있습니다ㅠ 일단 내일 자료 주시면 이번주 토요일까지 완료하겠습니다
due date. 03/02

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/53541211-13feb380-3b5c-11e9-8e7a-5139dbf8cfa8.png)

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/53546894-e839f880-3b70-11e9-933c-7b83241e092f.png)

**Comment by eleutheria80** [comment]
@wwjdtm 진행 사항 업데이트 해 주세요.

**Comment by wwjdtm** [comment]
이 이슈는 현재 수정 완료입니다. 디자인에 대한 이슈는 2차 수정때 다루기로 이전 회의때 결정하였습니다.

**Comment by opensrcdesign-admin** [comment]
merged, this issue will closed right now
