### ISSUE TITLE
[회원가입]비밀번호 규칙 

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#52]
우선순위:B, 아래의 조건에 맞아야 가입되도록 수정한다.
(A) 비밀번호 규칙에 어긋난 경우: ‘비밀번호는6자~ 15자이내로 영문, 숫자, 특수문자를 모두 조합하여 작성해 주십시오.’

**Comment by wwjdtm** [comment]
2월 11일까지 완료하도록 하겠습니다. 현재 우분투, 설정환경 재설치 문제로 파악된 원인은 추후 업로드 하겠습니다.

**Comment by wwjdtm** [comment]
완료날짜 2월12일로 정정하겠습니다.
비밀번호 인풋폼에서 입력값 형식 설정이 되어있지않습니다

**Comment by wwjdtm** [comment]
비밀번호 인풋폼에서 입력값 형식 설정이 아닌 회원가입 버튼을 눌렀을 때, 비밀번호 입력값 형식을 체크하는 기능을 추가하였습니다. 
수정 완료했습니다. 확인부탁바랍니다!
++ 이슈 053 (비밀번호 재입력 확인) 부분에서 추가적으로 수정할 부분이 있어 함께 수정하였습니다

**Comment by opensrcdesign-admin** [comment]
해당이슈 머지되었습니다.
기능잘작동합니다. 나중에는 비밀번호 입력하는 과정에서 체크하는 기능으로 변경해야할 것같습니다. 이에 대해서는 회의시간에 논의해주세요.

**Comment by eleutheria80** [comment]
@opensrcdesign-admin , @wwjdtm  최종 상태 정리해서 코멘트 남겨주세요.

**Comment by opensrcdesign-admin** [comment]
금일 2월 28일 회의내용에 따라 해당이슈는 닫겠습니다.
