### ISSUE TITLE
[회원가입]회원가입완료 후

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#54]
우선순위:B, 회원가입 후 회원가입 메시지를 3초동안 표시된 후 자동으로 사라지며 마이페이지로 이동하도록 한다.

**Comment by kimgyuri** [comment]
2월 26일까지 완료하도록 하겠습니다.

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/53151896-8b31c600-35f7-11e9-8b08-4d2016f909c9.png)

회원가입 메세지는 이런 어투로 가면 좋을 것 같습니다! 생각나서 올려봅니다

**Comment by opensrcdesign-admin** [comment]
@Jinakimm 제안하는 레이아웃이나 이미지있으시면 공유해주세요. 없으면 @kimgyuri 께서 해보셔도 좋을 것 같습니당!

**Comment by Jinakimm** [comment]
이런 레이아웃이 어떨까 해요
![image](https://user-images.githubusercontent.com/47623887/53148202-53be1c00-35ed-11e9-9502-e53f91d947a0.png)
회원가입이 완료 되면 마이페이지로 갈 텐데, 그 마이페이지가 백그라운드에 존재하고 저렇게 팝업 형식으로 띄우는건 어떨까 해요
백그라운드는 gradient balck opacity 30%~50%를 줘서 저 레퍼런스 사진처럼 명도 구분이 되면 더 확실해질 것 같아요!

**Comment by eleutheria80** [comment]
@kimgyuri 현재 상황 정리해서 코멘트 남겨주세요.

**Comment by kimgyuri** [comment]
현재 회원가입 완료 후 알림창이 뜨도록 alert을 이용해 코드 수정중입니다.

**Comment by opensrcdesign-admin** [comment]
이슈의 요구사항과 다르게 구현하고 있는거 아닌지 궁금합니다 :flushed::question:

어떤 방식으로 구현 하실 것인지 남겨주시면 감사하겠습니다 :smiley:

**Comment by kimgyuri** [comment]
앗 자동으로 뜨고 사라지게 해야되는걸 생각하지 못했네요! 죄송합니다.

**Comment by kimgyuri** [comment]
alert을 통해서 "마이페이지로 이동합니다." 라는 문구를 띄어주고 확인버튼을 누르면 이동하는 방식으로 구현하려고 했습니다! 3초동안 띄우고 자동으로 사라지도록 하는 방식은 시간을 갖고 조금 더 생각해야할 듯 싶습니다ㅠㅠ

**Comment by opensrcdesign-admin** [comment]
넵, 그럼 alert으로하는 걸로 하세요 :)

**Comment by opensrcdesign-admin** [comment]
https://stackoverflow.com/questions/49649767/reactjs-how-do-you-switch-between-pages-in-react
참고해서 구현하시면 될 것 같긴합니다.
3초는 타이머함수있구욤~

**Comment by kimgyuri** [comment]
29일까지 참고해서 구현하겠습니다! alert말고 타이머 함수 사용해서 해보겠습니다.

**Comment by kimgyuri** [comment]
타이머 이용해서 구현중입니다만 제가 구현하고 있는 파일의 위치가 정확한지 잘 모르겠습니당ㅠㅠ
App.js 파일에서 구현하는게 맞나요?

**Comment by kimgyuri** [comment]
현재 alert로 이용해서 회원가입창에서 마이페이지로 넘어가는 중에 알림창이 뜨도록 구현했습니다만
두번 뜨는 에러가 발생해서 원인을 찾아봐야 할 것 같습니당!

**Comment by opensrcdesign-admin** [comment]
타이머는 SignUpForm.js에서 구현하시면 될 것 같습니다.

alert이 뜨는 부분이 맞는지 잘 확인하시면 될 것같아요.

**Comment by eleutheria80** [comment]
@kimgyuri 날짜 다시 생각 해 보세요.

**Comment by kimgyuri** [comment]
넉넉잡아서 날짜를 29일로 해뒀는데 너무 늦다고 생각하시면 빠르게 해결하도록 하겠습니다. 정확하게 언제까지 끝낼 수 있다는 날짜를 저도 확신 할 수 없어서.. 죄송합니다

**Comment by kimgyuri** [comment]
아 죄송합니다ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 2월 28일까지 하겠습니다.. 순간 착각했네요ㅋㅋㅋ

**Comment by kimgyuri** [comment]
alert을 이용해 알림창이 뜨도록 했습니다만, 회의 떄 이전 버전과 같은 구현을 하자고 결정이 나서 다시 코드를 구현해야 할 것 같습니다.

**Comment by opensrcdesign-admin** [comment]
이미아실테지만, 타이머함수를 따로 만들기보단 콜벡함수로 구현하는 예제가 있으니 참고하시면 금방하실수 있으실것같습니다.

**Comment by kimgyuri** [comment]
이전 버전 홈페이지에서 회원가입을 실행해 보았습니다. 이전 버전은 아래 사진처럼 마이페이지 자체가 팝업으로 띄워지고 마지막에 텍스트가 뜨는데 저렇게 만들면 될까요? @opensrcdesign-admin 
![screenshot from 2019-02-28 21-06-10](https://user-images.githubusercontent.com/29365057/53565823-d91d6f80-3b9d-11e9-9161-64ddd7588208.png)
![screenshot from 2019-02-28 21-11-23](https://user-images.githubusercontent.com/29365057/53565825-db7fc980-3b9d-11e9-8c4d-0d3894f03efe.png)

**Comment by opensrcdesign-admin** [comment]
네ㅡ 그럼 이렇게 만드는것으로 하고 일정조정필요하시면 하시기바랍니다.

**Comment by kimgyuri** [comment]
3월 6일까지 하도록 하겠습니다

**Comment by kimgyuri** [comment]
이전 홈페이지에 적용되었던 코드보고 이해하는 중입니다! 현 서버에 맞게 코드를 수정하려면 시간이 조금 걸릴 것 같아요.

**Comment by eleutheria80** [comment]
@kimgyuri 예상 일정과 현재까지 진행 사항 알려주세요.

**Comment by Jinakimm** [comment]
회원가입 완료 후에 대한 디자인은 전체 테스트 완료 후 디자인 적용할 때 한꺼번에 제안하도록 하겠습니다

**Comment by ggamsang** [comment]
모달과 타이머를 이용하면 좋을 것 같습니다. 
https://stackoverflow.com/questions/52041452/countdown-on-modal 이거 참고하셔도 될 것 같습니다.

**Comment by kimgyuri** [comment]
위 링크 참고해서 3월 8일까지 완료하도록 하겠습니다.

**Comment by kimgyuri** [comment]
모달창 코드는 어느정도 구현을 했는데 타이머를 이용해 코드짜는 부분에서 약간 막힘이 있습니다. 기한은 다음 회의인 13일까지 늘리고 그 전까지 최대한 빨리 끝내보겠습니다.

**Comment by opensrcdesign-admin** [comment]
작업하신거 리퀘스트 부탁드립니다.

**Comment by kimgyuri** [comment]
풀리퀘스트 완료했습니다. 아래 이미지와 같이 구현한 상태입니다!
![Screenshot from 2019-03-13 17-25-30](https://user-images.githubusercontent.com/29365057/54263867-2b568b80-45b5-11e9-8afe-ecdf3e51ef8c.png)

**Comment by opensrcdesign-admin** [comment]
완료. 이슈닫겠음.
