### ISSUE TITLE
[디자인 수정]제목 - 글자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#60]
우선순위:B
변경후: **최대 문자 100자로 제한하기**
변경전: _최대 한글 50자(100자)로 제한하기_

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글50자(100자)"에서 "문자100자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 varchar(100)로 최대100자까지 가능합니다.

**Comment by kimgyuri** [comment]
2월 19일까지 완료하도록 하겠습니다.

**Comment by kimgyuri** [comment]
디자인 수정 제목 글자수 100자로 제한하였습니다.
(/home/gyurl/opendesign/myfront/src/components/Designs/ModifyDesignInfo/ModifyDesignInfo.js
166번째줄, 177번째줄 maxLength 추가)

**Comment by opensrcdesign-admin** [comment]
확인 후 풀리퀘스트 다시해주세요. 61이슈 리퀘했을 때 커밋을 보내오셨습니다.

**Comment by kimgyuri** [comment]
61이슈랑 파일이 겹쳐서 코드 내용도 같습니다! 풀리퀘스트 다시 해야할까요?

**Comment by kimgyuri** [comment]
해당 이슈는 완료하였으므로 확인 후 클로즈 부탁드립니다~
@opensrcdesign-admin
