### ISSUE TITLE
[디자인 수정]설명 - 글자수 제한

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#61]
우선순위:B
변경후: **최대 문자1000자로 제한하기**
변경전:_최대 한글 500자(1000자)로 제한하기_

**Comment by opensrcdesign-admin** [comment]
이슈내용에 혼돈되는 내용이 있어 수정합니다.
수정내용은 "한글500자(1000자)"에서 "문자1000자"로 변경합니다.
참고로 데이터베이스에서는 해당컬럼이 longtext로 최대4294967295자까지 가능합니다.

**Comment by kimgyuri** [comment]
2월 19일까지 완료하도록 하겠습니다.

**Comment by kimgyuri** [comment]
디자인 수정 설명 글자수 1000자로 제한하였습니다.
(/home/gyurl/opendesign/myfront/src/components/Designs/ModifyDesignInfo/ModifyDesignInfo.js
166번째줄, 177번째줄 maxLength 추가)

**Comment by opensrcdesign-admin** [comment]
수고하였습니다. 적용되었습니다.

**Comment by kimgyuri** [comment]
해당 이슈 클로즈 부탁드립니다~
@opensrcdesign-admin
