### ISSUE TITLE
[디자인 상세보기] 단계 - 순서변경 기능추가

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#65]
단계 순서를 변경할 수 있는 기능을 추가한다!
트렐로와 동일한 효과를 내도록.

**Comment by ggamsang** [comment]
2월 7일까지

**Comment by ggamsang** [comment]
일정변경
완료시점: 2월 14일

**Comment by ggamsang** [comment]
드래그앤드롭을 하여 순서를 변경하도록 기능을 추가할 것입니다.

**Comment by ggamsang** [comment]
일정변경
due date: 2월 20일
1) "event.dataTransfer" 함수를 찾지못하는 등 테스트코드를 적용하는 중,
2) DetailStep.js 구조가 복잡하여, 적용하는데 시일걸려.

**Comment by ggamsang** [comment]
1) 드래그앤드롭 기능
2) 드래그앤드롭으로 state내 order값 변경 기능
3) 값을 적용하기위한 요청기능 구현
와 같이 구현한다.

**Comment by ggamsang** [comment]
버튼방식으로 구현되었으며, 기본적으로 동작은 하나 불안전한 요소가 있어 이를 체크해봐야합니다.

due date: 02. 26

**Comment by eleutheria80** [comment]
@ggamsang 진행 사항 정리 해서 코멘트로 남겨주세요.

**Comment by opensrcdesign-admin** [comment]
머지함. 그래서 닫겠습니다. 드래그앤드롭은 다음버전에서 확실히 구현하도록하세요! :-1:
