### ISSUE TITLE
[파생디자인]파생디자인 생성

### ISSUE THREAD

**Issue by sojung1418** [kmu-crc/osd_front#72]
### 파생디자인 생성 관련 내용
- 모든 데이터(단계, 내용, 썸네일 등)를 복사
- 수정 및 관리가 가능하도록
-  기존의 '디자인 수정 폼'(단계) 이용 가능

**Comment by sojung1418** [comment]
### 기존 디자인 수정폼
![image](https://user-images.githubusercontent.com/30614706/52412914-7814f580-2b23-11e9-874e-6d1856ffd4bd.png)


### 변경될 사항
-  '파생디자인 생성'으로 변경
- 첫 화면은 파생할(부모) 디자인의 디자인수정 폼 데이터를 그대로 가져옴
- 바뀌면 안될 데이터(ex. 라이센스 등)은 표시하며 고정시켜둘 것

**Comment by kshahn** [comment]
라이센스가 '수정가능'이 아닌 디자인은 파생할 수 없음.
파생 디자인은 원 디자인의 라이센스를 그대로 따라야 하고 변경할 수 없음.
파생 디자인은 제목 앞부분에 파생 아이콘을 추가하여 식별 가능하도록 함.

**Comment by sojung1418** [comment]
오픈디자인 사이트 활용
https://opensrcdesign.com/designDetail/2940

**Comment by sojung1418** [comment]
**기한**
시나리오 정리 : ~2/18(월)
개발 1차 완료기한: ~2/25(월)

**Comment by sojung1418** [comment]
2/25:
진행중, 일부 에러로 개발지연중
2/28:
개발완료가능

**Comment by eleutheria80** [comment]
@sojung1418 진행 사항 정리해서 코멘트 남겨주세요.

**Comment by sojung1418** [comment]
오류해결하여 다시 개발 진행중입니다.
파생디자인 설계(문서화)와 같이 하도록 하겠습니다.

개발 완료기한 :2/28(목)

**Comment by sojung1418** [comment]
파생디자인 문서화 완료
진행상황과 함께 업로드하였습니다.

**Comment by sojung1418** [comment]
2/28: 개발완료
3/4: 구현 시연가능하도록 완료

3/6(수)에 회의 후 이슈 클로즈부탁드립니다.

**Comment by sojung1418** [comment]
3/6(수) 회의 시연을위해 실제디비에 연결하여 확인하는 과정에서 백엔드 구현이 부족함을 발견하였습니다.
다음 회의인 일주일 뒤 3/13(수)까지 부족한점 해결하도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
> 실제디비에 연결하여 확인하는 과정에서 백엔드 구현이 부족함을 발견하였습니다.
정확한 내용 공유해주시면 감사하겠습니다.

**Comment by sojung1418** [comment]
실제 서버에는 문제없습니다. 
제가 구현하는데에 있어서 백엔드 구현이 더 필요한것을 말씀드린것입니다.

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/54196497-f68afb80-4504-11e9-818e-9175261e9af1.png)
**파생 디자인이라는 언어를 쓰는 다른 사이트를 발견했습니다! 여기는 Fork라는 언어로 쓰네요**
혹시나 해서 올려봅니다

**Comment by ggamsang** [comment]
@Jinakimm 오ㅡ 프로세싱이네요, 반갑네요. 공유해주셔서 감사합니다!!!!
프로세싱 프로젝트들을 공유하는 사이트군요.
영어권에선 Fork를 많이 사용하나봅니다. ㅎ

**Comment by opensrcdesign-admin** [comment]
담당자 변경하였습니다. 
저장소 확인 결과 아직 인수인계(진행한것까지 본인저장소에 커밋/푸시하기)가 되지 않아보이지만, 기술명세서 보며 업무진행해야할 듯 합니다.

**Comment by ggamsang** [comment]
https://opensrcdesign.com/designDetail/2257 페이지에서 
"정보설계"보드 아래 "파생디자인"내용에 따라 아래와 같이 구현될 예정입니다.


백/프론트 | 구현내용
-- | --
프론트엔드 | 수정가능'의 경우 파생디자인생성'버튼을 표시한다.
프론트엔드 | [디자인 상세보기] 화면에서 '파생디자인생성'버튼을 클릭한다.
프론트엔드 | 생성요청함수를 호출하고, "로더"와 안내문이 있는 모달을 띄우고 대기한다.
백엔드 | "requestFork"가 발생하면 해당디자인을 조회하고 데이터를 변수에 저장한다.
백엔드 | 저장한 데이터를 조작한다.( 디자인제목, 카드제목에 "파생된"이라고 첨가한다.
백엔드 | 새로운 디자인을 생성하되 위의 저장된 데이터를 입력한다.
백엔드 | 위의 과정이 완료되면 프론트엔드로 새로운 디자인 아이디를 전송한다.
백엔드 | 위의 과정을 실패했을 시 프론트엔드로 메시지를 전송한다.
프론트엔드 | 백엔드로부터 실패 메시지를 받으면 안내창과 함계 이전 모달을 닫는다.
프론트엔드 | 백엔드로부터 완료메시지와 새로운 디자인 아이디를 받으면 해당디자인으로 화면이동을 한다.

*생성 시나리오에 의한 순서입니다.

**Comment by ggamsang** [comment]
섬네일 같은 경우 디자인상세보기 화면표시할 때 파생된 디자인이면 섬네일 위에 워터마크를 표시하게 합니다.

**Comment by ggamsang** [comment]
예정 완료시점: **4월 10일**

**Comment by ggamsang** [comment]
/*SELECT title, explanation, thumbnail, category_level1, category_level2,
			is_project, is_members, is_commercial, is_public, is_modify, is_display_creater, create_time, update_time, d_flag
				FROM opendesign.design  WHERE uid = 2494;*/
SET SQL_SAFE_UPDATES = 0;
DROP temporary table if exists tmp4;
CREATE TEMPORARY TABLE IF NOT EXISTS tmp4 AS (SELECT title, explanation, thumbnail, category_level1, category_level2,
			is_project, is_members, is_commercial, is_public, is_modify, is_display_creater, create_time, update_time, d_flag
				FROM opendesign.design  WHERE uid = 2494);

update tmp4 set title = concat("[파생됨]", title);
update tmp4 set explanation = concat("[파생됨]", explanation);

# select null as 'test', null as 'test', * from tmp4;
SET SQL_SAFE_UPDATES = 1;

**Comment by ggamsang** [comment]
메모
https://stackoverflow.com/questions/5859391/create-a-temporary-table-in-a-select-statement-without-a-separate-create-table 

You can use the TEMPORARY keyword when creating a table. A TEMPORARY table is visible only to the current session, and is dropped automatically when the session is closed. This means that two different sessions can use the same temporary table name without conflicting with each other or with an existing non-TEMPORARY table of the same name. (The existing table is hidden until the temporary table is dropped.) To create temporary tables, you must have the CREATE TEMPORARY TABLES privilege.

**Comment by ggamsang** [comment]
일정변경... **완료시점: 4월 12일**
데이터베이스 쿼리문 작성이 예상보다 오래걸리고 있어 연기하고자합니다.
현재 데이터베이스구조로부터 해당 데이터들을 어떻게 복제할 것인지에 대한 연구가 더 필요할 것 같습니다.

**Comment by ggamsang** [comment]
쿼리문 작성완료, 두 번째 사진에 처럼 생성된 모습을 볼 수 있습니다.
![Screenshot from 2019-04-11 21-05-48](https://user-images.githubusercontent.com/28895134/55955960-c8ccda00-5c9d-11e9-9d80-15e656743e0d.png)
![Screenshot from 2019-04-11 21-06-07](https://user-images.githubusercontent.com/28895134/55955964-ca969d80-5c9d-11e9-9fb4-2447f3d4f37e.png)

**Comment by ggamsang** [comment]
**파생표시아이콘** 카드 내 섬네일 우측하단에 표시할 예정이며, **디자인수정**페이지와 **디자인상세보기** 페이지에도 추가할 예정!

**Comment by opensrcdesign-admin** [comment]
머지하여 해당이슈 닫겠습니다.
