### ISSUE TITLE
[파생디자인]파생된 디자인 목록보기

### ISSUE THREAD

**Issue by sojung1418** [kmu-crc/osd_front#73]

**Comment by kshahn** [comment]
현재 디자인 디테일 화면에서 이 디자인에서 파생된 디자인이 있으면 (파생디자인보기) 버튼을 두고 이를 클릭하면 이 디자인에서 파생된 디자인 목록을 보여준다.
파생 디자인 생성 시 원본 디자인 데이터베이스 항목에 파생디자인 리스트를 추가하여 처리한다.
파생 디자인 목록은 바로 밑 단계만 보여준다. 파생 디자인 트리 보여줄 필요 없음.

**Comment by sojung1418** [comment]
**기한**
시나리오 정리 : ~2/18(월)
1차 개발기한: ~2/25(월)
개발완료기한:~2/28(목)

**Comment by sojung1418** [comment]
2/25:
개발 시작하지못함
2/28:
개발 진행예정

**Comment by eleutheria80** [comment]
@sojung1418 진행 사항와 예상 일정 정리해서 코멘트 남겨주세요.

**Comment by sojung1418** [comment]
파생디자인 생성 개발완료 후 바로 개발진행예정

문서화 완료기한: 3/4(월)
개발 완료기한: 3/7(목)

**Comment by eleutheria80** [comment]
@sojung1418 현재까지 진행에 문제가 없는지와 특이사항이 있으면 코멘트 남겨주세요.

**Comment by sojung1418** [comment]
진행사항이 많지 않아 3/6(수)에는 '파생디자인 생성' 까지만 완료로 보여드릴 수 있습니다.
'파생된 디자인보기'는 개발기한을 늘여야할 것 같아서 3/6회의 이후 바로 개발완료기한 다시 잡도록 하겠습니다.

**Comment by sojung1418** [comment]
'파생디자인 생성'의 기한이 미루어져서 3/6(수) 이후로 완료기한을 늦춰야합니다.
3/6(수) 이전까지 개발 완료기한 다시 잡겠습니다.

**Comment by eleutheria80** [comment]
@sojung1418 #74 이슈와 마찬가지로 테스트 기간 염두해서 확실하게 일정 계산해서 기한 설정 해 주세요.
@opensrcdesign-admin 2차 개발 라벨 설정 해 주시고 마일스톤 변경 해 주세요.

**Comment by ggamsang** [comment]
원본보기 구현할 사항은 아래와 같습니다.

백/프론트 | 구현내용
-- | --
프론트엔드 | 디자인 상세보기 화면에서 parent_id값이 있으면 '원본보기'버튼을 표시한다.
프론트엔드 | 부모 디자인으로 화면이동을 한다. (designDetail/:parent_id)

**Comment by ggamsang** [comment]
구현예정내용은 아래와 같습니다.

백/프론트 | 구현내용
-- | --
프론트엔드 | :forked의 값이 있으면 파생디자인목록모달을 생성하고, 파생디자인목록보기 버튼을 표시한다.
프론트엔드 | 목록보기를 클릭하면 모달을 표시한다.
프론트엔드 | 모달이 표시되면 "requestChildren"을 호출한다.
프론트엔드 | 모달이 표시되면 "로더"와 안내문을 띄우고 대기한다.
백엔드 | "requestChildren"가 발생하면 해당디자인을 parent_id를 하는 모든 디자인을 조회한다.
백엔드 | 조회된 디자인을 전송한다.
백엔드 | 예외처리가 발생하면 에러메시지를 전송한다.
프론트엔드 | 전송받은 목록을 출력한다.
프론트엔드 | 백엔드로부터 실패 메시지를 받으면 안내창과 함께 모달을 닫는다.
프론트엔드 | 목록의 디자인을 클릭하면 해당 디자인으로 이동한다.

**Comment by ggamsang** [comment]
위의 내용과 동일하게 구현할 것이며, 추가되는 내용있으면 추가하도록 하겠습니다.
완료시점은 **4월27일**입니다.

**Comment by opensrcdesign-admin** [comment]
완료시점 지났습니다. 해당내용에 대해 공유하기바랍니다.

**Comment by ggamsang** [comment]
5월1일까지 완료하겠습니다. 진행사항 계속 업데이트하겠습니다.

**Comment by ggamsang** [comment]
우선, 파생디자인목록을 생성하기위한 쿼리문을 작성합니다.

**Comment by ggamsang** [comment]
어떠한 디자인이 있고, 이 디자인으로부터 파생된 디자인의 목록을 조회하는 쿼리문은 다음과 같다.
여기서 어떠한 디자인의 uid는 0로 가정한다.
SELECT * FROM design WHERE parent_design=0;

**Comment by ggamsang** [comment]
디자인상세정보가져올때 해당디자인이 부모인지 조회후 결과를 boolean값으로 저장하도록 함/

**Comment by ggamsang** [comment]
![Screenshot from 2019-04-30 21-00-10](https://user-images.githubusercontent.com/28895134/56960227-0e890e00-6b8b-11e9-91d6-77b119dcf0a5.png)
진행사항 스크린샷으로 첨부합니다!

**Comment by opensrcdesign-admin** [comment]
머지하였습니다. 해당 이슈 닫습니다. 개선사항 발생 시 새롭게 이슈등록하여 진행주세요.
