### ISSUE TITLE
[파생디자인]파생 디자인의 원본 보기	

### ISSUE THREAD

**Issue by sojung1418** [kmu-crc/osd_front#74]
### 파생디자인의 원본 보기
파생된 파생디자인인지 확인 후 맞다면 이에대한 파생한(부모)디자인인 원본디자인을 볼 수 있도록 함(링크버튼)

**Comment by kshahn** [comment]
파생 디자인인 경우 (디자인 디테일) 화면에 원본 보기 버튼을 두고 이를 클릭하면 원본 디자인 디테일로 들어간다.

**Comment by sojung1418** [comment]
**기한**
시나리오 정리 : ~2/18(월)
1차 개발기한: ~2/25(월)
개발완료기한:~2/28(목)

**Comment by sojung1418** [comment]
2/25:
진행중, 일부 에러로 개발지연중
2/28:
개발완료가능

**Comment by eleutheria80** [comment]
@sojung1418 진행 사항 정리해서 코멘트 남겨주세요.

**Comment by sojung1418** [comment]
파생디자인 생성 개발완료 후 바로 개발진행예정

문서화 완료기한: 3/4(월)
개발 완료기한: 3/7(목)

**Comment by sojung1418** [comment]
3/4 개발 다시 시작하였습니다.

**Comment by eleutheria80** [comment]
@sojung1418 현재 진행 사항을 코멘트로 남겨주세요.

**Comment by sojung1418** [comment]
진행사항이 많지 않아 3/6(수)에는 '파생디자인 생성' 까지만 완료로 보여드릴 수 있습니다.
'파생 디자인의 원본 보기'는 개발기한을 늘여야할 것 같아서 3/6회의 이후 바로 개발완료기한 다시 잡도록 하겠습니다.

**Comment by sojung1418** [comment]
파생디자인 생성'의 기한이 미루어져서 3/6(수) 이후로 완료기한을 늦춰야합니다.
3/6(수) 이전까지 개발 완료기한 다시 잡겠습니다.

**Comment by eleutheria80** [comment]
@sojung1418 1차 개발에는 포함되지 않는 기능이니 테스트 기한 염두에 두고 일정을 정해주세요. 최대한 빠르고 정확하게, 더는 일정 변경없이.
@opensrcdesign-admin 2차 개발 라벨 붙여주시고 마일스톤도 변경 해 주세요.

**Comment by ggamsang** [comment]
https://opensrcdesign.com/designDetail/2257 페이지에서 
"정보설계"보드 아래 "파생디자인"내용에 따라 아래와 같이 구현될 예정입니다.


백/프론트 | 구현내용
-- | --
프론트엔드 | 수정가능'의 경우 파생디자인생성'버튼을 표시한다.
프론트엔드 | [디자인 상세보기] 화면에서 '파생디자인생성'버튼을 클릭한다.
프론트엔드 | 생성요청함수를 호출하고, "로더"와 안내문이 있는 모달을 띄우고 대기한다.
백엔드 | "requestFork"가 발생하면 해당디자인을 조회하고 데이터를 변수에 저장한다.
백엔드 | 저장한 데이터를 조작한다.( 디자인제목, 카드제목에 "파생된"이라고 첨가한다.
백엔드 | 새로운 디자인을 생성하되 위의 저장된 데이터를 입력한다.
백엔드 | 위의 과정이 완료되면 프론트엔드로 새로운 디자인 아이디를 전송한다.
백엔드 | 위의 과정을 실패했을 시 프론트엔드로 메시지를 전송한다.
프론트엔드 | 백엔드로부터 실패 메시지를 받으면 안내창과 함계 이전 모달을 닫는다.
프론트엔드 | 백엔드로부터 완료메시지와 새로운 디자인 아이디를 받으면 해당디자인으로 화면이동을 한다.

*생성 시나리오에 의한 순서입니다.

**Comment by ggamsang** [comment]
원본보기 구현내용은 아래와 같습니다.

백/프론트 | 구현내용
-- | --
프론트엔드 | 디자인 상세보기 화면에서 parent_id값이 있으면 '원본보기'버튼을 표시한다.
프론트엔드 | 부모 디자인으로 화면이동을 한다. (designDetail/:parent_id)

**Comment by opensrcdesign-admin** [comment]
#72 에서 해당커밋머지하였으므로 해당이슈는 닫도록 하겠습니다.
