### ISSUE TITLE
[메인] 로그인 시 회원에 특화된 정보 제공

### ISSUE THREAD

**Issue by doeuncow** [kmu-crc/osd_front#75]
- 내 그룹, 내 디자인, 관심 디자인, 인기 디자인 순으로
- 인기 디자인만 세로 스크롤, 관리자가 50개 정도 지정할 수 있도록

**Comment by doeuncow** [comment]
#65 가 완료되어야 세로 스크롤을 적용할 수 있을 듯하다.

**Comment by opensrcdesign-admin** [comment]
선행조건으로 #65 이슈가 맞는지 다시확인바람!! ^ↀᴥↀ^

**Comment by doeuncow** [comment]
엇, 세로 스크롤을 가로 스크롤로 착각했습니당ㅎㅎ,,,,

Due Date : 02.18

**Comment by doeuncow** [comment]
기존 메인처럼 각 항목(인기 디자인을 제외한)을 4개씩만 보이게 할 지, 혹은 4개 이상이라면 모두 나타낼 것인지?

**Comment by doeuncow** [comment]
Due Date: 02.21

그룹 이슈 먼저 진행하여 이 이슈에 대해 아직 진행하지 못하였습니다.

**Comment by doeuncow** [comment]
내 그룹, 내 디자인, 관심 디자인은 가로스크롤 가능하게
인기디자인만 세로 스크롤

**Comment by doeuncow** [comment]
[behance  선별된 갤러리](https://www.behance.net/galleries) 참조

**Comment by doeuncow** [comment]
**내 그룹, 내 디자인, 관심 디자인** 목록들 가져오는 방식 확인 중! (지금까지 파악한 부분은 각 탭들이 {host} /MyPage/{value} 방식으로 sorting하여 가져오는 거로 보였음! 좀 더 정확히 파악하여 해당 이슈 진행하도록 하겠습니다!)

**인기 디자인**은 ScrollTopDesign 파일을 통하여 불러오는데 그대로 놔두어도 괜찮을 듯 합니다! 세로 스크롤 방식이며, 100개만 나타내는 것이 아니라 스크롤을 내릴 때마다 디자인들을 더 요청하여 나타냅니다! 
(교수님께서 이전에 말씀하신 것처럼 아마 인기디자인 테이블을 따로 만든 듯한데 드롭박스에 올라온 DB 테이블 표를 확인하고 다시 답변 달겠습니다!)

Due Date : 02.22

**Comment by opensrcdesign-admin** [comment]
내 그룹, 내 디자인 , 관심있는 디자인 리스트를 넘겨받아 디스플레이한다. 정혁으로부터

**Comment by doeuncow** [comment]
인기 디자인을 가져오는 것처럼 각 파일들(내 그룹, 내 디자인 , 관심있는 디자인)을 구성하도록 하겠습니다! 

* 인기 디자인 관련 파일 목록
1. containers/Commons/ScrollTopDesignContainer/ScrollTopDesignContainer.js
2. components/Commons/ScrollList
3. actions/Commons/TopList.js

* function
GetTopDesignListRequest()

**Comment by doeuncow** [comment]
현재 인기디자인을 참조하여 ScrollMyDesign 파일 생성 중입니다. 각 파일마다 바꿔야하는 명칭 및 참조하는 파일들이 달라 부분부분 확인하면서 진행중입니다. 에러 수정과 김정혁 연구원님께서 추후 생성해주실 리스트를 넘겨받는 것까지 테스트를 한다면 2월 중에 끝내기는 무리일 듯 합니다. 따라서 마감기한을 3월 4일 즈음으로 잡도록 하겠습니다.

**Comment by doeuncow** [comment]
우선순위 : A

**Comment by doeuncow** [comment]
MyDesignList.js
MyGroupList.js
MyLikeList.js 

파일을 생성하여 내부 코드 수정중입니다. 이것 또한 TopList.js파일 `GetMyDesignListRequest()`과 같이 함수를 이용하여 가져올 수 있도록 진행 중입니다. 내부 코드가 어느정도 정리되면 커밋하여 김정혁 연구원님과 진행하도록 하겠습니다.

Due Date : 03.04

**Comment by ggamsang** [comment]
@doeuncow 제 이슈(#88) 늦어질 것 같습니다😭. 
추천디자인은 이전대로 GetTopDesignListRequest 그냥 사용하시면 됩니다.
혹시 먼저 구현되어야 하는거 있으면 말씀해주시면 감사하겠습니다 :) 
예를 들면, 추천디자이너나 추천그룹이요?

**Comment by doeuncow** [comment]
메인 화면에 띄워야 하는 것이 
(기본) 추천 디자인
(로그인 시, 추가적으로) 내 그룹, 내 디자인, 내가 관심있는 디자인
입니다! 

> 추천 그룹은 #76 에서 GetTopGroupListRequest() 함수를 생성하였고, 이를 불러오도록 만들었는데 (기능은 GetTopDesignListRequest와 동일하게 만듦.) 기능 사용 부분까지 코드 수정하여 커밋하도록 하겠습니다.

메인에서는 '내 그룹, 내 디자인, 내가 관심있는 디자인'이 담겨있는 테이블이 생성되었으면 합니다! (현재 사용자 페이지에서는 내 디자인에서도 분류가 되어있어 이를 그대로 활용하기는 어려울 듯 합니다.) 
우선 이를 요청하는 파일은 생성 해둔 상태(위 MyDesignList.js, MyGroupList.js, MyLike.js)입니다. 오류 생성된 부분을 조금 수정하여 내일 커밋하도록 하겠습니다!

**Comment by eleutheria80** [comment]
@doeuncow 코멘트를 남긴 시간상으로 보면 완료 시점에 혼동이 있을 수 있습니다. 예상 일정은 확실한 날짜를 명시 해 주시기 바랍니다.

**Comment by doeuncow** [comment]
Due Date : 03.06 입니다. 

위에서 마이페이지에서 사용하는 함수GetMyDesignListRequest()를 그대로 쓰기 어려울 듯하다고 적었으나, 코드를 수정하면서 다시 살펴보니 사용 가능하게 바꿀 수 있을 듯 합니다.
 
현재 마이 페이지에서 사용 해당 함수들을 불러오는 것은 구현했습니다.
1) request의 url이 잘못된 것인지 등록된 작품들을 불러오는 데 실패하였습니다. 이 부분 조금 더 수정하면서 고치는 대로 다시 코멘트 남기도록 하겠습니다. 
2) 마이페이지에서도 내 디자인과 내가 속한 디자인 등 통합하는 것으로 알고 있어 추후 DB가 통합되었을 때 같이 수정하면 될 듯합니다.
3) 로그인을 확인하는 this.props.valid이 제대로 동작하지 않습니다. (어쩌면 1번의 문제 또한 이와 관련되어 있을 것으로 보입니다.)

**Comment by ggamsang** [comment]
2. 마이페이지에서도 내 디자인과 내가 속한 디자인 이 통합된다는 것은 가져올 때  백엔드측에서 mysql 에서 제공하는 join을 이용하면 추가적인 데이터베이스 통합은 필요해보이지 않습니다.  이것은 회의 때 이야기나눕시다.

**Comment by ggamsang** [comment]
정정, join 보다는 중첩select문을 이용하는 방식을 생각해보겠습니다.

**Comment by doeuncow** [comment]
네! 확인했습니다. :)

로그인 시, 내 그룹, 내 디자인, 내가 관심있는 디자인들이 보여지게끔 코드를 수정하였으나, token을 읽는 과정에서 오류가 있는 듯 합니다. 
`message : "jwt malformed"`

**Comment by ggamsang** [comment]
부모컴포넌트로부터 token잘 받았는지 확인해보세요 :) 
확인방법 console.log(this.props.token) 
또는 render( ............ this.props.token && 토큰있음! .......);

**Comment by doeuncow** [comment]
확인해보았더니 메인에서 부르는 this.props와 마이페이지에서 요청하는 this.props가 다릅니다.
메인에서 부르는 this.props에는 token이 없어 오류가 난 것으로 확인되는데 마이페이지에서 this.props.token을 가져오는 방법을 잘 모르겠습니다.
bind()를 사용하는 것 같은데 활용하는 방법 다시 확인하여 수정하겠습니다.

**Comment by doeuncow** [comment]
데이터들 디스플레이는 성공했습니다. CSS 작업만 남은 상태인데 마감기한 맞춰 끝낼 수 있습니다. (가로 스크롤이 되게끔)

> Due Date : 03.06

**Comment by doeuncow** [comment]
3월 6일 마감기한에 맞추어 끝내려했으나 몸살기운이 있어 불가피하게 일정을 딜레이시켰습니다.

> 단순히 CSS만 바꾸면 될 것이라 생각하였는데, 마이페이지에서 스크롤 내리는 방식이 똑같이 적용되어 마이페이지와 메인페이지를 구분하여 스크롤 방법을 다르게 하기위한 방법을 찾고 있습니다.

Due Date: 03.08

**Comment by doeuncow** [comment]
현재 
1) React-horizontal-scroll list방법
  - 마이페이지와 메인페이지를 구분해줄 수 있는 속성을 넘겨줌으로써 다르게 표현할 수 있다. 그런데 구분하는 속성에는 무엇이 있는가?
  - horizontal-scroll list에 있는 property와 scrolllist에서 사용한 infinitescrolllist의 property가 다른데 그래도 각 속성이 허용이 되는지 확인할 필요가 있다._

2) 3~4개 디스플레이 후, 버튼 클릭 시, 마이페이지로 이동하는 방법
  - 메인에서 내게 중요한 그룹, 디자인들만 확인할 수 있으며, 추가적인 정보를 원할 때에는 마이페이지로 이동하게끔 할 수 있다.
  - 메인에서 모든 것을 처리할 필요가 없으니 마이페이지로 이동하게끔 하는 것 나쁘지 않음.
