### ISSUE TITLE
[그룹] 그룹 화면 수정 

### ISSUE THREAD

**Issue by doeuncow** [kmu-crc/osd_front#76]
- 그룹(개수) 옆에 그룹등록, 오른쪽 정렬하여 최신순 인기순 버튼
- ​관리자가 지정하는 그룹이 먼저 표시될 수 있도록 (이 부분은 사용자 선택에 우선함)
​

**Comment by doeuncow** [comment]
* ​관리자가 지정하는 그룹이 먼저 표시될 수 있도록 (이 부분은 사용자 선택에 우선함)

사용자 선택이라는 것이 무슨 의미인지 파악되지 않습니다. 아예 관리자가 지정한 대로 모든 사용자에게 동일하게 표시되는 것이 아니라는 것인지 다시 말씀해주셨으면 합니다! :)

**Comment by kshahn** [comment]
사용자는 그룹을 최신순, 인기순 등으로 표시할 수 있지만, 처음 중요한 그룹들은 이에 영향 받지 않고 처음부분에 고정되어 표시되어야 한다는 얘기임.

**Comment by doeuncow** [comment]
그룹 화면 정확히 어디에 위치하면 좋을 지 디자인이 된 후에 작업하도록 하겠습니다.

관리자가 지정하는 그룹이 먼저 표시되도록 하려면 어떤 그룹을 선정할 것인지 알아야 가능할 듯 합니다.

위 두 사항이 해결되면, +2~3일 정도 하여 해결할 수 있을 듯 합니다.

**Comment by doeuncow** [comment]
일단 이정훈 학생이 디자인 한 것을 바탕으로 코드 수정하도록 하겠습니다.

Due Date : 02.15

**Comment by doeuncow** [comment]
금요일에 일정이 생겨 Due Date를 변경하도록 하겠습니다.
Due Date : 02.18

**Comment by doeuncow** [comment]
![2019-02-18 06-21-45](https://user-images.githubusercontent.com/30363239/52919401-7dedb080-3345-11e9-94c3-46bd9d189b35.png)

**Comment by doeuncow** [comment]
dropdown 방식으로 되어있는 부분을 버튼방식으로 바꿔야하며, 해당 정렬이 될 수 있도록 수정해야하는 부분은 semantic ui react를 살펴 다시 수정하도록 하겠습니다. 그리고 중요한 그룹이 먼저 표시되도록 해야하는데 이 부분은 DB를 확인한 후 진행하도록 하겠습니다.

**Comment by doeuncow** [comment]
Due Date : 02.25

**Comment by doeuncow** [comment]
업데이트순 -> 최신순
등록일순
좋아요순

버튼으로 변경

(진아학생 디자인 확인 후, 재수정. 기능만 우선적으로 변경하기. Dropdown -> 버튼)

**semantic ui react**

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/52941994-5a5e5080-33ad-11e9-9e5c-f2cfda69eb8f.png)
![image](https://user-images.githubusercontent.com/47623887/52941999-5e8a6e00-33ad-11e9-8a45-46b5b8816394.png)

디자인이 잘 됐다고 생각된 레이아웃 구성입니다. 비핸스는 모든 필터를 왼쪽 정렬하여 버튼을 구성했네요. 사용자가 훨씬 더 쉽게 사용할 것 같아서 레퍼런스를 올려 봅니다.
만약에 이걸 보셨을 때 이게 더 나으시다면 댓글 남겨 주세요!

-
일단 저희 오픈디자인 사이트의 버튼은 이렇게 구성하였습니다. 
(그룹 등록 버튼이 빠졌다고 가정 > 그룹 등록 버튼은 디자인 등록 버튼이랑 동일시)

![image](https://user-images.githubusercontent.com/47623887/52942232-f425fd80-33ad-11e9-98ef-34b9de612541.png)

아직 여백 레이아웃이 정립이 되지 않아서 부분만 올립니다!

![image](https://user-images.githubusercontent.com/47623887/52942657-b8d7fe80-33ae-11e9-8f2a-2c168fdc85a0.png)

더 필요한 것이 있으면 말씀해주세요 (제가 여기 알림이 안떠서.. 카톡도 괜찮습니다)

-

비핸스 레퍼런스 보시고 다른 의견이 있으시면 말씀해주세요!

**Comment by kshahn** [comment]
업데이트순 (== 최신순) : 제일 최근에 업데이트(수정/갱신)한 디자인이 먼저 오도록
등록일순 : 제일 최근에 등록한 디자인이 먼저 오도록
인기순 (== 좋아요순) : 제일 많은 좋아요 받은 디자인이 먼저 오도록

*Kwangsoo Hahn, Ph.D.*
Professor,
College of Computer Science, Kookmin University
Office: +82-2-910-4794     Mobile: 010-5282-4794
E-mail: kshahn@kookmin.ac.kr


2019년 2월 18일 (월) 오후 6:56, Jinakimm <notifications@github.com>님이 작성:

**Comment by doeuncow** [comment]
![GroupList](https://user-images.githubusercontent.com/30363239/53039452-99ca9100-34c2-11e9-89a0-d9e1df856a17.png)

일단 1차적으로 위 사진과 같이 수정했습니다! 확인해주세요~ 그룹 등록 버튼을 아직 교체하지 않아서 임시적으로 그룹 수 옆에 두었습니다!

그리고 Sorting부분을 수정하면서 다른 페이지들(Design, Designer, Search)도 함께 수정이 되었습니다! 확인해주세요! :)

**Comment by doeuncow** [comment]
@Jinakimm 

그리고 적어주신대로 디자인을 적용하였는데 노트북 그래픽 문제인지, 사진과 약간 다르게 나와 임의적으로 수정하였습니다. 

#ff0000 -> #E72327 (opensrcdesign 그룹 등록에 쓰인 색상과 달라서 그런지 눈에 익지 않음. 혹시 그걸 고려하고도 #ff0000색상으로 하신거라면 다시 말씀해주세요!)
서체 14pt -> 11px
border : 2px solid #E72327

그 외에는 적어주신 디자인대로 수정하였습니다!

**Comment by doeuncow** [comment]
![2019-02-20 04-15-24](https://user-images.githubusercontent.com/30363239/53041005-33e00880-34c6-11e9-8d66-8d58ea743bc2.png)
그룹 등록 버튼 다시 우측으로 옮겼습니다 ㅎㅎ

**Comment by Jinakimm** [comment]
색 문제는 지금 페이지 디자인을 리뉴얼하면서 바꾼거라 지금 현재 서버에 올라와있는 색과는 다를 수 있을 것 같습니다! 그럼 이건 나중에 ui 다루면서 한꺼번에 색 정립은 다시 하도록 하겠습니다.

**border : 2px solid #E72327**
제가 비활성화 stroke 를 1px로 적어놓았는데 혹시 2px로 하신 이유가 있으신가요? 

**서체 14pt -> 11px**
그리고 이건 제가 서체값을 px로 볼 수 없어서 그런데 어떻게 변환하신 건가요?
![image](https://user-images.githubusercontent.com/47623887/53083268-ea350380-3541-11e9-865a-cb777bfcc504.png)
검색해 보니까 이렇게 뜨네요ㅠㅠ 
정확하게 측정할 수 있는 방법을 알려주시면 감사하겠습니다!

**Comment by doeuncow** [comment]
**border : 2px solid #E72327**
**제가 비활성화 stroke 를 1px로 적어놓았는데 혹시 2px로 하신 이유가 있으신가요?**
아 제가 stroke 설정을 어떻게 하는지 몰랐었어서 border에 다 넣었었는데 적용이 안되어서 최대한 비슷하게 표현을 하다보니 2px로 바꿨었습니다! develop 및 master 코드에 현재 변경사항이 업데이트 된 후에 수정하겠습니다! :)

**서체 14pt -> 11px**
**그리고 이건 제가 서체값을 px로 볼 수 없어서 그런데 어떻게 변환하신 건가요?**
14pt로 넣었더니 설정했던 버튼 박스 크기를 초과하여 텍스트가 입력되어 박스에 맞게 글씨 사이즈를 줄여두었습니다! (pt로 했었어야했는데 다른 부분들을 수정하면서 px를 자주 사용했더니 이 단위로 맞춰버렸습니다....;; )

**Comment by doeuncow** [comment]
검색해보니 stroke 설정은 svg 파일로 되어있는 도형같은 경우에 적용하는 것이더라구요! 얘는 버튼이라는 태그로 만들어진 사각형이라 border로 처리를 해야 디자인이 들어가는 것 같아요! 회의에서 말씀하셨던대로 외곽선이 좀 더 얇아야 한다 하셔서 border 두께를 1px로 변경하여 수정했습니다! :)

**Comment by doeuncow** [comment]
* ​관리자가 지정하는 그룹이 먼저 표시될 수 있도록 (이 부분은 사용자 선택에 우선함) :: 처음 중요한 그룹들은 이에 영향 받지 않고 처음부분에 고정되어 표시되어야 한다는 얘기.

아직 이 문제가 남아있음. 추천 디자인처럼 리스트를 불러오는 함수가 있다는 가정 하에 작업하도록 하겠습니다.
메인 페이지의 내 그룹, 내 디자인, 관심있는 디자인 불러오는 것과 비슷한 문제로 보입니다!

Due Date: 02.25

**Comment by Jinakimm** [comment]
네 감사합니다!

![image](https://user-images.githubusercontent.com/47623887/53218868-23d05080-36a1-11e9-8346-8345603494dc.png)
제 노트북에서는 이렇게 보여서요ㅠㅠ 혹시 몰라서 올려봅니다!

**Comment by doeuncow** [comment]
수정한 버전이 아직 사이트 코드에 통합이 안된것 같아요! 글씨가 초과되는 문제는 아무래도 해상도 차이로 생긴것 같은데 이것도 보완해야할 것 같네요ㅠㅠ
한가지 생각한 방법은 아예 최신순, 등록일순, 좋아요순 각각의 버튼 이미지를 만들어 그 이미지를 붙이는 것은 어떨까 싶은데 어떻게 생각하시나요? @Jinakimm

**Comment by Jinakimm** [comment]
그것도 좋은 방법인 것 같아요! 여기에 이렇게 올려드리면 되나요?

![on_new](https://user-images.githubusercontent.com/47623887/53279728-630ca900-3756-11e9-8ff5-174a177e83ec.png)
![on_update](https://user-images.githubusercontent.com/47623887/53279732-63a53f80-3756-11e9-842f-2b8ea9a4e96d.png)
![on_like](https://user-images.githubusercontent.com/47623887/53279733-63a53f80-3756-11e9-9c1d-e7bb5e4933c3.png)
![off_like](https://user-images.githubusercontent.com/47623887/53279734-63a53f80-3756-11e9-91f5-6efda2e276cd.png)
![off_new](https://user-images.githubusercontent.com/47623887/53279735-643dd600-3756-11e9-993e-a55577f9c6e2.png)
![off_update](https://user-images.githubusercontent.com/47623887/53279736-643dd600-3756-11e9-8efd-524e48273db8.png)

근데 앞으로도 뭔가 도형 안에 넣는 게 많을텐데 계속 이렇게 해야 하는지 고민이네요ㅠㅠ 
해결 방법 찾으시면 말씀해주세요!

**Comment by doeuncow** [comment]
지금 확인했는데 최신순, 등록일순, 좋아요순으로 써주셔야할 것 같아요! 최신순이랑 업데이트순은 같은 의미!

**Comment by doeuncow** [comment]
이미지로 넣는 것도 결국 크기 조절이 필요할 것 같아요! 

+테스트 환경에서 적용해보려고 했는데 URL을 잘못 적어서 그런건지 화면에 이미지가 안 뜨더라구요ㅠㅠ 이미지 아이콘만 뜨고,,,해상도 별로 확인하면서 조정하는 과정을 가지는 게 좋을 듯 합니다!

**Comment by Jinakimm** [comment]
엑 그러면 해상도를 어느정도로 할까요!? 하긴 작은 버튼이니까 좀 낮은 게 더 빠르겠죠..?

**Comment by Jinakimm** [comment]
이정도 해상도는 어떤가요?
일단 등록일 순으로 바꾼 것만 다시 올려볼게요! 그리고 이게 적용이 잘 되면 나머지 올리겠습니다

![on_update](https://user-images.githubusercontent.com/47623887/53301476-abcb7b80-3896-11e9-9615-5360bc881c62.png)
![off_update](https://user-images.githubusercontent.com/47623887/53301477-abcb7b80-3896-11e9-810a-80ca686d77f5.png)

그리구 저는 이제 잘거라,, 아마 지금부터는 연락이 안될 것같아용,, 내일 봬요ㅎㅎ

**Comment by doeuncow** [comment]
앗 제가 말씀드리려고 한거는 이미지로 안쓰고, 해상도별로 코드에서 수정하는 걸 말씀드린거에요! 
이미지 URL을 제가 잘못 쓴건지 이미지가 안 읽히기도 하고, 화면별로 보면서 수정하는게 좀 더 편할 것 같아요! ㅎㅎ 괜히 등록일순 이미지까지 만들도록 한것 같아 죄송합니다ㅠㅠ 안녕히 주무시고 내일 뵈요! :)

**Comment by doeuncow** [comment]
워딩변경 : 좋아요순 -> 인기순, 등록일순 -> 등록순

**Comment by doeuncow** [comment]
워딩변경 : 좋아요순 -> 인기순, 등록일순 -> 등록순
:: Due Date : 02.26
--------------------------------------------------------------------
•​관리자가 지정하는 그룹이 먼저 표시될 수 있도록 (이 부분은 사용자 선택에 우선함) :: 처음 중요한 그룹들은 이에 영향 받지 않고 처음부분에 고정되어 표시되어야 한다는 얘기.

아직 이 문제가 남아있음.

1.추천 디자인처럼 리스트를 불러오는 함수가 있다는 가정 하에 작업하도록 하겠습니다.
메인 페이지의 내 그룹, 내 디자인, 관심있는 디자인 불러오는 것과 비슷한 문제로 보입니다!

2.혹은 디비 그룹 테이블에 (생성된 그룹 기준으로)각 그룹마다 priority_flag를 세워 해당 표시가 있는 그룹들을 우선으로 띄울 수 있게 하는 방법은 어떨지...?

Due Date: 02.28

**Comment by doeuncow** [comment]
+ 추가적인 문제 :
특정 그룹에 들어가면 현재 정렬방법 하이라이트가 안되어있음.

**Comment by doeuncow** [comment]
P. 특정 그룹에 들어가면 현재 정렬방법 하이라이트가 안되어있음.
A. Groups/CurrentJoinListNew.js 해당 파일에 정렬을 시키는 함수명이 잘못 적혀있었다. handlechange -> handleClick. 드롭박스 방식에서 버튼 방식으로 바꾸었기에 이전 함수를 쓰는 부분을 모두 고쳤어야했는데 수정하는 과정에서 놓쳤다. 

P. 워딩변경 : 좋아요순 -> 인기순, 등록일순 -> 등록순
A. 버튼 내 워딩을 변경하였다.

**Comment by doeuncow** [comment]
​관리자가 지정하는 그룹이 먼저 표시될 수 있도록 (이 부분은 사용자 선택에 우선함) :: 처음 중요한 그룹들은 이에 영향 받지 않고 처음부분에 고정되어 표시되어야 한다는 얘기.

1.추천 디자인처럼 리스트를 불러오는 함수가 있다는 가정 하에 작업하도록 하겠습니다.

:: TopList.js에 탑 디자인이나 탑 디자이너를 불러오는 것처럼 함수를 만들었으며, 그 함수를 적용하는 코드를 작성중이다. 이 부분도 김정혁 연구원님께서 리스트를 넘겨주신다는 가정 하에 작업한 것이라 협업이 필요할 듯 하다. 현재 함수 추가한 부분만 커밋하여 확인할 수 있도록 하겠습니다. @ggamsang

**Comment by eleutheria80** [comment]
@doeuncow 완료일자가 다가오는데 현재까지 진행 사항 공유 해 주세요.

**Comment by doeuncow** [comment]
e1c485e51a2d677b209c07a9b1519c2bb73fa1bd

**Comment by ggamsang** [comment]
탑 그룹에 대해서도 라우팅 했습니다.
<img width="1647" alt="screen shot 2019-03-06 at 12 17 20 am" src="https://user-images.githubusercontent.com/28895134/53815688-72d18c00-3fa5-11e9-9018-be7981e76a58.png">
위와 같이 요청하면 해당결과를 받을수 있는 것을 확인하실수 있습니다. 이를보고 패치함수 내에 들어갈 url경로를 정하실수 있을 거 같습니다.  
논의되어야 할 사항은 "탑그룹과 일반그룹을 동시에 표시하게 될 때, 무한 스크롤이 잘 작동할까"입니다.

**Comment by doeuncow** [comment]
패치함수 내 URL경로를     
`export function GetTopGroupListRequest(page)`
` { return (dispatch) => `
` { return fetch(${host}/group/topGroupList/1/like)`

과 같이 테스트용으로 시도했는데 console에서 확인하면, 해당 링크가 없는 것으로 나타납니다. 그러나 주소창에 직접 입력하여 확인하면, 해당 그룹들이 뜹니다...
> `GET http://localhost:8080/group/topGroupList/1/like 404 (Not Found)` : 에러 메세지

-------------------------

안그래도 그룹 수가 많아진다면, 무한 스크롤로 인해 그룹들을 확인하는데에도 문제가 있다고 생각됩니다.
DB에서 우선 그룹에 flag를 세워 체크된 그룹들만 우선적으로 나타내게끔 할 수는 없을까요?
@ggamsang

**Comment by ggamsang** [comment]
@doeuncow 저번 회의시간에 추천그룹과 일반그룹을 한 번에 출력하는 방법에 대해서 이야기된 바 있습니다.
추천그룹을 우선 출력하고 그 이후에 일반그룹을 출력하는데 이 방법은 백엔드에서
추천그룹을 select하고, 추천그룹을 제외한 일반그룹을 select하는 쿼리문을 작성해야할 듯 싶습니다. 우선, 머지하고 getTopGroupListRequest 를 사용해보고 알려드리도록하겠습니다.

**Comment by doeuncow** [comment]
확인했습니다.

**Comment by ggamsang** [comment]
topGroupList 는 우선 커맨트아웃 시켰습니다.
groupList 로 부터 topGroupList 를 가져옵니다.
변경된 백엔드 topGroupList 은 요청에 따라 탑그룹에 속하는 그룹먼저 그렇지 않은 그룹은 후에 출력하도록 변경하였습니다.

**Comment by ggamsang** [comment]
그룹 정렬하면 변화가 없어 보이는데 이유는 
"추천그룹 x 정렬옵션"이라 그러합니다.
정렬을 어떻게 할 것인지 논의되어야할 것으로 보입니다.

**Comment by doeuncow** [comment]
확인했습니다! 감사합니다. :)
