### ISSUE TITLE
[디자인 상세보기] 동영상 컨텐츠 바로 동작할 수 있도록

### ISSUE THREAD

**Issue by doeuncow** [kmu-crc/osd_front#78]
동영상 컨텐츠 바로 동작할 수 있도록 변경한다.

구버전 참조하면 됨.

현재는 파일을 다운로드하여 볼 수 있게 되어있다.

**Comment by doeuncow** [comment]
<video controls autoplay>

**Comment by doeuncow** [comment]
`<video width="640" height="360" controls="controls"> <source src="https://s3.ap-northeast-2.amazonaws.com/osd.uploads.com/uploads/981e9b84-fa16-448b-8f21-d0c211ac68db.mp4" type="video/mp4"> </video>`

**Comment by ggamsang** [comment]
:+1:

**Comment by doeuncow** [comment]
Due Date : 02.13

**Comment by doeuncow** [comment]
구버전 확인 결과, 동영상 파일이 새로운 탭으로 열려 재생됨.
레이어 단계에서 바로 열릴 수 있도록 변경하기

**Comment by doeuncow** [comment]
Due Date 변경 
기존 02.13 -> 02.12

**Comment by doeuncow** [comment]
이전 버전으로 바꾸어 테스트 하는 과정이 오래 걸려 Due Date 를 2.13으로 재변경함.

**Comment by doeuncow** [comment]
02.13  문제 해결함.

**Comment by doeuncow** [comment]
@opensrcdesign-admin 
issue 닫아주세요~!
