### ISSUE TITLE
[디자인 상세보기] 디자인정보 부분  레이아웃 개선

### ISSUE THREAD

**Issue by doeuncow** [kmu-crc/osd_front#79]
상단의 썸네일 이미지 부분 축소하여 프로젝트 컨텐츠가 보다 많이 표시될 수 있도록.

현재는 이미지가 안들어간 컨텐츠로 보았을 때, 세로 2.5개 정도 보인다.
이미지가 들어갔을 경우에는 이미지의 사이즈에 따라 다르다. 
이미지가 세로로 큰 이미지이면 1개도 다 안보인다.
(참고로, 단계는 4.2개 정도 보인다.)

**Comment by doeuncow** [comment]
상세보기 페이지 디자인에 따라 변경될 듯 하다.

**Comment by doeuncow** [comment]
상세보기 페이지 디자인에 따라 변경된 내용을 확인 후, 기한을 설정하도록 하겠습니다.

**Comment by doeuncow** [comment]
썸네일 축소하면서 상단에 있던 등록일자와 최근 업데이트 일자를 하단으로 내렸습니다. 이정훈 학생의 디자인을 참조하여 변경하였으며, 우선은 개발자 화면에 맞추어 조정하였습니다. 이미지를 참조해주세요. 추가적인 디자인 보완사항이 이루어질 경우에는 앞선 이슈 해결 후 진행하겠습니다.

**Comment by doeuncow** [comment]
![2019-02-18 03-57-11](https://user-images.githubusercontent.com/30363239/52917639-568ce880-3331-11e9-8817-b8864b489c46.png)

**Comment by doeuncow** [comment]
하단 컨텐츠가 기존 2.5개 -> 3개로 더 보이게 조정하였다.

**Comment by doeuncow** [comment]
Version Update
이정훈 학생 디자인 참조 & 해상도별 화면 디자인 변경.

Due Date : 02.21

**Comment by doeuncow** [comment]
파생디자인 보기는 아이콘에서 진행

:메뉴 버튼에 있는 내용도 버튼으로 따로 빼야함.

**Comment by doeuncow** [comment]
?? 왜 closed 된거죠?

**Comment by doeuncow** [comment]
아이콘 90도로 회전하였다. 
src/components/Designs/DesignDetail/DesignDetail.js

이미지 source file이 따로 있는 것이 아니라 semantic-ui-react에서 가져오는 Icon이므로 css에서 설정해줘야했다.

**Comment by doeuncow** [comment]
![2019-02-25 02-08-52](https://user-images.githubusercontent.com/30363239/53302530-539a7680-38a2-11e9-9f01-a64d23d99282.png)

이정훈 학생의 디자인 디테일 페이지 시안을 참조하였다. 
디자인 설명 칸에 불필요하게 있던 줄 하나를 없애는 등 사진과 같이 변경하였다. 
양 옆의 여백을 없앨지 어떻게 바꿀지 방향이 정해지지않아 내용이 굉장히 좁아보이는 편이다.

회의에서 확인 후, 계속해서 디자인이 업데이트 될 예정이기에 이 부분은 3월까지도 열어둬야할 이슈로 보인다.

**Comment by doeuncow** [comment]
설명 부분이 1000자 까지 표시가 되는데 현재 줄인칸을 오버하여 설명이 적혀있다. 설명을 1000자까지 모두 표시할것인지(디스플레이 영역을 늘려야함) 설명부분에 커서를 가져다두면 새로운 레이어가 뜨면서 잘린 설명도 디스플레이할지?

**Comment by doeuncow** [comment]
![2019-02-25 15-05-06](https://user-images.githubusercontent.com/30363239/53317386-c0e3f100-390e-11e9-83ed-31a3e0468ebc.png)
위 사진과 같은 문제가 있음.

**Comment by doeuncow** [comment]
3월에 새로 버전 업 시키면서 디자인 상세 페이지에 대한 것도 다루기로 함. 
이슈는 열어두되, 3월 회의를 진행하면서 관리하도록 한다.

**Comment by doeuncow** [comment]
3월에 디자인 상세 페이지 디자인을 새로 하시면서 관련 내용을 이쪽으로 업로드해주셨으면 하여 미리 태그해두도록 하겠습니다. @Jinakimm

**Comment by Jinakimm** [comment]
넵 알겠습니다!
