### ISSUE TITLE
[디자인 등록/수정] 기본 섬네일 제공 기능

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#85]
현재, 디자인을 등록할 때 thumbnail 등록은 필수요소.
사용자가  thumbnail 없는 경우를 대비해 기본 thumbnail 를 제공하는 기능을 추가한다.

매번 업로드하지말고, s3에 따로 폴더만들어서 관리하면 수정할때도 편리할 것이다.

**Comment by opensrcdesign-admin** [comment]
디자인팀과 기본 섬네일 선정한다.
디자인팀과 섬네일 선택하는 뷰에 대해서 논의 후 기능을 구현한다.
섬네일 등록을 하지 않으면 랜덤하게 지정해줄 것인지? 사용자가 선택할 수 있게 할 것인지... 등등

**Comment by eleutheria80** [comment]
@opensrcdesign-admin, @wwjdtm, @Jinakimm   현재 상태 코멘트 남겨주세요.

**Comment by Jinakimm** [comment]
썸네일은 디자이너 썸네일에 대해서 이야기를 나눴고 
기타 디자인 카드에 대한 썸네일은 아직 이야기해보지 않았습니다
디자이너 카드 썸네일은 3월달에 전체적인 디자인을 잡은 후에 컬러파렛트 선정하여 만들도록 하겠습니다
