### ISSUE TITLE
[기타] 댓글 기능 컴포넌트로 만들고 디자인개선

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#87]
디자인의 댓글 기능에서 댓글의 댓글 기능을 추가한다. 이때,  댓글의 depth는 +1 이다.

**Comment by ggamsang** [comment]
d_flag 컬럼을 이용한다. 이 컬럼에 해당댓글의 부모댓글의 uid를 넣어서 관리한다. 
d_flag 의 값이 없다면 부모댓글이 되는 것이다.
d_flag 의 값이 있다면, 그 값에 해당되는 자식댓글이 되는 것이다.

1. 댓글을 가져온다.
2. 가져온 댓글들을 출력하기 전에 트리구조로 만든다.
3. 댓글을 출력하는데 자식댓글이면 들여쓰기와 대댓글 이미지를 첨가 후 내용을 출력한다. 
4. 부모댓글에는 댓글달기 버튼을 출력한다.
5. 자식댓글에는 댓글달기 버튼을 감춘다.

위와 같이 구현할 예정이며,

완료시점은 **2월 25일**입니다.

**Comment by ggamsang** [comment]
- 현재까지사항.
- [x] 댓글을 가져온다.
- [x] 가져온 댓글들을 출력하기 전에 트리구조로 만든다.
- [x] 댓글을 출력하는데 자식댓글이면 들여쓰기
- [ ] 대댓글 이미지를 첨가 후 내용을 출력한다.
- [x] 부모댓글에는 댓글달기 버튼을 출력한다.
- [x] 자식댓글에는 댓글달기 버튼을 감춘다.

- 추가해야할 사항
- [ ] 댓글달기 클릭시 댓글입력창띄우기, 댓글입력버튼클릭시 서버에 전달
- [x] 댓글삭제시 : 대댓글있으면 막음

*컴포넌트만들었으면 좋았을걸,,, 정확히는 좀 더 쪼갰으면 좋았을 것을...ㅠ 담버젼에선 이리 안한데이

**Comment by ggamsang** [comment]
대댓글 기능 완료하였고, 계획과 다르게 버튼을 따로 두지않았다. 이유는 댓글달기버튼이 두개가 되기 때문이다.
댓글을 달고자한다면 댓글내용을 클릭하면 아래에 댓글입력창이 뜨도록 구현하였다.

**Comment by Jinakimm** [comment]
@Jinakimm

**Comment by opensrcdesign-admin** [comment]
http://justintadlock.com/blog/wp-content/uploads/2016/11/in-reply-to-003.png
https://goo.gl/images/gdP9XR
참고하세요.

**Comment by Jinakimm** [comment]
![img_3553](https://user-images.githubusercontent.com/47623887/53633233-42fb4f00-3c5a-11e9-8c90-b12d5dd161b0.PNG) 
![img_3554](https://user-images.githubusercontent.com/47623887/53633235-4393e580-3c5a-11e9-86e6-706cb8eaf25a.PNG)
![img_3561](https://user-images.githubusercontent.com/47623887/53633236-4393e580-3c5a-11e9-9a82-5ebbfcb95469.PNG)

1. 댓글달기 버튼은 사용자가 볼 수 있게 명시한다 (댓글 창 아래에)
2. 날짜도 댓글달기 옆으로 옮긴다
3. 댓글을 달았을 때, 누구한테 속한 댓글인지 명시해주는 태그 @김진아를 만들어서 명시한다 (색: #ff0000)
4. 사용자 닉네임을 누르면 3번째 사진 처럼 사용자페이지로 가는 버튼이나, 신고하기 버튼을 만든다
 (이런 버튼을 만들지 않을 거라면 마우스오버했을 때 활성화되는 것을 아예 다 없앤다)

**Comment by eleutheria80** [comment]
@ggamsang 디자인 제안이 등록되어습니다. 검토 후 코멘트 남겨주세요.

**Comment by opensrcdesign-admin** [comment]
@eleutheria80 제안에 맞게 구현할 예정입니다.

**Comment by Jinakimm** [comment]
<img src = "https://user-images.githubusercontent.com/47623887/53870312-58e38800-403d-11e9-9150-e31eb669ecee.PNG" width= "50%">
<img src = "https://user-images.githubusercontent.com/47623887/53870314-597c1e80-403d-11e9-94a8-2061466e8bc4.PNG" width= "50%">
<img src = "https://user-images.githubusercontent.com/47623887/53870317-597c1e80-403d-11e9-8847-aa6b7f2a8ee9.PNG" width= "50%">

**Comment by opensrcdesign-admin** [comment]
@Jinakimm 소중한개인정보?! 감사합니다. 혹시나 해서 가렸습니다. 제가 참고할때만 표시하도록 하겠습니다.

**Comment by opensrcdesign-admin** [comment]
(방법 3.) 댓글 옆에 답글 달기 버튼을 생성. 클릭 시, 답글을 작성할 수 있는 텍스트 창이 뜬다. 입력 창 하단에 저장 취소 버튼 추가
 '답글 달기'의 버튼 위치. Fold할 필요는 없다. '댓글 쓰기' 버튼 -> '저장'버튼 과 '취소'버튼으로 변경. 게시 날짜는 업데이트 일자로 바꾸어 (ex. 1분전) 나타내기.

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/53891032-c824a080-406c-11e9-8011-180cbb3d2d1a.png)
![image](https://user-images.githubusercontent.com/47623887/53891054-d2df3580-406c-11e9-99ab-13473f16aff6.png)
![image](https://user-images.githubusercontent.com/47623887/53891117-fbffc600-406c-11e9-87a0-ece11b1344c9.png)

다른 사이트들을 보니까 "게시"라는 단어를 사용하네요!
순서대로 인스타그램, 페이스북, 비핸스입니다

**Comment by Jinakimm** [comment]
/
**아직 디자인이 확정된 것이 아니라 댓글 기능만 참고해주세요!**
**빨리 보여드려야 할 것 같아서 뼈대만 빨리 작업했습니다. 간격이나 세부 디테일, 그리고 인터페이스 디자인은 나중에 시간을 오래 갖고 올리겠습니다**
/
/
/
/
클릭해서 봐주세요!
/
저장이랑 게시 중에 일단 "게시"로 작업하였습니다. 추후에 바꿔야한다면 바꾸겠습니다!

![1](https://user-images.githubusercontent.com/47623887/53893006-b513cf80-4070-11e9-9707-74b81a017730.jpg)

**Comment by ggamsang** [comment]
넵, "게시"로 우선 구현해보고 안되면 다른 단어로도 해봅시다.

해당이슈도 일정변경하고자합니다.
완료시점은 **3월11일**입니다.

**Comment by ggamsang** [comment]
![Screenshot from 2019-03-12 20-21-43](https://user-images.githubusercontent.com/28895134/54196363-94ca9180-4504-11e9-833d-ae44a433fc66.png)
![Screenshot from 2019-03-12 20-21-51](https://user-images.githubusercontent.com/28895134/54196368-972ceb80-4504-11e9-822c-ba57cb0ec11e.png)

**Comment by ggamsang** [comment]
다른 곳에서 사용되는 댓글도 이와같이 변경할 계획이며, 이는 2차개발때 새로운 이슈만들어서 진행하도록 하겠습니다.

**Comment by Jinakimm** [comment]
세부디자인은 나중에 어느정도 틀 잡히면 차근차근 맞춰가도록 하겠습니다!
지금은 아직 전체 여백도 불분명해서요ㅠ
