### ISSUE TITLE
[관리자 앱] 별도의 관리자앱에서 추천그룹/디자인 선정기능구현

### ISSUE THREAD

**Issue by ggamsang** [kmu-crc/osd_front#88]
관리자에게 메인에 표시되는 디자인의 순서를 변경할 수 있는 기능을 제공한다.

**Comment by ggamsang** [comment]
@wwjdtm님 Unsubsribe 누르세요.

**Comment by ggamsang** [comment]
[이 이슈는 아래와 같이 진행할 예정]
파악한 결과 현재 top_design테이블통해 목록가져온다. design테이블과 연동되어 있지않은것도 확인.
새로운 테이블을 만든다. hot 이며 각각 uid, id, type으로 구성된 테이블이다.
- 관리자
1) 관리자계정은 오픈소스디자인/admin/main 에 접속하여, 로그인하도록한다.
2) 일반계정은 접속하지 못하게한다.
3) /main/hotdesign 페이지생성
4) 해당페이지를 아래와 같이 보여준다.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
[추천그룹목록] 그룹정보나열 [내리기버튼] 
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
[일반그룹목록] 그룹정보나열 [올리기버튼]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
*일반그룹목록: 추천그룹외에 모든 그룹목록
내리기버튼 hot테이블에서 제거
올리기버튼 hot테이블에 추가
버튼 누르때마다 요청, 변경된 데이터가져와서 다시 출력
바뀐정보만 리랜더링하기때문에 깜박이거나하지않음.
**이하 디자인과 디자이너 동일하게.

- 비관리자(일반유저)
#107 에 맞게 표시한다.

due date: 02.28

**Comment by eleutheria80** [comment]
@ggamsang 28일 완료 예정인데 진행 사항 남겨주세요.

**Comment by ggamsang** [comment]
관리자용 테이블 생성함.

**Comment by ggamsang** [comment]
진행중
![screenshot from 2019-02-28 11-38-27](https://user-images.githubusercontent.com/28895134/53537470-6be1ee00-3b4d-11e9-88ba-acb341fbd5ca.png)
현재는 데이터베이스를 구성하면 해당하는 디자인을 찾아서 전달하는 방식으로 구현 중.

**Comment by ggamsang** [comment]
일정변경: 개강전까지! 대신 doeuncow 업무차질없도록
due date: 03. 03

todo:
- [ ] : adminpage(auth*)
- [ ] : collect func. in front(view)
- [ ] : collect func. in back(action)
항목생기면 추가하겠음.

**Comment by opensrcdesign-admin** [comment]
회의시간에 이야기한대로 테이블은 각각 만들어서 관리하길 바랍니다.

**Comment by ggamsang** [comment]
-진행사항
done) 각 테이블 만들었고 그중 디자인테이블은 이전과 같은 디자인들로 우선 구성하였음.
done) 백엔드 쿼리부분만 수정하여서 프론트엔드에서는 toplist를 이전과 동일하게 사용하면 추천 디자인을 받을 수 있음.
todo) 그룹과 디자이너에 대해서 추가하도록 하겠음.
todo) 추천관련 테이블 조작가능한 유저인터페이스***
todo) 관리자 로그인

-일정조정
일정변경 - 3월 8일
사유 - 파일업로드/다운로드 파일이름 인코딩문제, 프로토콜(사이트접속관련 및 아마존설정)문제 파악 및 해결 중으로 미뤄짐.

- 협업관련
doeuncow 일정에는 문제없을것으로 판단되나 별로 물어봐야할 듯.

**Comment by ggamsang** [comment]
개발 중 질문 사항 - 추천 디자이너 목록 가져오는데 카테고리에 따라 분류해야하는지? 
우선 분류없이 가져오는 것으로 구현 중.

**Comment by ggamsang** [comment]
- 진행사항
~~done) 각 테이블 만들었고 그중 디자인테이블은 이전과 같은 디자인들로 우선 구성하였음.~~
~~done) 백엔드 쿼리부분만 수정하여서 프론트엔드에서는 toplist를 이전과 동일하게 사용하면 추천 디자인을 받을 수 있음.~~
done) 그룹과 디자이너에 대해서 추가하도록 하겠음.
todo) 추천관련 테이블 조작가능한 유저인터페이스***
todo) 관리자 로그인

**Comment by ggamsang** [comment]
사용자인증 코드부분 분석 중입니다.

**Comment by opensrcdesign-admin** [comment]
- "순서변경" 이슈에 사용되었던 기능들을 이용하면 UI 및 그룹 및 디자인 순서 변경하는 기능은 빠르게 만들수있을것으로보임.
- 인증부분은 "정보통신처"이슈에서 말했듯이 일반사용자와 관리자가 분리되어야한다. 
- 우선순위가 높은 이슈이므포 풀테스트기간동안 완성할 것.

**Comment by ggamsang** [comment]
> 그룹관리자
![Screenshot from 2019-03-15 20-48-35](https://user-images.githubusercontent.com/28895134/54429415-d147f880-4763-11e9-9a7e-82e15aae0b7f.png)

 - ~순서변경기능~ :ballot_box_with_check: 
 - 그룹 가져오기 
 - ~그룹 분류하기~:ballot_box_with_check:  :information_source: 내부 json데이터로 우선 구현 중
 - 디비변경 요청 :arrow_backward: 현재 진행 중
 - 레이아웃 및 디자인 개선!!!!!
 - 백엔드: 요청처리
 - 관리자인증
 - 백엔드: 관리자인증
 - 디버깅

**Comment by ggamsang** [comment]
> 그룹관리자

 - :ballot_box_with_check:  ~순서변경기능~
 - :ballot_box_with_check:  ~그룹 가져오기~
 - :ballot_box_with_check:  ~그룹 분류하기~
 - :ballot_box_with_check:  ~디비변경 요청~ 
 - 레이아웃 및 디자인 개선**!!!!! 
 - :ballot_box_with_check:  ~백엔드: 요청처리~
 - 프론트엔드: 관리자인증 :information_source: 현재는 일반사용자로 로그인해서 하고있음,토큰때문에...:arrow_backward: next
 - 백엔드: 관리자인증 :arrow_backward: next
 - 디버깅

:information_source: 관리자모드는 리덕스를 사용하지않고 구현하고 있음.

**Comment by ggamsang** [comment]
그룹관리자
---

 - :ballot_box_with_check:  ~순서변경기능~
 - :ballot_box_with_check:  ~그룹 가져오기~
 - :ballot_box_with_check:  ~그룹 분류하기~
 - :ballot_box_with_check:  ~디비변경 요청~ 
 - 레이아웃 및 디자인 개선**!!!!! 
 - :ballot_box_with_check:  ~백엔드: 요청처리~
 - :ballot_box_with_check:~프론트엔드: 관리자인증~
 - :ballot_box_with_check:~백엔드: 관리자인증~
 - 코드개선 및 디버깅

:information_source: 관리자모드는 리덕스를 사용하지않고 구현하고 있음. 
:heavy_plus_sign: 인증부분은 리덕스 그대로 사용, 계속 유지해야하기위해서다.

**Comment by opensrcdesign-admin** [comment]
관리자앱을 독립적으로 구현합니다.
우선, 인기그룹 및 추천디자인의 목록과 순서를 변경할 수 있는 기능을 구현합니다.

**Comment by ggamsang** [comment]
완료시점: **5월29일**
구현할 내용
1. 독립적인 관리자앱
2. 백엔드에 접근
3. 공지사항 테이블 작성
4. 공지사항 기능추가
5. 디자인관리페이지 -추천디자인 선정기능  (구현되어 있는거 참고하며 진행할 예정)
6. 그룹관리페이지 - 인기그룹 선정기능 (구현되어 있는 거 참고하며 진행할 예정)

**Comment by ggamsang** [comment]
우선, 131에서 개발테스트하고, 아마존서버에는 논의 후 업로드할 예정입니ㄷㅏ.
도메인지정에 대해서 논의가 필요할 것으로 보입니다.

**Comment by ggamsang** [comment]
2개 테이블 생성
공지사항 레코드 저장 테이블
공지사항 상세내용 레코드 저장 테이블(디자인 컨텐츠와 유사)

테이블작성
CREATE TABLE IF NOT EXISTS `notice`(
`uid` int(11) NOT NULL AUTO_INCREMENT,
`type` int1 DEFAULT NULL,
`content` longtext,
`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`expiry_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=24924 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `notice_content`(
`uid` int(11) NOT NULL AUTO_INCREMENT,
`notice_id` int(11) DEFAULT NULL,
`content` longtext,
`type` varchar(100) DEFAULT NULL,
`data_type` varchar(100) DEFAULT NULL,
`extension` varchar(100) DEFAULT NULL,
`order` int(11) DEFAULT NULL,
`file_name` varchar(500) DEFAULT NULL,
`create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`uid`),
KEY `notice_content_notice_id_idx` (`notice_id`),
CONSTRAINT `notice_content_notice_id` FOREIGN KEY (`notice_id`) 
REFERENCES `notice` (`uid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=24924 DEFAULT CHARSET=utf8

**Comment by ggamsang** [comment]
진행사항
1)
![Screenshot from 2019-05-28 20-18-33](https://user-images.githubusercontent.com/28895134/58474344-cb1fc080-8185-11e9-8a48-77007fc72c56.png)

**Comment by opensrcdesign-admin** [comment]
notice 기능까지 구현하고 해당이슈닫는 것으로 하겠습니다.

**Comment by ggamsang** [comment]
기한연장하겠습니다. 31일까지

**Comment by opensrcdesign-admin** [comment]
우선, 최소한의 기능을 구현이 완료되어 크로즈합니다.
향후 어떤 기능을 추가할지에 대한 논의가 필요합니다.
