### ISSUE TITLE
[디자인 상세보기] 파일 다운로드 시 파일명 그대로 다운로드 될 수 있도록

### ISSUE THREAD

**Issue by doeuncow** [kmu-crc/osd_front#94]
현재는 파일을 다운로드하면, 어떤 파일형식이든 숫자로 변환되어 다운로드 된다. 파일명 그대로 다운로드 받을 수 있도록 변경해야한다.

**Comment by opensrcdesign-admin** [comment]
<a href="{s3주소}" download="저장할이름">...</a> 와 같이 수정하면되지만, s3버킷에 설정이 필요함.
s3버킷의 모든파일들에 대해 메타데이터를 입력해야함.
s3버킷에 데이터를 업로드할 때 메타데이터도 추가하여 업로드하도록 코드수정해야함(백엔드에 이슈만들것)

**Comment by doeuncow** [comment]
백엔드 이슈라고 적혀있는 점 + ...이라고 적혀있어 어떻게 수정해야하는지 잘 모르겠습니다ㅠㅠ
구현 방법 대강 살펴보았을 때에는 php 파일로 새로 만들어야할 것 같습니다.

적용시킬 수 있는 기능인지 아직 살펴 보는 중이라 기간을 넉넉히 잡도록 하겠습니다.

Due Date : 02.28

**Comment by opensrcdesign-admin** [comment]
추가
### 프론트엔드에서는
... 내용은  < a href="{s3주소}" _download="저장할이름"_>...</a > 와 같으며 이는 프론트엔드 내 컨텐츠를 표시하는 곳에 이미 < a> 태그가 있고, download를 추가하면 된다고 알고있습니다.

### 백엔드에서는
s3와 연결하여 전달받은 데이터를 업로드하는 곳이 있습니다.
그곳에 ContentDisposition 메타데이터를 추가해주어야합니다. 
관련 내용은 
https://stackoverflow.com/questions/40718782/s3-set-file-name-on-upload
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

* php를 이용하지 않아도 됩니다 :) aws-sdk는 자바스크립트도 지원합니당ㅋ
* 백엔드부분은 해당저장소에 이슈만들어서 진행하도록 합시다.

살펴보시고 추가할 내용이 있으면 코멘트 달아주세요.

**Comment by doeuncow** [comment]
헉ㅋㅋㅋㅋ 감사합니다. 확인하겠습니다 :)

**Comment by doeuncow** [comment]
frontend 부분 수정

Due Date : 02.21

**Comment by doeuncow** [comment]
< a href="{s3주소}" _download="저장할이름"_>
인 곳이 소스 수정/삭제로 보이는 곳에서 발견하였는데 이 부분이 아닌 듯하여 다시 재 탐색 중입니다.

**Comment by opensrcdesign-admin** [comment]
서버측에서 텍스트이름으로 보내줄것

**Comment by ggamsang** [comment]
백엔드부분 코드수정완료하였습니다. 테스트도 해봤는데 원래파일이름대로 다운로드하는 거 확인했습니다!

@doeuncow 위에서 제가 조금 잘못알려드린 것은 < a key={index} href={item.content} 라고 알려드렸으면 금방 찾으실수 있었네요ㅠ 위에서 말한대로 고치시고 테스트해보세욤. 
(백엔드 다시 끌어온다음에 혹은 npm run-script start하셔도 바로테스트하셔도 됩니다.)

참고1
  교수님께서 제안한 방법은 ec2에서 바로 다운받는 방법으로 ec2에 데이터를 가지고 있어야 합니다. 
이는 s3에 데이터를 모두 저장하는 현 시스템 관점으로 봤을 때 데이터를 두 곳에 데이터를 보관하게 되는 것이고,
관리면에서 불편함이 있을 것 같습니다. 또한 s3를 사용하는 이유는 속도개선을 위해서이기도 합니다.

참고2
  지금 이 방법대로 하면 정상동작하지만 문제는 이전에 올려둔 파일들에 대해서는 다운로드하면 예전과 같은 상황이 발생합니다. 이는 이전에 올려둔 파일에는 메타데이터가 없기 때문입니다.
이미 올라간 파일에 대한 메타데이터입력이 필요합니다. 문제는 량이 무지하게 많다는데 있습니다.
매크로나 이 문제만을 처리하기 위한 스크립트를 작성하는 방법이 있겠습니다. 이에 대해서 추후에 업데이트 하겠습니다.

**Comment by doeuncow** [comment]
해당 부분 코드는 고쳤으나 

1. 백엔드 코드 업데이트 후,  로컬에서 테스트 -> 새로운 파일이 등록이 안되고 로딩화면만 계속됨.
2. 테스트 서버 환경에서 확인하려 했으나, 디자인 리스트 디비가 보이지 않아 확인불가 상태.

위 두가지 환경에서 테스트가 되지 않아 정확히 작동하는지 확인불가입니다.ㅠㅠㅠ

고친 코드 /opendesign/front/src/components/Designs/CardSourceDetail.js
item.type==="FILE"인 img, source, a tag 에 
`download={item.file_name}'`추가

**Comment by ggamsang** [comment]
머지했어요, 어제요... 너무 늦게 답장드려 죄송해요ㅠ 

이거 제가 실수했더라구요, 백엔드 코드고치고 적용을 안시켜서 테스트하시는데 고생하셨네요ㅠ 죄송해요. 귀한시간잡아먹어서... 테스트서버문제도 있군요 저거 확인하고 이슈업데이트해야겠네요.

무튼 지금은 정상동작합니다. 물론, @doeuncow 께서 올리신 텍스트파일엔 메타데이터가 적용되지 않아서 이름변경되지않고 다운받을거에요. 그 아래 카드에 제가 올린거는 이름그대로 다운받아요. 적용한 후에 올린 파일이라서요.

**Comment by doeuncow** [comment]
괜찮습니다! 고생하셨어요ㅠㅠ 확인했습니다! 정상적으로 다운로드 되는 것도 확인했구요! :)

**Comment by eleutheria80** [comment]
@doeuncow , @opensrcdesign-admin 이슈 완료일 경우 확인 후 완료 처리 해 주세요.

**Comment by opensrcdesign-admin** [comment]
현재시점으로 업로드하고 다운로드하면 파일이름대로 받으실수있습니다.

하지만, 이전에 업로드된 파일들은 그렇지 않습니다. 이에 대한 해결이 필요합니다. 

그 사항은 다른 이슈에서 하겠습니다.
