### ISSUE TITLE
[디자인 상세보기] 최근 업데이트 날자 갱신 기능

### ISSUE THREAD

**Issue by kshahn** [kmu-crc/osd_front#95]
단계에 포함된 컨텐츠들은 수정해도 업데이트 날자가 갱신되지 않음 ==> 갱신된 날자 반영하도록
디자인 자체의 최근 갱신일은 최근 갱신된 컨텐츠 갱신일로 바뀌어야 함
'최근 업데이트' 워딩도 '최근 갱신일자'로 하는게 나을 듯 함

**Comment by ggamsang** [comment]
@wwjdtm unsubscribe 누르세욤.

**Comment by ggamsang** [comment]
디자인 테이블에 update_time이라는 항목이 존재, 이를 업데이트해달라는 요청을 구현한다.

시간업데이트 요청을 해야할 시기는 
디자인 내 단계가 (1)추가, (2)수정되었을 때, 각 단계에서 카드가 (3)추가, (4)수정되었을 때가 있다.

// 이 이슈는 https://github.com/kmu-crc/osd_back/issues/6 와 연결된 이슈이다.

**Comment by ggamsang** [comment]
현재, 
카드, 보드 생성 시 '최근업데이트'값 업데이트됨.
앞으로,
수정에 대해서 적용하면 됨.

오늘 저녁중에 완료될 것. 
due date: 02.21

**Comment by ggamsang** [comment]
(듀데이트 초과해서) 완료했습니다. 에헤;;
자세한 변경내용은 아래에 링크했습니다.(내용이 많아서요..)
https://github.com/kmu-crc/osd_front/commit/86a9e4aeda93f337bbda4d9ddfaf252edaf5a0bd
https://github.com/kmu-crc/osd_front/commit/cb4a90d06476957523286718220b04dc760c6103
https://github.com/kmu-crc/osd_front/commit/832e869a039c4fc1eda65fabfb2fe56f03e75620

간단히 설명하면, 
1)디자인시간
백엔드: 요청이오면 design테이블 내 update_time의 값을 now()로 갱신한다.
프론트엔드: 요청하는 함수를 구현, 해당하는 부분마다 함수호출
*별도의 요청함수는 아래 카드 업데이트때문에 추가할 필요가 있었음.
2)카드시간
백엔드: 카드의 UPDATE쿼리가 수행되는 곳에 구문에 update_time=now()구문을 추가했음.
프론트엔드: 할일없음

**Comment by opensrcdesign-admin** [comment]
기능은 작동하나, 새로고침이 필요하다... 변경된 사항에 대해서 리랜더링 할 것!

**Comment by eleutheria80** [comment]
@opensrcdesign-admin 추가 수정이 필요한것 같은데 예상 일정 코멘트 남겨주세요.

**Comment by opensrcdesign-admin** [comment]
구현완료하였으므로 이슈 닫습니다.
