### ISSUE TITLE
[마이페이지] 화면 디자인 수정

### ISSUE THREAD

**Issue by kshahn** [kmu-crc/osd_front#97]
다음 정보를 순서대로 위에서 아래로 표시

(내 정보) - 여기에 현재 진행중인 멤버 초대 수 표함
(내 디자인 - 내가 속한 디자인 포함) 
(내 그룹)
(좋아요 - 디자인/그룹/디자이너 순으로)

**Comment by Jinakimm** [comment]
![-3](https://user-images.githubusercontent.com/47623887/52907773-a3c67700-32ab-11e9-9fc9-8fa9ae3fdea1.jpg)
![-32](https://user-images.githubusercontent.com/47623887/52907770-8abdc600-32ab-11e9-90db-248ca0ae63ab.jpg)
![-33](https://user-images.githubusercontent.com/47623887/52907771-8abdc600-32ab-11e9-8e5c-f19c91a0446b.jpg)

**Comment by Jinakimm** [comment]
1. 낭비되는 공간이 너무 많아 모든 페이지의 좌우 여백을 조정하였습니다. 좌우 60px
(나머지 페이지들은 추후에 업로드 하도록 하겠습니다.)
또한 접근성을 더 높이기 위해 버튼의 위치를 바꿨습니다. 
(검색 버튼과 디자인 등록하기 버튼)

2. 사용자가 혼란스러워 하지 않도록 명시된 버튼들의 언어 정립을 하였습니다.
참여 디자인 > 참여한 디자인 / 관심 디자인 > 관심있는 디자인

3. 등록된 디자인들의 디스플레이 크기를 확대하였습니다.

4. 행간은 line-height: pt;로 적어놓았습니다 다른 값이 필요하면 말씀해주세요

**Comment by Jinakimm** [comment]
![image](https://user-images.githubusercontent.com/47623887/52907848-33205a00-32ad-11e9-8f80-32c20ae99ebd.png)

3_1. 등록된 디자인들의 썸네일이 기본 비율에 맞지 않았을 때, 여백을 주게 하는 것 보다 사진을 확대하여 여백이 남지 않도록 해야할 것 같습니다.
썸네일의 목적은 프로젝트를 온전히 보여주는 것 보다 관심을 촉구하여 들어오도록 유도하는 것이기 때문에 나열된 프로젝트마다 다른 여백이 존재하고 그것이 눈에 보기 좋지 않으면 관심도가 현저히 떨어질 것으로 예상됩니다.

**Comment by Jinakimm** [comment]
// UX적인 측면은 계속 고민하고 있습니다. 

제가 처음 봤을 때 바로 생각났던 것들은
1.사람들에게 보여주기 위한 아카이브인지 자기들만의 기록용 아카이브인지의 정립 필요
> 전자의 경우(ex. behance / pinterest)라면 퍼스트 유저가 매력을 느낄 수 있을만한 썸네일과 행동유도가이드가 필요할 것 같습니다.
2.접근성 향상을 위한 레이아웃 정립
>프로토타입
3.여백 관리
4.언어 명시 정립
5.모션의 방향성
> 위아래와 좌우 > 좌우보다는 위아래가 접근성이 높습니다.
![image](https://user-images.githubusercontent.com/47623887/52907908-6ca59500-32ae-11e9-8910-4685520690b6.png)

**Comment by Jinakimm** [comment]
변경사항 적용해서 재업로드 합니다

![17](https://user-images.githubusercontent.com/47623887/53301352-f21fdb00-3894-11e9-8a5e-e7daf375138d.jpg)

**Comment by eleutheria80** [comment]
@opensrcdesign-admin , @kshahn , @opensrcdesign-admin 디자인 파트에서 지속적으로 디자인 의견을 올려주고 있는데 해당 내용 검토 후 피드백 남겨주세요.

**Comment by Jinakimm** [comment]
회의 때 전반적인 이야기를 가볍게 나눴습니다
아직 의견 수렴이 정확히 되지 않은 것 같아서 일단은 저번 회의 때 받은 피드백을 중심으로 다시 디자인을 해서 올려보도록 하겠습니다
다른 이슈들과 같이 정해진 due date는 없을 것 같습니다
