### ISSUE TITLE
[기타] 시간설정

### ISSUE THREAD

**Issue by opensrcdesign-admin** [kmu-crc/osd_front#99]
new Date().getTime() 으로 현재시간 얻어오고 있음.
환경(타임존)에 따라 값이 이상해지는(마이너스값이됨) 경우가 생김.

해결방안으로는 접손한 타임존에 맞게 설정하여 시간을 설정하는 방법으로
조사 후 아래에 커맨트하겠음.

**Comment by kimgyuri** [comment]
커멘트 달아주시면 후에 일정 올리도록 하겠습니다.

**Comment by ggamsang** [comment]
다시 내꺼!
이거 현재 오픈소스사이트에서는 문제없이 작동하고 있어서(코드가 그렇게 되어있어서)
 3월에 처리할거임.

**Comment by ggamsang** [comment]
현재 "방금전", "x분 전", "x시간 전", "x달 전" 과 같이 출력되고 있다.
여기에 "x.x년 전"과 같이 출력되도록 추가한다.
due date: 02.24

**Comment by opensrcdesign-admin** [comment]
머지함.

**Comment by kimgyuri** [comment]
저 어싸인 제외 부탁드려용~
